### ISSUE TITLE
Add/Update/Delete not working on Trigger Events

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#1]
#### Page Title
Advanced Traffic Pumping Fraud Triggers by Calling Number

#### Legacy URL
N/A

#### New URL
http://172.16.4.93:9080/ui2/Fraud-Control/CDR-Analytics-Advanced/By-Calling-Number/Traffic-Pumping/Trigger-Thresholds

#### Description of issue
See title

**Comment by fenichelar** [comment]
@DmitryIsakbayev 

http://172.16.4.32:7080/analyzer/cgi-bin/action/deleteReportTrigger.exe&key=fraudscoresourceplustriggerbycallingnumbercountrycode;wild%20card;wild%20card;101;1%20%20%20%20%20%20%20%20usa

What is wrong with the above URL?

**Comment by fenichelar** [comment]
@JimDalton 

For this page and any others like it, the unique value should be 'Key' instead of 'key'.

**Comment by DmitryIsakbayev** [comment]
The URL should use ? instead of &
deleteReportTrigger.exe?key=

**Comment by JimDalton** [comment]
Changed column.0.title from Key to key to match page.unique value.

**Comment by fenichelar** [comment]
Thank you. Fixed.
