### ISSUE TITLE
Server Error on Email Processing Scheduling Page

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#10]
#### Page Title
CDRs Processed Alert Configuration

#### Legacy URL
http://172.16.4.32:7080/analyzer/Fraud_Analytics_for_CDRs_for_Basic_for_Configuration_for_Email_for_Alert_Schedule_for_Alert_Schedule.htm

#### New URL
http://172.16.4.93:9080/ui2/Fraud-Control/CDR-Analytics-Basic/Configuration/Email/Alert-Schedule

#### Description of issue
This page cannot view or update data.

paths.view=/analyzer/cgi-bin/data/getKeyValueInPropertiesFile.exe?dir=..%2F..%2F..%2Fetc&file=AlertSchedule.etckeyName=PATHMASK

paths.update=/analyzer/cgi-bin/action/setKeyValueInPropertiesFile.exe?dir=..%2F..%2F..%2Fetc&file=AlertSchedule.etckeyName=PATHMASK

Screenshot:
![image](https://cloud.githubusercontent.com/assets/18315382/14887159/88422b84-0d22-11e6-86d1-4fa75bdf619e.png)

**Comment by DmitryIsakbayev** [comment]
The paths.view and paths.update URLs need the & delimiter
between file=AlertSchedule.etc*&*keyName=PATHMASK

**Comment by fenichelar** [comment]
Beat me to it Dmitry! I tested and that solves the problem.
