### ISSUE TITLE
View or Download Exported Rate Plans

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#100]
#### URL
Old UI: /billing/oss_billing_exported_rates.htm

#### Description of issue
paths.list;   paths.view;   paths.download;   paths.deleteFile

**Comment by DmitryIsakbayev** [comment]
paths.list - `/logs/cgi-bin/data/listLogFiles.exe?dir=../../../EXPORTED_RATE_PLANS&fileMask=.*.RP.txt.*&lastFileFirst=false&sortOrder=dsc`

paths.view and path.download - `/logs/cgi-bin/data/getLogFile.exe?dir=../../../EXPORTED_RATE_PLANS&file=PATHMASK`

paths.deleteFile - `/cgi-bin/action/rates/deleteRejected?dir=EXPORTED_RATE_PLANS&file=PATHMASK`

**Comment by JimDalton** [comment]
Updated Config File - Need to test

**Comment by JimDalton** [comment]
Change page type from data-view to file-viewer.
Need to test

**Comment by DmitryIsakbayev** [comment]
In order to fix the "delete rate plans" problem, please update paths.deleteFile
from `/cgi-bin/action/rates/deleteRejected?dir=EXPORTED_RATE_PLANS&file=PATHMASK`
to     `/cgi-bin/action/rates/deleteRejected?dir=EXPORTED_RATE_PLANS/&file=PATHMASK`

**Comment by JimDalton** [comment]
Update paths.deleteFile to be `/cgi-bin/action/rates/deleteRejected?dir=EXPORTED_RATE_PLANS/&file=PATHMASK`

Need to test

**Comment by JimDalton** [comment]
Worked as expected.  Took less than 30 seconds to view rate plan with 1.6 million rows.
