### ISSUE TITLE
Dashboard / Monitor / Resources  - Two Issues

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#101]
#### Description of issue
1) The Go To Page links go to pages showing log messages.  These links should go to pages with a history of the resource utilization.  Also 9 pages do not have a Go To Page link.

2) Swap Space and IOPS data are absolute values.  Everything else is a % utilization.  
   a) Change Swap Space data to a utilization %  from the calculation of swap space used divided by error threshold (4GB).  Also, please note that when swap space exceeds if warning threshold or error threshold, a message should be logged in NexOSS-resurce-warning.res file.  This is not happening.
   b) Remove IOPS data from  this page.  It is good data, but is out of place on this page which is a summary of utilization alarms.  IOPS data would be a good fit for this page if we could set warning and error thresholds for IOPS.  

New Request: Please change the Resource Name "Background Applications" to "Java Memory Allocation".

![image](https://cloud.githubusercontent.com/assets/18315382/16693928/9126d194-4505-11e6-9499-a1382ad8e1ed.png)

**Comment by DmitryIsakbayev** [comment]
o Removed IOPS (etc/NexStat.etc)
      o Redefined swap utilization task from used to used / total
      o Changed resource name Background Applications to Java Memory (etc/FileStat.etc)
      o Synchronized 7 Unique Page Ids bentween the UI and etc/NexStat.etc

**Comment by JimDalton** [comment]
All changes look good - thank you.
However, there is one typo in the Description for Prepaid Billing:
Run c1-redit check and update May Orignate status of Accounts in OSPrey"
Please change c1-redit to credit.

**Comment by fenichelar** [comment]
Resolved. Please test tomorrow.

**Comment by JimDalton** [comment]
Corrected.
