### ISSUE TITLE
Change Status Color Names so they can be pre-sorted for users 

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#102]
#### Description of issue
For Dashboard pages (Resources, Processes, Triggers) it is easier for users if the rows with a red status are presented at the top of the page.  Proposed solution is:
1) Change status color names to 0-Green, 1-Yellow, 2-Red in NexOSS.
2) Set columns.X.order to 0 for status data so it is the first (left most column) in a table.  Ember sorts reports for presentation based on the first column.
3) Change Ember to perform descending sort when columns.0.type is color.

**Comment by DmitryIsakbayev** [comment]
Changed status color labels to 0-green, 1-yellow, 2-red in NexOSS 8.9.26

**Comment by fenichelar** [comment]
Jim, please follow step 2 for any pages you wish to be sorted by color.

**Comment by fenichelar** [comment]
Add color grey - for me

**Comment by fenichelar** [comment]
From Jim - "Need to pre-sort view of Monitors of Resources, Processes and Triggers pages by colors: Red, Yellow and green."

**Comment by fenichelar** [comment]
@JimDalton What order should grey appear?

1-Red
2-Yellow
3-Green

**Comment by fenichelar** [comment]
@DmitryIsakbayev Resolved in Sails. Feel free to remove in NexOSS however it will not cause a problem if you leave it.

**Comment by fenichelar** [comment]
@JimDalton Please change color to first column if you wish to sort by color automatically.

**Comment by JimDalton** [comment]
Swap column order for Resource and Status on Resources page.
Need to test

**Comment by JimDalton** [comment]
Works as expected.
![image](https://cloud.githubusercontent.com/assets/18315382/17338332/0d789990-58b5-11e6-8f2e-a6ee6345145f.png)
