### ISSUE TITLE
Dashboard / Monitor / Resources / CPU Utilization

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#103]
This issue is focused on the the recreation of the following two pages from the old UI.
Chart-Total CPU                             /logs/oss_stats_chart_cpu_utilization.htm
Chart-CPU used by applications    /logs/oss_stats_chart_cpu_alarm.htm

The the Chart-Total CPU page shows CPU utilization by User, System, Wait and Steal.  The purpose of this chart is to help identify the cause of high CPU utilization.

The Chart-CPU used by applications (bad name) is used to trigger an alarm when CPU utilization exceeds 90% and also to provide a chart of historical utilization compared to the warning and error thresholds.

#### Description of issue
The following two paths provide the same data.

Chart-Total CPU
path.view - /logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.NexOSS_CPU_Alarm.

Chart CPU used by Applications
path.view - /logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.NexOSS_CPU.

The NexOSS_CPU_Alarm data looks correct.

The NexOSS_CPU data should show CPU by user, system, wait and steal. It does not
 
To avoid confusion, please provide the following:
For Chart-Total CPU                             /logs/oss_stats_chart_cpu_utilization.htm
- paths.view
- column numbers for User, System, Wait and Steal data.
- Please convert data to a percentage
- Please check the data provided matches what is presented in the old UI
- The existing help note says: "This page shows CPU utilization of host server by running vmstat command."  Please provide the exact syntax for running this linux command.  Are there other instructions user need to know to run this command? 

Chart-CPU used by applications    /logs/oss_stats_chart_cpu_alarm.htm
- paths.view
- column numbers for Total CPU Utilization, Warning Threshold (80%) and Error Threshold (90%)
- Please convert data to a percentage
- Please check the data provided matches what is presented in the old UI
- The existing help note says: "This page shows CPU utilization."  Does this information come from the vmstat utility?

**Comment by DmitryIsakbayev** [comment]
Total:
paths.list
`/logs/cgi-bin/data/listLogFiles.exe?dir=../../../LOG&fileMask=NexOSS-Nex-Stat.res.*`

paths.view
`/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*;NexOSS_CPU;.*&tokenDelimiter=;&searchFor=,&replaceWith=;&convertColumnsToPercent=4,5,6,7`

column delimiter ;

column API:
dateTime
-1
-1
-1
userPercent
systemPercent
waitPercent
stealPercent

**Comment by DmitryIsakbayev** [comment]
By Applications:
Total:
paths.list
`/logs/cgi-bin/data/listLogFiles.exe?dir=../../../LOG&fileMask=NexOSS-Nex-Stat.res.*`

paths.view
`/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*;NexOSS_CPU_Alarm;.*&tokenDelimiter=;&convertColumnsToPercent=4,5,6`

column delimiter ;

column API:
dateTime
-1
-1
-1
utilizationPercent
warningThresholdPercent
errorThresholdPercent

**Comment by JimDalton** [comment]
Updated paths.view for Pages
Dashboard - Resources - Host Server - CPU Total
Dashboard - Resources - Host Server - CPU Components
Need to test

**Comment by JimDalton** [comment]
Works as expected.
