### ISSUE TITLE
Chart Memory Total

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#104]
#### Description of issue
This page is intended to be a recreation of the following page in the old UI.
Chart-Total Memory            /logs/oss_stats_chart_mem_utilization.htm
The purpose of this chart is to show the user the share of memory being used for cache, buffers and applications.

I need the following configuration information.
- paths.view
- column numbers for memory utilization by cache, buffers and applications.
- Data provided as a percentage value.
- Please verify the data being provided is the same as the data displayed on the old UI.
- The help comment provided by Jinyoun for this page is: "This page shows memory utilization of host server by the free command in Linux utilities."  Please provide the exact syntax of the free command so I can include it in our help comments.  Are their other instructions a user needs to know to run this command?

**Comment by DmitryIsakbayev** [comment]
The output of "free" has changed in CentOS 7.  It requires "-w" flag and the "used" value no longer includes "buffers" and "cache"
Sample output of free -w
                       total        used        free       shared     buffers      cache       available
Mem:       64261872    12977824      937276    14869576       12644    50334128    36105664
Swap:      16908280     2561928    14346352

**Comment by DmitryIsakbayev** [comment]
paths.list
/logs/cgi-bin/data/listLogFiles.exe?dir=../../../LOG&fileMask=NexOSS-Nex-Stat.res.*

paths.view
/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*;NexOSS_Memory;.*&tokenDelimiter=;&searchFor=,&replaceWith=;&convertColumnsToPercent=4,5,6

column delimiter ;

column API:
dateTime
-1
-1
-1
cachedPercent
buffersPercent
applicationsPercent

**Comment by JimDalton** [comment]
Updated paths.view
Need to test

**Comment by JimDalton** [comment]
Change column types from percentage to number.
Need to test,

**Comment by JimDalton** [comment]
Data looks as expected.
