### ISSUE TITLE
Chart Memory Used by Application

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#105]
#### Description of issue
The purpose of this issue to recreate the following page from the old UI as a table on the new UI
Chart-Memory used by Applications      
Old UI: /logs/oss_stats_chart_mem_alarm.htm

The purpose of this page is track memory used by applications only because this data trend is a better indicator of when memory resources are becoming too low.  

The help notes on the old UI state:
"This statistic, from the free command in Linux utility, shows memory utilization of host server. An alarm is set when the following value, (used memory - cached memory - buffered memory) / (total memory) is more than the threshold."

The data current displayed in the new UI shows utilization as a negative number.  

Please provide the following configuration data for the new UI:
- paths.view
- Column numbers for memory utilization, Warning threshold (80%) and Error Threshold (90%)
- Please convert the data to precent.
- Please check the data agrees with what is displayed on the old UI.  If the calculation for memory utilization is negative, please correct the calculation.

**Comment by DmitryIsakbayev** [comment]
This is still a work in progress.
/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=NexOSS-Nex-Stat.res&searchKey=.*;NexOSS_Memory;.*&tokenDelimiter=;&searchFor=,&replaceWith=;&convertColumnsToPercent=4,5,6

**Comment by DmitryIsakbayev** [comment]
paths.list
`/logs/cgi-bin/data/listLogFiles.exe?dir=../../../LOG&fileMask=NexOSS-Nex-Stat.res.*`

paths.view
`/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*;NexOSS_Memory;.*&tokenDelimiter=;&searchFor=,&replaceWith=;&convertColumnsToPercent=4,5,6`

column delimiter ;

column API:
dateTime
-1
-1
-1
cachedPercent
buffersPercent
applicationsPercent

**Comment by DmitryIsakbayev** [comment]
The instructions above are actually for #104

**Comment by DmitryIsakbayev** [comment]
Updated instructions

paths.list
/logs/cgi-bin/data/listLogFiles.exe?dir=../../../LOG&fileMask=NexOSS-Nex-Stat.res.*

paths.view
/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*;NexOSS_Memory_Alarm;.*&tokenDelimiter=;&convertColumnsToPercent=4,5,6

column delimiter ;

column API:
dateTime
-1
-1
-1
totalPercent
warningThresholdPercent
errorThresholdPercent

**Comment by JimDalton** [comment]
Works as expected
