### ISSUE TITLE
NexOSS Database Partition

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#109]
#### Description of issue
The purpose of this page is to display the space available in the partition hosting the database.

This page has been configured for the new UI, but "No matching records found".  A screenshot of the new page is shown below.

The paths.view is
/analyzer/cgi-bin/data/downloadTable.exe?sql=select OSS_Updated,OSS_DbFree,OSS_DbUsed,OSS_DbTotal,OSS_DbFree/(OSS_DbFree+OSS_DbUsed),OSS_DbUsed/(OSS_DbFree+OSS_DbUsed),1.0 from NEXOSS_STATUS_TB order by OSS_Updated DESC

Please provide a paths.view for this page.
Please test the paths.view url

![image](https://cloud.githubusercontent.com/assets/18315382/16710330/7634587c-45f8-11e6-9f31-e2c93cd6b1b9.png)

**Comment by DmitryIsakbayev** [comment]
Need to url encode + as %2B
and suppress information about the number of rows and column names.  The showColumnCount and showColumnHeaders parameters will be supported in NexOSS v.8.9.24.

The updated paths.view is
`/analyzer/cgi-bin/data/downloadTable.exe?showColumnCount=false& showColumnHeaders=false&sql=select OSS_Updated,OSS_DbFree,OSS_DbUsed,OSS_DbTotal,OSS_DbFree/(OSS_DbFree%2BOSS_DbUsed),OSS_DbUsed/(OSS_DbFree%2BOSS_DbUsed),1.0 from NEXOSS_STATUS_TB order by OSS_Updated DESC`

**Comment by JimDalton** [comment]
Updated paths.view.  Need to test with NexOSS V8.9.24

**Comment by JimDalton** [comment]
Test with 8.9.24.  Still not working as expected.  I need help trouble shooting this problem


Example of the status file downloaded directly from Chrome.
ColumnCount=7
OSS_UPDATED	OSS_DBFREE	OSS_DBUSED	OSS_DBTOTAL	OSS_DBFREE/(OSS_DBFREE+OSS_DBUSED)	OSS_DBUSED/(OSS_DBFREE+OSS_DBUSED)	1.0
2016-07-19 09:06:17.187	29.149	60.851	90	3.23877777777777777777777777777777777778E-01	6.76122222222222222222222222222222222222E-01	1
2016-07-19 08:06:14.78	29.149	60.851	90	3.23877777777777777777777777777777777778E-01	6.76122222222222222222222222222222222222E-01	1
2016-07-19 07:06:11.964	29.149	60.851	90	3.23877777777777777777777777777777777778E-01	6.76122222222222222222222222222222222222E-01	1

**Comment by DmitryIsakbayev** [comment]
Please re-test with NexOSS 8.9.25 - synchronized downloadTable with viewTable API to suipport showColumnCount and showColumnHeaders parameters

**Comment by JimDalton** [comment]
Tested on 8.9.25, but still no matching records for this report.  Tried adding ; /t and | delimiters to Edit interface and saved the change, but still no matching records for the report.  The Status file (below) returned by the paths.view url looks OK.
DO not understand the problem - Need help trouble shooting.
OSS_UPDATED	OSS_DBFREE	OSS_DBUSED	OSS_DBTOTAL	OSS_DBFREE/(OSS_DBFREE+OSS_DBUSED)	OSS_DBUSED/(OSS_DBFREE+OSS_DBUSED)	1.0
2016-07-20 19:06:12.212	29.149	60.851	90	3.23877777777777777777777777777777777778E-01	6.76122222222222222222222222222222222222E-01	1
2016-07-20 18:09:06.098	29.149	60.851	90	3.23877777777777777777777777777777777778E-01	6.76122222222222222222222222222222222222E-01	1
2016-07-20 17:08:53.797	29.149	60.851	90	3.23877777777777777777777777777777777778E-01	6.76122222222222222222222222222222222222E-01	1

**Comment by DmitryIsakbayev** [comment]
Alec, is it ok that some of the numbers are in scientific notation?

**Comment by fenichelar** [comment]
@DmitryIsakbayev I believe so.

This issue is being caused by spaces in the url. Please remove all spaces in the url.

Another issue is the response. The response includes 2 header lines that need to be removed.

**Comment by DmitryIsakbayev** [comment]
Updated URL to :
disable showColumnCount and showColumnHeaders 
url encoded spaces (as %20)
use DbPartitionTotal and OSS_DbPartitionFree instead of OSS_DbFree and OSS_DbUsed

There is a bug - the NexOssStatusCheck application did not calculate OSS_DbPartitionTotal and OSS_DbPartitionFree columns of the NEXOSS_STATUS_TB table.  Will need to retest after upgrading to NexOSS - 8.9.27

update url
`/analyzer/cgi-bin/data/downloadTable.exe?showColumnCount=false&showColumnHeaders=false&sql=select%20OSS_Updated,OSS_DbPartitionFree,OSS_DbPartitionTotal-OSS_DbPartitionTotal,OSS_DbPartitionTotal,OSS_DbPartitionFree/OSS_DbPartitionTotal,(OSS_DbPartitionTotal-OSS_DbPartitionFree)/OSS_DbPartitionTotal,1.0%20from%20NEXOSS_STATUS_TB%20order%20by%20OSS_Updated%20DESC`

**Comment by DmitryIsakbayev** [comment]
Please change column delimiter from ";' to tab

**Comment by JimDalton** [comment]
Updated paths.view and delimiter
Need to test

**Comment by DmitryIsakbayev** [comment]
The error is "SQLDataException: ORA-01476: divisor is equal to zero"  We need to protect the SQL from rows where OSS_DbPartitionTotal is 0.

Here is the updated paths.view (after url encoding spaces as %20 and > as %3E)

`/analyzer/cgi-bin/data/downloadTable.exe?showColumnCount=false&showColumnHeaders=false&sql=select%20OSS_Updated,OSS_DbPartitionFree,OSS_DbPartitionTotal-OSS_DbPartitionTotal,OSS_DbPartitionTotal,OSS_DbPartitionFree/OSS_DbPartitionTotal,(OSS_DbPartitionTotal-OSS_DbPartitionFree)/OSS_DbPartitionTotal,1.0%20from%20NEXOSS_STATUS_TB%20where%20OSS_DbPartitionTotal%3E0%20order%20by%20OSS_Updated%20DESC`

The update is already on .93

**Comment by fenichelar** [comment]
@JimDalton Please update the urls above.

**Comment by JimDalton** [comment]
Updated Config.  Need to test

**Comment by JimDalton** [comment]
Changed OSS_DbPartitionTotal-OSS_DbPartitionTotal to OSS_DbPartitionTotal-OSS_DbPartitionFree in paths.view.
Need to test

**Comment by JimDalton** [comment]
Work as expected on .93
