### ISSUE TITLE
NexOSS Database Tables

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#110]
#### Description of issue

This page requirement for the new UI replace the second table displayed on the old UI at:
/logs/oss_resources_nexoss_db_status.htm

A nice feature of the old UI, was a chart for each table that displays the growth of each table over the previous 30 days.

Need a page on the new UI that presents the size of all NexOSS database tables.

**Comment by DmitryIsakbayev** [comment]
The SQL for selecting the data set is
`select
	OSS_TABLES.tabletype,
	NEXOSS_STATUS_DETAILS_TB.tablename,
	NEXOSS_STATUS_DETAILS_TB.rowcount
from
	OSS_TABLES,
	NEXOSS_STATUS_DETAILS_TB
where
	NEXOSS_STATUS_DETAILS_TB.updated = (select max(updated) from NEXOSS_STATUS_DETAILS_TB)
	and
	NEXOSS_STATUS_DETAILS_TB.tablename = OSS_TABLES.tablename
	and
	OSS_TABLES.application = 'OSS'`

The paths.view url is
`/analyzer/cgi-bin/data/downloadTable.exe?showColumnCount=false&showColumnHeaders=false&sql=select%20OSS_TABLES.tabletype,NEXOSS_STATUS_DETAILS_TB.tablename,NEXOSS_STATUS_DETAILS_TB.rowcount%20from%20OSS_TABLES,NEXOSS_STATUS_DETAILS_TB%20where%20NEXOSS_STATUS_DETAILS_TB.updated=(select%20max(updated)%20from%20NEXOSS_STATUS_DETAILS_TB)%20and%20NEXOSS_STATUS_DETAILS_TB.tablename=OSS_TABLES.tablename%20and%20OSS_TABLES.application=%27OSS%27`

Columns API:
tableType (such as RATE, CDR, OTHER)
tableName
rowCount

Column delimiter: TAB

**Comment by DmitryIsakbayev** [comment]
The SQL for selecting history for a specific page is
`select
	updated,
	rowcount
from 
	NEXOSS_STATUS_DETAILS_TB
where
	tablename='RATEDCDR'`

The paths.view is url (disable column count and column headers, url escape spaces as %20 and single quotes as %27)
`/analyzer/cgi-bin/data/downloadTable.exe?showColumnCount=false&showColumnHeaders=false&sql=select%20updated,rowcount%20from%20NEXOSS_STATUS_DETAILS_TB%20where%20tablename=%27RATEDCDR%27`

Alec, how do we link the summary view to the detail view for each page?  The linking variable is the table name.

**Comment by JimDalton** [comment]
Added paths.view,  3 columns and delimiter.
Need to test and to add links to tables that provide a history of row data per table.

**Comment by fenichelar** [comment]
@DmitryIsakbayev can you make the paths.view url function like the other non-sql APIs? The same thing you did with the export rate plan API.

I am looking into how to do the linking.

**Comment by DmitryIsakbayev** [comment]
@fenichelar the paths.view for both the summary and detail views are already defined to use the /analyzer/cgi-bin/data/downloadTable.exe API.

**Comment by fenichelar** [comment]
@DmitryIsakbayev For the detail view:

`/analyzer/cgi-bin/data/downloadTable.exe?showColumnCount=false&showColumnHeaders=false&sql=select%20updated,rowcount%20from%20NEXOSS_STATUS_DETAILS_TB%20where%20tablename=%27RATEDCDR%27`

this is very different than the rest of the charts. Can it function more like this:

`/analyzer/cgi-bin/data/downloadTable.exe?showColumnCount=false&showColumnHeaders=false&sqlDatabaseName=NEXOSS_STATUS_DETAILS_TB&sqlTableName=RATEDCDR`

**Comment by DmitryIsakbayev** [comment]
I think I am following now.  How about something like -

`/analyzer/cgi-bin/data/downloadTable.exe?showColumnCount=false&showColumnHeaders=false&sql=select%20updated,rowcount%20from%20NEXOSS_STATUS_DETAILS_TB&whereCondition1=tableName`

and then the UI would append `&tableName=xxxxxxx`

**Comment by fenichelar** [comment]
@DmitryIsakbayev that would work well. And you give me the `tableName` in the summary view?

**Comment by DmitryIsakbayev** [comment]
Yes.

**Comment by DmitryIsakbayev** [comment]
Will extend the downloadTable API to support whereCondition1 parameter in NexOSS 8.9.31.

**Comment by fenichelar** [comment]
Waiting for NexOSS 8.9.31 to be released and installed before continuing.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Can you duplicate the table name in the summary view? Like this:
OTHER	ACCOUNTINVOICE		1969	ACCOUNTINVOICE
...

Columns API:
tableType (such as RATE, CDR, OTHER)
tableName
rowCount
tableName

The order doesn't matter.

**Comment by DmitryIsakbayev** [comment]
Sure.   We can extended the SQL statement to include the tableName twice.  The updated paths.view url is
`/analyzer/cgi-bin/data/downloadTable.exe?showColumnCount=false&showColumnHeaders=false&sql=select%20OSS_TABLES.tabletype,NEXOSS_STATUS_DETAILS_TB.tablename,NEXOSS_STATUS_DETAILS_TB.rowcount,NEXOSS_STATUS_DETAILS_TB.tablename%20from%20OSS_TABLES,NEXOSS_STATUS_DETAILS_TB%20where%20NEXOSS_STATUS_DETAILS_TB.updated=(select%20max(updated)%20from%20NEXOSS_STATUS_DETAILS_TB)%20and%20NEXOSS_STATUS_DETAILS_TB.tablename=OSS_TABLES.tablename%20and%20OSS_TABLES.application=%27OSS%27`

**Comment by fenichelar** [comment]
Done. Please test.

**Comment by JimDalton** [comment]
@fenichelar    The database table charts looks good.  However, the X axis value labels for date-time stamps go to milliseconds.  Can these X-axis values be shortened to YYYY-MM-DD hh:mm?

**Comment by fenichelar** [comment]
@DmitryIsakbayev Is this something you can handle? I currently just display exactly what you give me in the X axis.

**Comment by DmitryIsakbayev** [comment]
Yes.  Since it is a sql statement, we can use the sub-string function to truncate the time stamp to the first 10 characters.  Please test.

**Comment by JimDalton** [comment]
Done
