### ISSUE TITLE
Fix Utilization % Calculation for Java Memory for applications 

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#112]
#### Description of issue
I think this issue applies to all pages that log the memory utilization of java applications.

Below is a screenshot of the Resources NexOSS-Replication-Configuration.res file.
I assume that column 5 is the utilization calculated by Jinyoun's original implementation.  Column 5 data looks like utilization followed by a % sign.  This value cannot be graphed in the UI because it is text.  

Column 6, utilization calculated as decimal value, is always zero.  We need this utilization value so utilization can be charted with the warning and error thresholds.  Please update the calculation of this value.

![image](https://cloud.githubusercontent.com/assets/18315382/16716630/faa48780-46cf-11e6-9d19-1a55c3e5dd7f.png)

**Comment by DmitryIsakbayev** [comment]
I think it is because the utilization value is up to 2 decimal places and the actual utilization is less than 1%.  It works for the web server stats where utilization is more than 1%.  I will increase the format to 4 decimal places in NexOSS v.8.9.24

**Comment by JimDalton** [comment]
Works as expected
