### ISSUE TITLE
OSPrey License

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#113]
#### Description of issue
Response Time and License Utilization values are text.  The words ""Maximum" for Response Time and "Average" for License Utilization need to be removed so Response Time data can be type=number and License Utilization data can be type=percentage so the data can be charted.

In addition, we need a new feature to receive an e-mail message when the total license utilization exceeds 100%.  Let's discuss when you are ready.

![image](https://cloud.githubusercontent.com/assets/18315382/16717425/f23be46c-46e3-11e6-8f5d-7332df3e4b2e.png)

**Comment by DmitryIsakbayev** [comment]
Words "Maximum" and "Average" will be removed in NexOSS v.8.9.24.
Error logs are already being generated (which can be forwarded via email) according to the following values:

OSPreyMonitor.LicenseUtilization.IsEnabled=true
OSPreyMonitor.LicenseUtilization.WarningThreshold=80.0
OSPreyMonitor.LicenseUtilizatoin.ErrorThreshold=90.0

OSPreyMonitor.ResponseTime.IsEnabled=true
OSPreyMonitor.ResponseTime.WarningThreshold=350000
OSPreyMonitor.ResponseTime.ErrorThreshold=600000

OSPreyMonitor.MPHLicenseUtilization.IsEnabled=true
OSPreyMonitor.MPHLicenseUtilization.WarningThreshold=80.0
OSPreyMonitor.MPHLicenseUtilization.ErrorThreshold=90.0

**Comment by DmitryIsakbayev** [comment]
paths.list = `/logs/cgi-bin/data/listLogFiles.exe?dir=../../../LOG&fileMask=OSPrey-License-Usage.res.*`
paths.view = `/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK`
Column API:
dataTimeStamp
-1
-1
server
responseTime
callsProcessed
callsThreshold
-1
utilization

**Comment by JimDalton** [comment]
What is the delimiter for this page?  ; or /t

**Comment by DmitryIsakbayev** [comment]
The delimiter is ;

**Comment by JimDalton** [comment]
Update config file.  Need to test

**Comment by JimDalton** [comment]
Work as expected
