### ISSUE TITLE
Only Display Graph Button for tables that have Date-Time as column1

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#114]
Fewer buttons, when possible, is better.

All of our charts are time series charts, so we should only have charts for time series data.

**Comment by fenichelar** [comment]
Done. Please test.

**Comment by JimDalton** [comment]
Graph button is still on the Devices page  (/Accounts_Devices)
![image](https://cloud.githubusercontent.com/assets/18315382/16818342/388ecc94-4915-11e6-9400-a5040be75e0a.png)

**Comment by fenichelar** [comment]
Please test.

**Comment by fenichelar** [comment]
Reverted back to original.

**Comment by fenichelar** [comment]
Please determine what other pages will be necessary. Maybe instead search for the word "date" and the word "time". If either match in the first column, display the graph button.

**Comment by JimDalton** [comment]
Log files have Date - Time as the first column title and a  chart button makes no sense for those pages.   I think you suggested that the chart button would be added to any page that had Date - Time as the first column and contained another column that was either type number or percentage. I think this is the best idea we have discussed.   Is this possible?  Can the Chart Button be a configurable option by page?

**Comment by fenichelar** [comment]
@JimDalton I am not sure I am following.

You do or don't want charts for log files?

Also, the problem with using Date - Time is that some pages need charts that don't have `Date - Time`. For example: `/Fraud-Control_CDR-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Report` and drill down all the way.

We can do page by page config but what would the default be?

**Comment by fenichelar** [comment]
Done. Please test.

**Comment by JimDalton** [comment]
The graphs for pages that have time series data look good.
Having the graphs button on log pages does not make sense.  Can you remove the Graph button from pages that have Date - Time in column 1, but no data with type = percentage or number in the other columns?

**Comment by fenichelar** [comment]
Should be resolved tomorrow. Please test.

**Comment by JimDalton** [comment]
Works as expected
