### ISSUE TITLE
NexOSS Minutes Per Hour License

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#117]
#### Description of issue
Old UI = oss_rp_mins_processed.htm
In new UI, "No Matching Records Found" for the NexOSS Minutes per Hour table. 
paths.list = /logs/cgi-bin/data/listLogFiles.exe?dir=../../../LOG&fileMask=Minutes-Processed-Usage.res.*
paths.view = /analyzer/cgi-bin/data/getReportFile.exe?dir=../../../REPORTS/PATHMASK&file=details.txt&zippedDirLevel=5&fromLine=2

Is the correct url for the paths.view?

![image](https://cloud.githubusercontent.com/assets/18315382/16747742/70a65c38-478e-11e6-86aa-b86d7a788af7.png)

**Comment by DmitryIsakbayev** [comment]
The paths.view should be `/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK`
Will follow up with Column API.

**Comment by DmitryIsakbayev** [comment]
Column API:
dateTimeStamp
-1
-1
responseTime
minutesProcessed
minutesThreshold
-1
utilization

**Comment by JimDalton** [comment]
Updated Config File need to test

**Comment by JimDalton** [comment]
Works as expected.
