### ISSUE TITLE
No Section Titles

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#119]
#### Description of issue
No Section Title is displayed.
The sections.0.title = Routing Table Build Status, but it is not displayed.

Same issue with other pages that use sections.

![image](https://cloud.githubusercontent.com/assets/18315382/16818534/2fff6e48-4916-11e6-9e0d-33e897fa46a0.png)

**Comment by fenichelar** [comment]
Resolved. Please test.

**Comment by JimDalton** [comment]
Work as expected
