### ISSUE TITLE
Rate Plan Viewer

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#12]
#### Description of issue
In development.

**Comment by fenichelar** [comment]
paths.list
/logs/cgi-bin/data/listLogFiles.exe?dir=../../../REJECTED&fileMask=.*.ProviderRP.txt.*&lastFileFirst=false&sortOrder=dsc

paths.view
/logs/cgi-bin/data/getLogFile.exe?dir=../../../REJECTED&fromLine=11&searchKey=[^%23].*&file=PATHMASK

paths.deleteFile
/cgi-bin/action/rates/deleteRejected?file=PATHMASK

paths.download
/logs/cgi-bin/data/getLogFile.exe?dir=../../../REJECTED&file=PATHMASK

sections.headings.url
logs/cgi-bin/data/getLogFile.exe?dir=../../../REJECTED&fromLine=1&toLine=9&file=PATHMASK

sections.errors.url
/logs/cgi-bin/data/getLogFile.exe?dir=../../../REJECTED&fromLine=11&searchKey=[%23]Error.*&file=PATHMASK

sections.warnings.url
/logs/cgi-bin/data/getLogFile.exe?dir=../../../REJECTED&fromLine=11&searchKey=[%23]Warn.*&file=PATHMASK

**Comment by fenichelar** [comment]
REJECTED
ARCHIVE
WORK

**Comment by JimDalton** [comment]
Archived and Rejected Provider Rate Plan pages work as expected.
