### ISSUE TITLE
Document Schema for Users

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#121]
#### Description of issue

We need a document that describes parameters in the Ember configuration that are not obvious to users.
Page Type:  What are the choices, what are the characteristics of each page type.
Column Type: What are the choices, what are the characteristics of each column type
Section Type:  What are the choices, what are the characteristics of each section type
Section Key:  What is a section key?
Column Dependency: 

It would be excellent if this documentation was integrated with the edit interface so users could refer to these descriptions while editing.

**Comment by fenichelar** [comment]
@JimDalton Done. Please test tomorrow. Please let me know anything that needs to be changed/improved.

**Comment by JimDalton** [comment]
Thank you
