### ISSUE TITLE
Improvement Fraud Analysis Graphs

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#122]
#### Description of issue
Good looking, easy to understand graphs are great for demos and selling.
This requirement for better graphing has two components.

First, referring to the chart below.  The X-axis values are undefined.  I think this is because the X axis values are in the format of "Minutes mm:ss - mm:ss".  The chart would look better if this value was just the starting mm:ss value.  I will explain in help notes that the mm:ss is the start time.

Second, This chart needs a title that defines the data being charted.  The title shoud be the breadcrumb.  In this case it would be: Date / Account name / Device Name / Dial Code

![image](https://cloud.githubusercontent.com/assets/18315382/16849104/f3f6fe82-49c6-11e6-9ca1-7af84d74489d.png)

**Comment by fenichelar** [comment]
Done. Please test.

**Comment by JimDalton** [comment]
Work as expected
