### ISSUE TITLE
Added two Page Unique Ids to Config File

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#124]
#### Description of issue
Two Page Unique IDs have been added to the config file. 
/NexOSS-DatabaseSpace.htm
/CDRAnalyzer-DatabaseSpace.htm
These values are in the highlighted rows in the screenshot.
![image](https://cloud.githubusercontent.com/assets/18315382/16888595/14b7dd88-4aaf-11e6-90ad-42ad822a7f9d.png)

Need to synchronize Page UniqueIDs between NexOSS and config file.

Question for Dmitry
The CDRAnalyzer page is a new page I added to the new UI.  Following is my guess at the paths.view:
/analyzer/cgi-bin/data/downloadTable.exe?showColumnCount=false&showColumnHeaders=false&sql=select OSS_Updated,OSS_DbFree,OSS_DbUsed,OSS_DbTotal,OSS_DbFree/(OSS_DbFree%2BOSS_DbUsed),OSS_DbUsed/(OSS_DbFree%2BOSS_DbUsed),1.0 from CDRANALYZER_STATUS_TB order by OSS_Updated DESC
I replaced NEXOSS_STATUS_TB with CDRANALYZER_STATUS_TB.  Is this correct?

**Comment by DmitryIsakbayev** [comment]
The table name is STATUS_TB and the column names do not have the OSS_ prefix.  The paths.view should be `/analyzer/cgi-bin/data/downloadTable.exe?showColumnCount=false&showColumnHeaders=false&sql=select Updated,DbFree,DbUsed,DbTotal,DbFree/(DbFree%2BDbUsed),DbUsed/(DbFree%2BDbUsed),1.0 from STATUS_TB order by Updated DESC`

**Comment by JimDalton** [comment]
Added this page to config file for CDRAnalyzer.  Need to test.

**Comment by JimDalton** [comment]
Go To Page link to CDRAnalyzer Database space works as expected.
