### ISSUE TITLE
Two new UniquePageURLs - Please add these to NexOSS

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#125]
The screenshot below shows two new resource monitor utilization pages.
I have defined the following unique Ids for these two pages:
Resource Utilization Tables    New Unique ID
Inodes                                    Dashboard_Resources_Host-Server_Disk_Inodes
IOPS                                       Dashboard_Resources_Host-Server_Disk_IOPS

The IOPS page should not be included on the Resource Monitir list since every row on this page is presented as a % utilization.  

![image](https://cloud.githubusercontent.com/assets/18315382/16888729/df160960-4aaf-11e6-83c3-9e131b40bf9d.png)

**Comment by DmitryIsakbayev** [comment]
Updated etc/NexStat.etc (version 8.9.25)
