### ISSUE TITLE
Synchronize 5 UniqueIDs in NexOSS with Config File

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#126]
In the screenshot below are 6 highlighted rows.  5 of these rows have the PageUniqueURL in the right hand column.  These 5 rows correspond to resource utilization pages that exist in the legacy UI.
These page have the following unique IDs configured in the excel file.
Description on Resource Monitor Page              unique Id and Legacy url
=========================            ========================
Memory Utilization of the Host Server              /logs/oss_stats_chart_mem_alarm.htm
CPU Utilization of the Host Server                     /logs/oss_stats_chart_cpu_alarm.htm
Used SWap Space for the Host Server               /logs/oss_stats_chart_mem_swap.htm
CPU Utilization of the Web Server                      /logs/oss_stats_chart_nexoss_cpu.htm
Mem. util. by web svr as % of total host mem.   /logs/oss_stats_chart_nexoss_mem.htm
 
![image](https://cloud.githubusercontent.com/assets/18315382/16888920/f01f82ee-4ab0-11e6-8a09-c8fb5f1d9787.png)

**Comment by DmitryIsakbayev** [comment]
Updated etc/NexStat.etc (version 8.9.25)

**Comment by JimDalton** [comment]
Need to test with NeexOSS V 8.9.25

**Comment by JimDalton** [comment]
Tested with NexOSS V8.9.25.  Page looks better.  Remaining Requirements
1) Remove the row for Total IOPS
2) Swap space data is presented as percent utilization, but the data is the actual Swap space.  Need to present Swap utilization as a percent calculated from (Actual swap space used / 4000 MB).  An present warning and error thresholds as 50% and 100%.
3) Change Resource name Background Applications to Java Memory
4) Make default sorting for this page by the Status column with Red Status on top, followed by yellow and green. 

Question: In the screenshot below, why does Dashboard_Resources_Host-Server_Disk_Inodes appear instead of a Go To Page button?
![image](https://cloud.githubusercontent.com/assets/18315382/17005062/2a4939f8-4ea6-11e6-983a-a4632e90a2b4.png)

**Comment by DmitryIsakbayev** [comment]
NexOSS 8.9.26
      o Removed IOPS (etc/NexStat.etc)
      o Redefined swap utilization task from used to used / total
      o Changed resource name Background Applications to Java Memory (etc/FileStat.etc)
      o Changed status color labels to 0-green, 1-yellow, 2-red (for presorting by color)

>>Question: In the screenshot below, why does Dashboard_Resources_Host-Server_Disk_Inodes appear instead of a Go To Page button?
I think it is because the link is broken.  The detail page is not defined.

**Comment by JimDalton** [comment]
> Question: In the screenshot below, why does Dashboard_Resources_Host-Server_Disk_Inodes appear instead of a Go To Page button?



> I think it is because the link is broken. The detail page is not defined.

 

Yes! That is the reason.  Thank you.
