### ISSUE TITLE
Cannot add Subnet

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#127]
#### Description of issue

Cannot add a subnet.  
The paths.add url in the config file is /cgi-bin/action/devnew2

Below is a copy of the url to add a subnet from the java console.
/cgi-bin/action/devnew2?group=00-TestNewUI&shortName=testSubNetAdd&address=4.4.4.4&mayTerminate=false&hasEnrolled=false&protocol=SIP&ospVersion=0.0.0&inPrefix=&outPrefix=&isOnline=false&bitMaskLength=31&networkId=&stripInPrefix=false&inMaxCallBurstPerMinute=60000&inCallGappingInSeconds=0.001&outMaxCallBurstPerMinute=60000&outCallGappingInSeconds=0.001&outCallingPrefix=&mandDestAttribute=&prefDestAttribute=&port=&supportsNPDI=true&supportsRN=true&enableMultiLegMediation=false&useCDRMediationRulesFor=All_Other_Devices&addLRNToOutPrefix=false&changeDefaultOutPrefixOrder=false&noLoopBackToDevice=false

**Comment by fenichelar** [comment]
Resolved. Please test.

**Comment by JimDalton** [comment]
Tried to add a subnet.  Something went wrong.

**Comment by fenichelar** [comment]
I can't reproduce. I am able to add subnets.

**Comment by JimDalton** [comment]
I also could not reproduce the problem.
Works as expected.
