### ISSUE TITLE
Cannot Add a Device

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#128]
#### Description of issue
Cannot add a device.
The paths.add url in the config file is: /cgi-bin/action/devnew2

Url taken from Java console when adding a device.
/cgi-bin/action/devnew2?group=00-TestNewUI&shortName=AddATestDEvice&address=56.78.90.12&mayTerminate=false&hasEnrolled=false&protocol=SIP&ospVersion=0.0.0&inPrefix=&outPrefix=&isOnline=false&bitMaskLength=32&networkId=&stripInPrefix=false&inMaxCallBurstPerMinute=60000&inCallGappingInSeconds=0.001&outMaxCallBurstPerMinute=60000&outCallGappingInSeconds=0.001&outCallingPrefix=&mandDestAttribute=&prefDestAttribute=&port=&supportsNPDI=true&supportsRN=true&enableMultiLegMediation=false&useCDRMediationRulesFor=All_Other_Devices&addLRNToOutPrefix=false&changeDefaultOutPrefixOrder=false&noLoopBackToDevice=false

**Comment by fenichelar** [comment]
Please test.

**Comment by JimDalton** [comment]
Worked as expected.
