### ISSUE TITLE
Dropdown boxes in modal to add a Fraud Trigger are wrong.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#129]
Old Url: /analyzer/Fraud_Analytics_for_SIP_for_Basic_for_By_Customer_Device_for_Traffic_Pumping_for_Trigger_Report_for_Traffic_Report.htm

New Url: /Fraud-Control_SIP-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Thresholds

#### Description of issue
1) When trying to add a trigger, the dropdown box for adding an account does not have acccounts.  It looks like realm or groupId information for SDReporter, not NexOSS accounts.
The dropdown url for customer account is /analyzer/cgi-bin/data/viewChoices.exe?setKey=SourceGroups&addChoices=Wild%20Card

2) The dropdown box to configure a device has a similar problem.
dropdown url = /analyzer/cgi-bin/data/viewChoices.exe?setKey=SourceDevices&addChoices=Wild%20Card

3) The dropdown box for breakout displays noting.
dropdown url = /analyzer/cgi-bin/data/viewFraudBreakoutCodes.exe?addChoices=Wild%20Card

**Comment by DmitryIsakbayev** [comment]
1) the url is for SDReporter.  The url for NexOSS should be `/cgi-bin/data/grpdata2.exe?type=customer&addChoices=Wild%20Card` for fraud or `/cgi-bin/data/grpdata2.exe?type=provider&addChoices=Wild%20Card` for QoS and Call Completion.  The difference is in the type of customer.

2) the url is for SDReporter.  The url for NexOSS should be `/cgi-bin/data/destinationsForProvider.exe?provider=PATHMASK&inludeSubnets=true&addChoices=Wild%20Card` for fraud or `/cgi-bin/data/destinationsForProvider.exe?provider=PATHMASK&inludeSubnets=false&addChoices=Wild%20Card` for QoS and Call Completion.   The difference is in including subnets in the list.  The API name suggests that it is only for providers, but it works for all kinds of customers.

3) There was a regression bug.

2 and 3 will be available in NexOSS 8.9.25.

I will test the changes after the lab is upgraded.

**Comment by JimDalton** [comment]
Upgrade all the dropdown urls for items 1 and 2 in trigger thresholds.  Testing using the Edit interface looks good.  Need to test with new build.

**Comment by JimDalton** [comment]
Typo in the dropdown for customer accounts trigger thresholds.  
The term Wild Card is spelled Wild Card**y**
![image](https://cloud.githubusercontent.com/assets/18315382/17023915/c3fe3b66-4f23-11e6-9005-4b17a4c5f062.png)

**Comment by DmitryIsakbayev** [comment]
The label is configured in the Url.  There is a trailing character is in the dropdownUrl for column 3. 
`/cgi-bin/data/grpdata2.exe?type=customer&addChoices=Wild%20Card�`

**Comment by JimDalton** [comment]
Thank you!  There is a trailing space for the dropdown url in the Excel file.  I have removed it for all pages.

**Comment by JimDalton** [comment]
Closing this issue and re-opening as multiple issues so it is simpler to understand
