### ISSUE TITLE
Text File Viewer

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#13]
#### Description of issue
In development.

**Comment by fenichelar** [comment]
Done.

**Comment by JimDalton** [comment]
Hello Dmitry and Alec,

I am trying to add two new NexOSS web pages that use the updated text viewer component that enables viewing and downloading a text file from NexOSS

For the page to download NexOSS Release notes, I think the paths.download url is:
/logs/cgi-bin/data/getLogFile.exe?dir=../../..&file=RELNOTES.txt   
What should the path be to view the file?

I also want to add a page that enables viewing and downloading the catalina.out log file.  I think the paths.download url is:
/logs/cgi-bin/data/getLogFile.exe?dir=../../../WebServer/logs&file=catalina.out
What is the path the view the file?
@fenichelar @DmitryIsakbayev

**Comment by DmitryIsakbayev** [comment]
The view and download paths are the same.
