### ISSUE TITLE
Cannot view CDR File

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#131]
Old Url: /analyzer/Fraud_Analytics_for_SIP_for_Basic_for_By_Customer_Device_for_Traffic_Pumping_for_Trigger_Report_for_Traffic_Report.htm

New URL: /Fraud-Control_SIP-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Report

Eaxample page
![image](https://cloud.githubusercontent.com/assets/18315382/16962922/e2029e4e-4dc1-11e6-89b9-19c193551a3b.png)

No Matching records.
![image](https://cloud.githubusercontent.com/assets/18315382/16962942/f87db776-4dc1-11e6-9a5d-7c1ecb6a417b.png)

**Comment by fenichelar** [comment]
@DmitryIsakbayev @JimDalton Can't reproduce because only archived reports exists. I need non-archived reports to access CDRs.

**Comment by fenichelar** [comment]
I believe this has been resolved but I need more CDRs to test.

**Comment by fenichelar** [comment]
@JimDalton Please test this and chart views when more CDRs are available.

**Comment by JimDalton** [comment]
Works as expected.
