### ISSUE TITLE
Cannot add Called Number Translation Rules

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#132]
Old Url:/trans/oss_nt_pre_routing_called_number_trans.htm
New Url: Number-Translation_Pre-Routing_Called-Number-Translation

Get the Error message "Something went wrong" when I try to add or change a number translation rule.
This feature use to work.  What happened?

**Comment by fenichelar** [comment]
Resolved. Please test.

**Comment by JimDalton** [comment]
Works as expected
