### ISSUE TITLE
Trigger Dropdown URLs for SDReporter

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#133]
The Excel config file for NexOSS will need the following dropdown url modifications in order to create a SDReporter configuration.

Fraud Trigger threshold pages:
Dropdown url for Source Realms = /analyzer/cgi-bin/data/viewChoices.exe?setKey=SourceGroups&addChoices=Wild%20Card

Dropdown url for source devices = /analyzer/cgi-bin/data/viewChoices.exe?setKey=SourceDevices&addChoices=Wild%20Card

Are the two urls above correct?

Trigger thresholds for Traffic Analyzer & QoS Pages
Dropdown url for Source Realms =?
Dropdown url for Source Devices = ?
Dropdown url for Destination Realms =?
Dropdown url for Destination Devices = ?

**Comment by DmitryIsakbayev** [comment]
>Are the two urls above correct?
Yes.

Trigger thresholds for Traffic Analyzer & QoS Pages
Dropdown url for Source Realms =?
`/analyzer/cgi-bin/data/viewChoices.exe?setKey=SourceGroups&addChoices=Wild%20Card`
Dropdown url for Source Devices = ?
`/analyzer/cgi-bin/data/viewChoices.exe?setKey=SourceDevices&addChoices=Wild%20Card`
Dropdown url for Destination Realms =?
`/analyzer/cgi-bin/data/viewChoices.exe?setKey=DestinationGroups&addChoices=Wild%20Card`
Dropdown url for Destination Devices = ?
`/analyzer/cgi-bin/data/viewChoices.exe?setKey=DestinationDevices&addChoices=Wild%20Card`

**Comment by JimDalton** [comment]
These Dropdown urls have been added to the SDReporter config.   Need to test.

**Comment by JimDalton** [comment]
Works as expected
