### ISSUE TITLE
Fraud Trigger Thresholds by GroupId

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#136]
Need Correct Dropdown Url for ServiceProviderId

In the old UI, the dropdown by ServiceProviderID includes MetTel
![image](https://cloud.githubusercontent.com/assets/18315382/17030738/eb5f00bc-4f3e-11e6-82a8-38abce804a95.png)

In the new UI, configured with the dropdown url for ServerProviderId =
/analyzer/cgi-bin/data/viewChoices.exe?setKey=SourceGroups&addChoices=Wild%20Card
Shows CallingGroupIds when compared to the old UI
![image](https://cloud.githubusercontent.com/assets/18315382/17030800/3a0bc416-4f3f-11e6-93e7-7474c15c6aa1.png)

**Comment by DmitryIsakbayev** [comment]
The setKey should be ServiceProviderIDs

/analyzer/cgi-bin/data/viewChoices.exe?setKey=ServiceProviderIDs&addChoices=Wild%20Card

**Comment by JimDalton** [comment]
Updated dropdown urls for triggers by ServiceProviderId.
Need to test

**Comment by JimDalton** [comment]
Need to test with MetTel Broadsoft CDRs on SDReporter on .53.

**Comment by JimDalton** [comment]
I tried to test this page using the UI with SDReporter on .53.  It caused both Chrome and Waterfax to crash.  The java console started on the Waterfox and I got a message that a script was unresponsive.
![image](https://cloud.githubusercontent.com/assets/18315382/18323831/605a622e-7507-11e6-8dc9-903b7348a67b.png)

![image](https://cloud.githubusercontent.com/assets/18315382/18323844/730ecc34-7507-11e6-80cc-9b2e4810919e.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton, does it work if you use .101 and switch the UI from NexOSS to SDReporter?

**Comment by JimDalton** [comment]
@DmitryIsakbayev   I cannot reproduce the problem when I switch .101 to SDReporter.

**Comment by JimDalton** [comment]
Works as expected
