### ISSUE TITLE
Fraud Trigger Thresholds by UserId

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#137]
Need dropdown url for calling UserId

**Comment by DmitryIsakbayev** [comment]
The setKey should be UserIDs

/analyzer/cgi-bin/data/viewChoices.exe?setKey=UserIDs&addChoices=Wild%20Card

**Comment by JimDalton** [comment]
Updated dropdown urls for trigger thresholds with UserId.
Need to test

**Comment by JimDalton** [comment]
Tried to test NexOSS UI2 on .53 running SDReporter with BroadWorks CDRs.  Did not work.  Need new UI for SDReporter.

**Comment by JimDalton** [comment]
Works as expected.
