### ISSUE TITLE
Call Completion Triggers Dropdown url for Providers

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#138]
Dropdown Url for Providers = /cgi-bin/data/grpdata2.exe?type=provider&addChoices=Wild%20Card
Does not provide a list of providers.  Is this correct?

**Comment by DmitryIsakbayev** [comment]
The Url is not correct.

Provider (customerType=.*Term.*) Accounts
/cgi-bin/data/grpdata2.exe?type=customer&customerType=.*Term.*&addChoices=Wild%20Card

Customer (customerType=.*Orig.*) Accounts
/cgi-bin/data/grpdata2.exe?type=customer&customerType=.*Orig.*&addChoices=Wild%20Card

All Accounts (any customer type):
/cgi-bin/data/grpdata2.exe?type=customer&addChoices=Wild%20Card

**Comment by fenichelar** [comment]
@JimDalton Please update the urls above.

**Comment by DmitryIsakbayev** [comment]
The URL for getting a list of providers (Terminating customers) is 
`/cgi-bin/data/grpdata2.exe?type=customer&customerType=.*Term.*&addChoices=Wild%20Card`

**Comment by JimDalton** [comment]
New provider account dropdown url works in edit interface.  Also changed dropdown url for customer account in Excel Config file.
Need to test after new build.

**Comment by JimDalton** [comment]
Fix type in Dropdown url for customers:
Tested in Edit Interface and it works.  Need to retest in new build.

**Comment by JimDalton** [comment]
Work as expected.
