### ISSUE TITLE
Add Validations

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#14]
#### Description of issue

Supported validators can be found here: https://github.com/DockYard/ember-validations

**Comment by DmitryIsakbayev** [comment]
Names for Accounts, Products and Devices:
Length between 1 and 50
Invalid chars  "`~!@#$%^&*()=+[{]}\\|;'\",<>/?\t\r\n"
A single space is allowed, but no consecutive spaces.
Reserved words (case insensitive) none, lcr-1, lcr-2, ..., lcr-10

**Comment by JimDalton** [comment]
Compile a list of validation types and then give each validation type a name.
Give the list of validations and type names to Alec, who will program into Ember

**Comment by JimDalton** [comment]
Here are a proposed set of Validations:

Validation Name = name
Length between 1 and 50
Invalid chars "`~!@#$%^&*()=+[{]}\|;'\",<>/?\t\r\n"
A single space is allowed, but no consecutive spaces.
Reserved words (case insensitive) none, lcr-1, lcr-2, ..., lcr-10

The follow validation names require only integer values with in a certain range
integer_1-5
integer_1-10
integer_1-20
integer_1-100
integer_1-10000

For example integer_1-5 requires an integer value from 1 to 5.

**Comment by JimDalton** [comment]
Alec, please add one more validation: integer_0-100

**Comment by fenichelar** [comment]
@JimDalton, integer_0-100 already exists. Would you like 1000?

**Comment by fenichelar** [comment]
Need to resolve regex issue.

**Comment by fenichelar** [comment]
Regex issue resolved but validation rules are not being applied. Need to investigate problem.

**Comment by fenichelar** [comment]
Issue resolved!!!!

**Comment by fenichelar** [comment]
@JimDalton `IPaddress` validation added

**Comment by DmitryIsakbayev** [comment]
Device Mandatory and Preferred Attributes
[a-zA-Z0-9\-_ ]{0,25}

Destination Attribute - similar to the one for devices, but includes ',' and should probably be longer
[a-zA-Z0-9,\-_ ]{0,50}

**Comment by DmitryIsakbayev** [comment]
Account BillingCycle and BillingStartDate are mandatory.

**Comment by JimDalton** [comment]
Added validations=required to all Traffic Analyzer and Fraud Trigger Thresholds for Customer Account, Customer Device and Calling Numbers
Added validations=required to all Traffic Analyzer and Fraud Trigger Thresholds for Breakouts and set default = Wild Card

**Comment by JimDalton** [comment]
Added validations - Note_100 to Number Translation Notes and to Breakout Codes Comments.  Works as expected, but does not block bad characters such as \ or /.  Need to add bad character checking.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Please provide a list of bad characters that should not be allowed for any fields.

**Comment by DmitryIsakbayev** [comment]
Invalid chars "`~!@#$%^&*()=+[{]}\|;'\",<>/?\t\r\n"

**Comment by fenichelar** [comment]
@DmitryIsakbayev Don't we use the `#` symbol is certain places? What fields should those characters not be allowed for?

**Comment by DmitryIsakbayev** [comment]
@fenichelar you are correct.  We allow `#*+` in phone numbers.  Let's remove them from invalid chars.

**Comment by fenichelar** [comment]
Done. Please let me know any additional validations needed.

**Comment by DmitryIsakbayev** [comment]
@fenichelar we need a validation for subnets like

0.0.0.0/1
1.0.0.0/31
1.2.3.4/32

**Comment by JimDalton** [comment]
Closing this issue.  Known validation requirements have been implemented.
