### ISSUE TITLE
Add support for changing application on the fly

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#141]

**Comment by fenichelar** [comment]
Done. Please test and confirm it works as expected. The buttons are on the edit interface. The NexOSS-FC button won't work until a `NexOSS-FC.txt` file is created.

**Comment by JimDalton** [comment]
Alec, I do not see a NexOSS-FC button.   What should I test?
![image](https://cloud.githubusercontent.com/assets/18315382/17438052/fcb09270-5aee-11e6-8021-8d8deab31649.png)

**Comment by fenichelar** [comment]
@JimDalton. Just a heads up, if you type `@` and then start typing my name you can "tag" me. This will ensure I get a notification about the message on items that I am not assigned to.

The button is on the "Edit Interface". This page is "Edit This Page". Please let me know if you have better names for these.
You do not need to create a `NexOSS-FC.txt` file until you are ready. Just be aware that you should not click the button until you do as it will cause problems. The buttons can be found on the bottom right of the "Edit Interface":

**Comment by JimDalton** [comment]
@fenichelar.  I do not see any buttons at the bottom right of the Edit Interface.  
![image](https://cloud.githubusercontent.com/assets/18315382/17527080/efb7d352-5e37-11e6-8ae3-8caaf42c723b.png)

**Comment by fenichelar** [comment]
@JimDalton Select "Edit Interface" not "Edit This Page" from the "Admin" menu.

**Comment by fenichelar** [comment]
Tested.
