### ISSUE TITLE
Graphing from oldest to most recent tiem

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#143]
#### Description of issue
Alec, by default, tables are sorted so the most recent date is at the top.  This is nice for users so they do not have to scroll down to see the most recent data.

However, it is an issue for graphs which display data with the oldest data on the left and the most recent data on the right.  This will be confusing for users.

Is it possible to keep the table sorting unchanged (most recent data on top) and change graphs to display time series data with the oldest on the left of the graph and the most recent data on the right?

**Comment by fenichelar** [comment]
Done. Please test tomorrow.

**Comment by JimDalton** [comment]
Works as expected.
