### ISSUE TITLE
Add Subnet IP range to the table view of Subnets

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#146]
The legacy UI Subnet page displays the range of IP addresses in a subnet.  This would be a user friendly addition to the new UI.  

This is a low priority enhancement.  I expect this would require a change to NexOSS.  We can assign responsibility for this enhancement when we are ready to work on this feature.

**Comment by fenichelar** [comment]
@JimDalton Potential solution implemented.

**Comment by fenichelar** [comment]
Resolved. Please test.

**Comment by JimDalton** [comment]
Works as expected.
