### ISSUE TITLE
Global handlebars issue

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#148]
No table view of Route Provisioning / Least Cost / Routes / Rates

![image](https://cloud.githubusercontent.com/assets/18315382/17412707/19859628-5a4c-11e6-8878-f96ffb4b306c.png)

**Comment by fenichelar** [comment]
@JimDalton This issue is causing problems on many pages. Fixing now.

**Comment by fenichelar** [comment]
Resolved. Please test on .93.

**Comment by JimDalton** [comment]
Fixed.
