### ISSUE TITLE
Dropdown URL for Account names includes all data about accounts, not just names.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#15]
#### Page Title
Devices and Subnets Pages

#### Legacy URL
http://172.16.4.32:7080/oss_rp_devices.htm
http://172.16.4.32:7080/oss_rp_subnets.htm

#### New URL
http://172.16.4.93:9080/ui2/Accounts/Devices/All
http://172.16.4.93:9080/ui2/Accounts/Subnets/All
However, staring on 2016-05-06 the "/All" of these urls will be removed.

#### Description of issue
The dropdown url property for the Accounts column returns all data about Account.  The dropdown url should only list the account names.  The dropdown url is /cgi-bin/data/grpdata2.exe?type=customer

Should this be addressed on Ember or NexOSS?

Screenshot of modal to add a device with dropdown for Account Names:
![image](https://cloud.githubusercontent.com/assets/18315382/15052394/76b6d19a-12cb-11e6-999d-fc134c260ca5.png)

**Comment by fenichelar** [comment]
Done.
