### ISSUE TITLE
Add support for multiple types on columns with multiple titles

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#152]
#### Page Path
All reports

#### Description of Issue
See title

**Comment by JimDalton** [comment]
Alec, for the Product Full View Page:
titles = ["Home","Product","Breakout","Provider","Destination","Device"]
Should types be the same kind of array?  For example:
["text","text","telephone","text","text","text"]

**Comment by fenichelar** [comment]
@JimDalton Yes

**Comment by fenichelar** [comment]
Done. Needs testing.

**Comment by JimDalton** [comment]
Work as expected.
