### ISSUE TITLE
Product Full View Performamce

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#153]
#### Description of Issue
The Product Full View display in the new UI is noticeably slower than the old UI.  It has a negative impact on demos.  It appears that perhaps more than 1/2 of the delay is due to a slow NexOSS response.

Need to optimize for faster Product Full View display..

**Comment by DmitryIsakbayev** [comment]
Optimizations included in v.5.9.30.

**Comment by JimDalton** [comment]
Viewing the Full View is faster.  However, the old UI is still noticeably faster.  We may need to revisit optimizing the full view.
