### ISSUE TITLE
Dashboard \ Monitors \ Resources bad links to details pages

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#155]
#### Page Path
Dashboard \ Monitors \ Resources

#### Description of Issue
All the Go To Page links for Resource - Java Memory, go to the log file for those java applications.  Instead, the Go To Page link should go to the page that monitors the java usage of that application.

For example, the "Go to Page" for CDR Collection links to: /Dashboard_Logs_CDR%20Processing_CDR-Collection.  THis is a log file.
It should link to /Dashboard_Resources_Applications_CDR-Collection which is a table of memory utilization.

![image](https://cloud.githubusercontent.com/assets/18315382/17439611/e57a32d4-5af6-11e6-93cf-d6701b4b99a7.png)

**Comment by fenichelar** [comment]
@DmitryIsakbayev 

`http://localhost:1337/api/keys?token=`**TOKEN**
or
`http://localhost:1337/api/keys?username=`**USERNAME**`&password=`**PASSWORD**

will give you the mapping of pages on the old interface to the new interface.

**Comment by DmitryIsakbayev** [comment]
Updated links for Dashboard / Resources (ResourceFileURL in etc/FileMon.etc) to point to resource utilization instead of log pages.  NexOSS v 5.9.30

**Comment by JimDalton** [comment]
Works as expected
