### ISSUE TITLE
Status column did not sort as expected in Trigger Minitor page.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#156]
#### Page Path
Dashboard \ Monitors \ Triggers \ Fraud

#### Description of Issue
Rows with Red status are at the bottom of the page.  They should be at the top of the table.  Also, is the Traffic Pumping trigger by CDRs yellow or Orange?  
![image](https://cloud.githubusercontent.com/assets/18315382/17528682/60c0cc1a-5e3e-11e6-8b74-4ee8944aed43.png)

The Traffic Analyzer Triggers page has the same issue.
![image](https://cloud.githubusercontent.com/assets/18315382/17528875/179ff8c0-5e3f-11e6-8b0c-a45c202e4df3.png)

**Comment by fenichelar** [comment]
Resolved. Please test tomorrow.

**Comment by JimDalton** [comment]
Sorts status as expected.
![image](https://cloud.githubusercontent.com/assets/18315382/17637362/1562a55c-60b1-11e6-98ad-7c925f8e2ae0.png)
