### ISSUE TITLE
Old and New UI for CDRs Monitor Page show different status data.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#157]
#### Page Path
Dashboard \ Monitors \ CDRs

#### Description of Issue
The CDRs Monitor pages for the Old and New UI do not match.  The status for CDRs in the WORK directory should be red, but the new UI says green..
![image](https://cloud.githubusercontent.com/assets/18315382/17528954/76023c2a-5e3f-11e6-81f7-5dc78fea0d46.png)

![image](https://cloud.githubusercontent.com/assets/18315382/17529026/b9f74222-5e3f-11e6-985a-9c2da481d00a.png)

**Comment by DmitryIsakbayev** [comment]
The  unix/utils/count_cdr_files.py script generated status color based on the age of the last file instead of the oldest file.  Will include the fix in NexOSS 8.9.30

**Comment by JimDalton** [comment]
Works as expected
