### ISSUE TITLE
Remove Default button from modal for Add/Copy/Update

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#16]
#### Description of issue
Is there a use case for the Default button on the Add/Copy/Update modal?  If not, it should be removed.
![image](https://cloud.githubusercontent.com/assets/18315382/15092965/29432a80-1447-11e6-8794-c9ae0e51320d.png)

**Comment by fenichelar** [comment]
This button was originally named "Clear". It sets all of the fields to their default value.
