### ISSUE TITLE
Time lag updating Process Monitor causes user confusion

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#161]
#### Page Path
Dashboard \ Monitors \ Processes

#### Description of Issue
When updating a row on the Process Monitor page, the page does not change when the change is submitted.  If the user refreshes the page, the change is still not updated on the page until after approximately 1 minute.  This in confusing for users, who think the update failed and will repeatedly retry the update.  In addition, sometime an update submission results in an error, but I cannot reliable reproduce this error.
![image](https://cloud.githubusercontent.com/assets/18315382/17618303/d83d2f9e-604c-11e6-88fb-defe67536519.png)

**Comment by JimDalton** [comment]
The solution we discussed was for the client to post a green success message with the following text.
"The change has been successfully submitted to the server and will take effect in approximately 60 seconds.  The change will not appear on this page until the change takes effect and the page is refreshed."

**Comment by JimDalton** [comment]
Added successMessage to Excel config file.

**Comment by fenichelar** [comment]
Done. Please test.

**Comment by JimDalton** [comment]
Works as expected.
