### ISSUE TITLE
Device IP address is Mandatory and should be required in add or update modal

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#162]
#### Page Path
Devices and Subnet's page

#### Description of Issue
IP address is a mandatory field.  When the user submits a modal to add or change a device or subnet that does not have an IP address, the user should get a prompt that the IP address is mandatory.

**Comment by fenichelar** [comment]
This is handled by validations.

**Comment by fenichelar** [comment]
`IPaddress` validation added
