### ISSUE TITLE
Improve Error Messages

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#163]
When an error is received by Ember from NexOSS, the user should get some useful information that explains why the error occurred.

**Comment by fenichelar** [comment]
@DmitryIsakbayev We need to discuss a consistent format for error messages to be sent using.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Error messages are now passed through.

**Comment by fenichelar** [comment]
@JimDalton Please intentionally do things to cause errors and confirm error messages are correct and helpful.

**Comment by DmitryIsakbayev** [comment]
@fenichelar On error, in addition to sending error description as HTTP Status Description, will send it as "X-Error-Description" HTTP header.  Should be ready for testing after the lab is upgraded to 8.16.2
