### ISSUE TITLE
Modify table search to exclude columns that are buttons (LOW PRIORITY)

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#164]
#### Description of Issue
This is low priority.
Example: Want to find all the breakouts for AL (Alabama).  Cannot use the column search for breakouts because it is type=telephone and search is "starts with) which will never find a breakout such as 1205 AL.  However, table search for AL returns all columns because all the links to CDR details include AL  Need to exclude CDR details column from table search..

**Comment by fenichelar** [comment]
Resolved by using awk instead of grep. Only columns that are not links/buttons/etc are searched.

**Comment by fenichelar** [comment]
@JimDalton What needs to be done?
