### ISSUE TITLE
iframe size

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#165]
#### Description of Issue
@fenichelar   Can you make the iframe window larger?  I see a lot of blank space when I view an iframe.
![image](https://cloud.githubusercontent.com/assets/18315382/17634541/240206b2-60a1-11e6-8244-f47912cce1b7.png)

**Comment by fenichelar** [comment]
Size increased. Please test tomorrow.

**Comment by JimDalton** [comment]
Much better
