### ISSUE TITLE
LCR Product Full View does not display

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#166]
#### Description of Issue
Drilling down into the LCR full view shows no providers for ##1201200.  The legacy view shows 5 providers for breakout ##1201200.
![image](https://cloud.githubusercontent.com/assets/18315382/17635337/c1e16e06-60a4-11e6-92a2-30683b5f6608.png)

Legacy View
![image](https://cloud.githubusercontent.com/assets/18315382/17635372/eb98b6a0-60a4-11e6-824f-deb6a277ff7b.png)

**Comment by DmitryIsakbayev** [comment]
@fenichelar the key for product "LD" breakout "##1201200" is "Products%3BLD%3B%23%231201200" (or "Products;LD;##1202200" after URL decoding the value), but the server does not get the full key.
It only receives - /cgi-bin/data/orig-routedataFullView2?forKey=Products;LD;
## and everything after it is dropped.

**Comment by fenichelar** [comment]
Resolved. The url's were decoded by Sails automatically so I re-encoded them before using curl.

**Comment by JimDalton** [comment]
Works  as expected.
