### ISSUE TITLE
Port Prepaid Billing page to new UI

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#167]
#### Page Path in Legacy UI

/logs/oss_report_credit_control.htm
#### Description of Issue

Need to create table in New UI of Prepaid Accounts.  My need to add a Status column with values of "Warning" or "Blocked"
![image](https://cloud.githubusercontent.com/assets/18315382/17637742/9efa4340-60b3-11e6-8cfd-c6e50bfb86a4.png)

**Comment by DmitryIsakbayev** [comment]
@fenichelar, we need an option to flag Inserted and Created columns as serverGenerated.  Something similar to "canNotEdit" but it will apply for the Add dialog.

**Comment by DmitryIsakbayev** [comment]
@fenichelar,

Columns Created and Updated are generated  by the server.  They should be visible on the page, but not in the Add or Update modals.

Columns Charge and Payment are required for the update operation.  They should not be visible on the page and in the Add modal, but should be visible in the Update modal.

**Comment by fenichelar** [comment]
`canNotAdd` and `canNotEdit` are now both available.

**Comment by DmitryIsakbayev** [comment]
Marked Payment, Charge, Crated and Inserted columns as `canNotEdit`

**Comment by DmitryIsakbayev** [comment]
Please test

**Comment by JimDalton** [comment]
/ui/Billing_Prepaid-Billing_Warning-Accounts
Cannot update Prepaid Billing Account.  No Response From Server.
![image](https://cloud.githubusercontent.com/assets/18315382/20448735/830518b6-adb3-11e6-8859-4184c9a5919d.png)

**Comment by JimDalton** [comment]
Working as expected.
