### ISSUE TITLE
Port Prepaid Billing E-mail Config to new UI

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#168]
#### Page Path in Legacy UI
/analyzer/oss_report_credit_control_config_email.htm

#### Description of Issue
![image](https://cloud.githubusercontent.com/assets/18315382/17637805/1a42bf6e-60b4-11e6-9cb6-5aa840b88b0c.png)

**Comment by DmitryIsakbayev** [comment]
Looks like this page has already been ported.
