### ISSUE TITLE
Port pages for Credit Control Broadsoft Configuration by Hour and by Day 

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#169]
#### Page Path - Pages on Legacy UI
Configuration for hourly reports: /billing/oss_billing_broadsoft_configuration_4.htm
Configuration for daily reports: /billing/oss_billing_broadsoft_configuration_5.htm

#### Description of Issue
![image](https://cloud.githubusercontent.com/assets/18315382/17637978/2b36074e-60b5-11e6-85c5-234c902b981b.png)

**Comment by DmitryIsakbayev** [comment]
Ported.
