### ISSUE TITLE
Added Device Names must be unique

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#17]
#### Page Title
Devices

#### Description of issue
Device names must be unique.  When a Device Name is added a validation should be made to ensure the Device name is unique.  The Add Device modal provides list of previously added devices names when the Device Name box in the modal is selected. The user should not be given the option to select a previously added device name.  For example, in the screenshot, below, the previously added device name "Ameriteck" is presented as an option the user can select.  This should not happen.
![image](https://cloud.githubusercontent.com/assets/18315382/15093137/242722c2-144c-11e6-9385-c24a92ef78dc.png)

**Comment by fenichelar** [comment]
The interface is displaying what it is receiving from NexOSS. I am not following. Is this supposed to be a dropdown?

**Comment by JimDalton** [comment]
No, the text box for device name should not be a dropdown.  The issue I was trying to describe is hard to see in the screenshot, but you may notice that a device called Ameriteck is displayed just below the device name box.  This should not appear when the device name text area is selected.  This is probably only viewable from my browser since I change a device name to Ameritck.  It will be easier to  discuss in the office when I can show what I am trying to describe,

**Comment by fenichelar** [comment]
I think I know what this is. We can confirm Monday but I am not sure if I will be able to do much. If it is what I suspect, your browser is remembering what you typed previously. Your browser should do this on all of the forms as long as they submit successfully. I am not sure if I will be able to force the browser to stop remembering what was previously typed.
