### ISSUE TITLE
Port Billing Invoices Pages

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#170]
#### Page Path on Legacy UI

Customer Account Invoices: /billing/oss_billing_invoice_3.htm
Provider Account Invoices: /billing/oss_billing_invoice_4.htm
#### Description of Issue - View of Legacy Customer Account Invoices page

![image](https://cloud.githubusercontent.com/assets/18315382/17638172/51537230-60b6-11e6-97b4-243cffc6662b.png)

**Comment by DmitryIsakbayev** [comment]
Ported 
Billing_Invoices_By-Customer_By-Billing-Period 
and 
Billing_Invoices_By-Provider_By-Billing-Period

@fenichelar, the pages should not presort the output.  Is it possible to disable presorting by the 1st column?

**Comment by DmitryIsakbayev** [comment]
Started porting 
Billing_Invoices_By-Customer_Before-Invoice-Date
and
Billing_Invoices_By-Provider_Before-Invoice-Date

@fenichelar, the paths.list returns a list of folderName/fileName.  For Example:
`
Logix/InvoiceDate_2016-05-09_Created_2016-08-30_Logix_Invoice-2145_Amount-0.00.Customer-Invoice
Logix/InvoiceDate_2016-05-10_Created_2016-08-30_Logix_Invoice-2147_Amount-0.00.Customer-Invoice
Logix/InvoiceDate_2016-05-11_Created_2016-08-30_Logix_Invoice-2149_Amount-0.00.Customer-Invoice
Logix/InvoiceDate_2016-05-12_Created_2016-08-30_Logix_Invoice-2151_Amount-0.00.Customer-Invoice
Logix/InvoiceDate_2016-05-13_Created_2016-08-30_Logix_Invoice-2153_Amount-0.00.Customer-Invoice
`
It looks like the paths.view action does not like the /.  The PATHMASK only gets the folder part.

**Comment by fenichelar** [comment]
@DmitryIsakbayev I have encoded the `/` in view urls.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Do you want to disable sorting entirely or just presort?

**Comment by DmitryIsakbayev** [comment]
@fenichelar, definitely presort.  I am not sure if it makes to sort on this page.  @JimDalton, what do you think?

**Comment by JimDalton** [comment]
@DmitryIsakbayev   I do not have clear enough understanding of the issue to offer a useful opinion.  Is the page sorted on the old UI?  If not, then no need to sort.  I suggest we move forward with what is easiest to implement and change if needed after using the page.

**Comment by fenichelar** [comment]
`disablePresort` property created. Set true to disable presort.

**Comment by JimDalton** [comment]
@DmitryIsakbayev   Need better error message for Customer Invoices page.  I tried to view the page and got on a 500 message.
/ui/Billing_Invoices_By-Customer_Before-Invoice-Date
![image](https://cloud.githubusercontent.com/assets/18315382/18797377/b282f1d8-819b-11e6-908d-c79cfe83b377.png)

**Comment by DmitryIsakbayev** [comment]
Disabled presort, ignore the 1st column and the 1st line for

config/pages/NexOSS/08-Billing/05-Invoices/By-Customer/01-Before-Invoice-Date.json
config/pages/NexOSS/08-Billing/05-Invoices/By-Provider/01-Before-Invoice-Date.json

**Comment by DmitryIsakbayev** [comment]
Disabled presort for

config/pages/NexOSS/08-Billing/05-Invoices/By-Customer/02-By-Billing-Period.json
config/pages/NexOSS/08-Billing/05-Invoices/By-Provider/02-By-Billing-Period.json

**Comment by DmitryIsakbayev** [comment]
Please test.

**Comment by JimDalton** [comment]
Looks good.
