### ISSUE TITLE
Port Billing Re-Rate Pages

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#171]
#### Page Paths in Legacy UI

Add Request                         /billing/oss_billing_add_rerate_request.htm
View Pending Requests        /billing/oss_billing_pending_rerate_q.htm
View Processed Requests     /billing/oss_billing_processed_rerate_q.htm

**Comment by DmitryIsakbayev** [comment]
@fenichelar, the Add Re-Rate Request page requires an action similar to the paths.exportRatePlan and date select input in the format YYYY-MM-DD.  The server expects the date value in the CallStartTime variable.

**Comment by fenichelar** [comment]
Should this be called "Request To Rerate"?

**Comment by fenichelar** [comment]
@DmitryIsakbayev Is the currently selected row also attached or just the date?

**Comment by DmitryIsakbayev** [comment]
@fenichelar both the row and the date please.

**Comment by fenichelar** [comment]
What is the date? I need to config the field title.

**Comment by DmitryIsakbayev** [comment]
The current page does not have a title for the field.  I suppose it could be something like "Since call start time"
![screenshot](https://cloud.githubusercontent.com/assets/14879700/18921612/828a4018-8573-11e6-9c24-35745c07b8f5.png)

**Comment by fenichelar** [comment]
@DmitryIsakbayev Please test.

**Comment by DmitryIsakbayev** [comment]
@fenichelar looks like the request does not make it to NexOSS.  Sails logs

{"IP":"172.16.5.4","Method":"POST","Path":"/api/pages/Billing_Re-Rating_Add-Request/rerate","Query":{},"Username":"ossadmin","Token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9zc2FkbWluIiwiaWF0IjoxNDc2Mzc4Njk2LCJleHAiOjE0NzYzODA0OTYsImlzcyI6Ik5leE9TUyJ9.HLyOyU9SPDAwP9JMddBrRwh_caMRJzOmrsAc-Lrh4-A","Body":{"0":"true","Account":"Ameritech","Type":"Term","Rate_Plan_Name":"Ameritech_Inter-State","Effective_Date":"2016-02-04 00:00:00","Provisioned_On":"2016-02-12 11:11:42.531","Rate_Plan_Id":"26","id":"62432eb43e52692600dfc579f716f57390b23233","CallStartTime":"2016-10-13"},"Response":404,"Timestamp":"2016-10-13 13:17:40"}

**Comment by fenichelar** [comment]
@DmitryIsakbayev Caused by Ember making a request to Sails at the wrong URL because I mistyped it. Resolved.

**Comment by DmitryIsakbayev** [comment]
Looks good.
