### ISSUE TITLE
Menu extends beyond screen view

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#173]
#### Page Path
Dashboard \ Resources \ Applications \ More

#### Description of Issue
The menu extends beyond the viewable screen.  There is no way to scroll down to select menu items off the viewable screen.
![image](https://cloud.githubusercontent.com/assets/18315382/17664740/3df1f5ee-62c4-11e6-9884-0ec2c6bbe15a.png)

**Comment by fenichelar** [comment]
@JimDalton  This unfortunately will not be very easy to fix. Please move "More" to the top for now and we will circle back and address the problem.

**Comment by JimDalton** [comment]
Not a priority.  I will change the menu.
