### ISSUE TITLE
New report by All User Agents / Customer / Device / Time

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#174]
Please use the /Fraud-Control_SIP-Analytics-Basic_Blacklisted-User-Agents_By-Customer_Trigger-Report report as a template.  The only differences are the fileMask in the paths.list and contextName in the paths.view.  Here are the values specific to the report

paths.list
`/analyzer/cgi-bin/data/listReportFiles.exe?dir=..%2F..%2F..%2FREPORTS&lastFileFirst=false&fileMask=.*-FQ-AllUserAgent-Source-Source-Time%28.report%7C.report.gz%29&sortByDayNameOfWeek=false&sortOrder=dsc`

paths.view
`/applet/cgi-bin/data/viewReport.exe?appPrefix=Analyzer&appSubPrefix=&contextName=OSS-AllUserAgents-Customer-FQB-Report&contextResources=tree-report-viewer&includeHeaders=false&forReportFileName=PATHMASK&forKey=FILTERMASK&displayMinusOneAs=`

**Comment by DmitryIsakbayev** [comment]
In order to add the new report to the /Fraud-Control_SIP-Analytics-Basic_Configuration_Reports page,
add a new column where the api equals to "FraudQueryAllUserAgentsBySourceSource"

**Comment by JimDalton** [comment]
Changes added to config.  Need to test.

**Comment by JimDalton** [comment]
The Report looks good.  However, there is no fraud score calculated.  The fraud score is always 0.  Can it be calculated for this report?
![image](https://cloud.githubusercontent.com/assets/18315382/17706696/0e1043ca-63ab-11e6-9fb6-840ca734ead3.png)

**Comment by DmitryIsakbayev** [comment]
Yes.  User Agent reports were not configured to use Fraud Scores.  I will include the fix in the next release.

**Comment by JimDalton** [comment]
Works as expected
