### ISSUE TITLE
No Billing Data in billingCDR

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#177]
#### Page Path
http://172.16.4.93:9080/special/billingCDR/Hourly%20Credit%20Control%20Report%20by%20Customer/%20%2F%20Home%20%2F%20Day%202016-08-17%20EDT(-0400)%20%2F%20Customer-17/2016-08-17-20160812165440-BillingBy-Customer-Hour.report.details%252FDay%2B2016-08-17%2BEDT%2528-0400%2529%252FCustomer-17%252FHour%2B00

#### Description of Issue
Billing CDR does not include any billing data.  Billing data, such as Orig Fee and Term Fee is populated as expected in Credit Control report, but not in the billing CDR file.
![image](https://cloud.githubusercontent.com/assets/18315382/17736353/5d3d003c-6455-11e6-80b6-80bac6dfcc87.png)

**Comment by DmitryIsakbayev** [comment]
I was wrong in describing the details.txt format for billing records.  Here is the actual order of columns.  Columns "RelatedCallIdReason" and below are placeholders for columns that are not yet implemented in the database.
Date Time Stamp
Reporting Device Name
Routing Group
Source Device Name
Source Group
Destination Device Name
Destination Group
Calling Number
Called Number
CDR Type
Callid
Transaction Id
Duration
Count
Total
TC Code
Call Start Time
Called Number Reported
Called Number After In Prefix
Called Number After Pre Routing
Called Number After Post Routing
Calling Number Reported
Calling Number After Pre Routing
Call End Time
Call Alert Time
Post Dial Delay
Source Device Network Id
Destination Device Network Id
Signaling IP
Call Connect Time
Called Number After Routing Number Manipulation
Reporting Device Short Name
Source Device Short Name
Destination Device Short Name
Called Number After LNP
Custom Info 1
Custom Info 2
Custom Info 3
Custom Info 4
Custom Info 5
Source-to-Proxy-RTP-Packets-Lost
Destination-to-Proxy-RTP-Packets-Lost
Source-to-Proxy-RTP-Jitter-Avg
Destination-to-Proxy-RTP-Jitter-Avg
Source-to-Proxy-RTP-Octets
Destination-to-Proxy-RTP-Octets
Source-to-Proxy-RTP-Packets-Received
Destination-to-Proxy-RTP-Packets-Received
Source-to-Destination-RTCP-Packets-Lost
Destination-to-Source-RTCP-Packets-Lost
Source-to-Destination-RTCP-Jitter-Avg
Destination-to-Source-RTCP-Jitter-Avg
Proxy-to-Destination-RTCP-Two-way-Delay-Avg
Proxy-to-Source-RTCP-Two-way-Delay-Avg
Destination-to-Proxy-RFactor
Source-to-Proxy-RFactor
Destination-to-Proxy-MOS
Source-to-Proxy-MOS
Called Number After Out Prefix
Calling Number After Post Routing
Calling Number After Out Prefix
From Reported Calling Number
Diversion Reported Calling Number
NPDI
Via Source Device Name
Via Source Device Short Name
Via Source Device Group
Diversion Source Device Name
Diversion Source Device Short Name
Diversion Source Device Group
Ported Region Name
Wire Device Name
Wire Device Short Name
Wire Device Group
Reported NPDI
Reported Routing Number
Queried NPDI
Queried Routing Number
Source-to-Proxy-RTP-Jitter-Max
Destination-to-Proxy-RTP-Jitter-Max
Source-to-Destination-RTCP-Jitter-Max
Destination-to-Source-RTCP-Jitter-Max
Proxy-to-Destination-RTCP-Two-way-Delay-Max
Proxy-to-Source-RTCP-Two-way-Delay-Max
Source Signaling Protocol
Source Codec
Destination Codec
SIP Status
Destination Signaling Protocol
Signaling Protocol
Source Realm
Destination Realm
Source SessionId
Destination SessionId
Correlation SessionId
Asserted Id
Remote Party Id
Role Info State
Role Info Format
Role Info Vendor Info
Charge Info
Breakout Code Label for Traffic Analyzer & QoS Trigger Report
Processing Time in Milliseconds
Processing Time for NPD in Milliseconds
Processing in Parallel Count
CDR queue size
Call Transfer Id
Call Transfer Status
Breakout Code Label for Traffic Analyzer & QoS Report
TC Code Description
Calling Party User Name
Calling Party User Id
Calling Party User Group
Called Party User Name
Called Party User Id
Called Party User Group
Local SessionId
Remote SessionId
Release Source
Top Provider
Breakout Code Label for Fraud Trigger Report
Call Completion Status
Called Number After Post-Routing Translation By Provider
Service Provider Id
Network Translated CalledNumber
Successful Call
O_RatePlanId
O_RatePlanDataId
O_ExchangeRateId
O_InvoiceId
O_BillingDuration
O_Currency
O_BillingAmountCustCurr
O_BillingAmountFuncCurr
T_RatePlanId
T_RatePlanDataId
T_ExchangeRateId
T_InvoiceId
T_BillingDuration
T_Currency
T_BillingAmountCustCurr
T_BillingAmountFuncCurr
GrossProfitFuncCurr
ProfitPerMinuteFuncCurr
ProfitMargin
RelatedCallIdReason
SystemId
Source_Video_Codec
Destination_Video_Codec
Source_to_Reporting_Device_RTP_Video_Octets
Source_to_Reporting_Device_RTP_Video_Packets
Destination_to_Reporting_Device_RTP_Video_Octets
Destination_to_Reporting_Device_RTP_Video_Packets
Source_to_Reporting_Device_RTP_Video_Packets_Lost
Source_to_Reporting_Device_RTP_Video_Jitter_Avg
Source_to_Reporting_Device_RTP_Video_Jitter_Max
Destination_to_Reporting_Device_RTP_Video_Packets_Lost
Destination_to_Reporting_Device_RTP_Video_Jitter_Avg
Destination_to_Reporting_Device_RTP_Video_Jitter_Max
Destination_to_Source_RTCP_Video_Packets_Lost
Destination_to_Source_RTCP_Video_Jitter_Avg
Source_RTCP_Video_Two_way_Delay_Avg
Destination_to_Source_RTCP_Video_Jitter_Max
Source_RTCP_Video_Two_way_Delay_Max
Source_to_Destination_RTCP_Video_Packets_Lost
Source_to_Destination_RTCP_Video_Jitter_Avg
Destination_RTCP_Video_Two_way_Delay_Avg
Source_to_Destination_RTCP_Video_Jitter_Max
Destination_RTCP_Video_Two_way_Delay_Max
CDRProxyHost
CDRProxyFolder
CDRProxySubfolder
FromDisplayName
UserAgent
SourceDeviceGeoId
SourceDeviceCountry
SourceDeviceState
SourceDeviceCity
DestinationDeviceGeoId
DestinationDeviceCountry
DestinationDeviceState
DestinationDeviceCity
SourceAudioAddress
SourceVideoAddress
DestinationAudioAddress
DestinationVideoAddress
ProxyIngressAddress
ProxyEgressAddress
ProviderPDD
JIP
CNAM
CNAM_best_name
CNAM_city
CNAM_state
CNAM_line_type
Reputation_level
Reputation_score
Reputation_type
Reputation_category
Reputation_volume_score
Reputation_report_count

**Comment by JimDalton** [comment]
A new billingCDR file has been configured in the Excel spreadsheet  using the order for CDRs in the list above.

Need to test.

A second file, billingCDR2, is ready to be used with the new UI when the following fields are added to the billingCDR,
P-Asserted-Id_Display_Name
Call Type
Call Category
Network Type
SPID
AltSPID
Reported SPID
Reported AltSPID
Queried SPID
Queried AltSPID
SourceDeviceSwitchId
DestinationDeviceSwitchId

**Comment by JimDalton** [comment]
Works as expected
