### ISSUE TITLE
Add support for multiple levels of tabs

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#178]
See title.

**Comment by JimDalton** [comment]
I added tabs to the following pages:
Traffic Analyzer - Configuration - Reports
QoS - Configuration - Reports 
The 3rd sun tab is visible but not active on the QoS - Configuration - Reports page for both SDReporter and NexOSS
All other sub tabs, on all pages, work as expected.
![image](https://cloud.githubusercontent.com/assets/18315382/17864916/02872aba-686e-11e6-85a7-ea45b0cededf.png)

**Comment by fenichelar** [comment]
Caused by tab titles with multiple spaces. Issue resolved. Please test tomorrow.

**Comment by JimDalton** [comment]
Tried to test, but Something Went Wrong with both Traffic Analyzer and QoS Reports
![image](https://cloud.githubusercontent.com/assets/18315382/17906506/a0752204-6945-11e6-947f-59ea4ca7441b.png)

**Comment by DmitryIsakbayev** [comment]
OSS on .32 is down for upgrade.

**Comment by fenichelar** [comment]
@JimDalton This is going to be quite complicated from a config standpoint. Is this a feature you still wish to have?

**Comment by JimDalton** [comment]
I think the current functionality is good - thank you.
