### ISSUE TITLE
Error updating bit mask on Subnets page

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#18]
#### Page Title
Subnets

#### Legacy URL
http://172.16.4.32:7080/oss_rp_subnets.htm

#### New URL
http://172.16.4.93:9080/ui2/Accounts/Subnets

#### Description of issue
Steps to recreate issue.
1. Select Subnets page
2. Select a Subnet
3. Select the Update button.
4. Change the IP Bit Mask
5. Select Submit button - an error message is returned and the IP Bit Mask value is not changed.
However, viewing the legacy we interface shows that the value was updated.  Also, refreshing the new interface shows that the value was updated as expected.

**Comment by fenichelar** [comment]
The following url is returning an error from NexOSS but is functioning as expected. What needs to change about the url?

http://172.16.4.32:7080/cgi-bin/action/devstat2?originalGroup=PassThru&originalShortName=passThru-1&originalAddress=0.0.0.0&originalHasEnrolled=false&originalProtocol=SIP&originalOspVersion=0.0.0&originalInPrefix=&originalBitMaskLength=3&originalNetworkId=&originalStripInPrefix=false&originalInMaxCallBurstPerMinute=60000&originalInCallGappingInSeconds=0.001&originalMandDestAttribute=&originalPreDestAttribute=&originalUseCDRMediationRulesFor=All_Other_Devices&originalId=a7d3d17cda5db6f908d012889e8b59bc358bd5c4&0=true&group=PassThru&shortName=passThru-1&address=0.0.0.0&hasEnrolled=false&protocol=SIP&ospVersion=0.0.0&inPrefix=&bitMaskLength=1&networkId=&stripInPrefix=false&inMaxCallBurstPerMinute=60000&inCallGappingInSeconds=0.001&mandDestAttribute=&preDestAttribute=&useCDRMediationRulesFor=All_Other_Devices&id=a7d3d17cda5db6f908d012889e8b59bc358bd5c4

**Comment by DmitryIsakbayev** [comment]
This problem should go away when OSS is upgraded to 8.9.12.  It has to do
with the outPrefix property being set to null.

From release notes:
o Bug Fix: NullPointerException at Configuration$25.device triggered by a
subnet added through UserIntefaceTwo (null value in outPrefix)

Stack trace:
        java.lang.NullPointerException
        at com.transnexus.DevManager.updateOutPrefix(DevManager.java:704)
        at com.transnexus.DevManager.updateDevice(DevManager.java:450)
        at
com.transnexus.Configuration.updateDevice(Configuration.java:1146)
        at com.transnexus.CgiBin$34.processRequest(CgiBin.java:1945)
        at com.transnexus.CgiBin.syncProcessRequest(CgiBin.java:3474)
        at com.transnexus.CgiBin.processRequest(CgiBin.java:3405)
        at com.transnexus.CgiBin.handleRequestInternal(CgiBin.java:4115)
