### ISSUE TITLE
Old/New UI integration user experience

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#185]
Gentlemen,
  At the beginning of this project, I had hoped that we could offer users a very convenient transition from the old UI to the new UI.  I know that I agreed to make the transition from port 7080 to 9080, but I would like to revisit that decision and explore if a better experience is practical.  Below is my wish list for what I hope users will experience when we are done with the new UI.
1) Users access both the new and old UI using port 7080.
2) The new UI authentication system works for both the old and new UI.
3) The new UI has a Legacy button that takes users to the corresponding page on the old UI.  This is already done.  However, if there is no corresponding page on the old UI, then the users should see a page that says "The requested page does not exist on the legacy interface."  This page should also give users the choice to return to the page they came from of go to the Legacy dashboard.  I do not want users to see a 404 page and think our software is broken.
4) The old UI has link that will take users to dashboard of the new UI.
5) The Rate Provisioning Tool, downloaded from the new UI, will work with no changes.
6) API connection direct to NexOSS, not via sails.js should be possible.
7) Support API connections to sails.js as planned.

I think we need a discussion to determine if, and which, of these requirements are practical in terms of the implementation investment required.

**Comment by fenichelar** [comment]
3 - The "Legacy" button always takes the user to the old dashboard. It is no longer contextually aware due to the 404 issue.

**Comment by DmitryIsakbayev** [comment]
Work in progress.  For now, you need to explicitly go to :9080/ui

**Comment by DmitryIsakbayev** [comment]
Added a local default file that redirects to /ui.
fenichelar, in order to access the old UI through thew new web server, you have to explicitly go to /index.htm.   If the "Legacy" button is not contextually aware, let's change it to redirect to /index.htm

**Comment by fenichelar** [comment]
@DmitryIsakbayev The "Legacy" button now redirects to `/index.htm`.

**Comment by fenichelar** [comment]
What tasks are remaining?

**Comment by JimDalton** [comment]
Works great!

**Comment by JimDalton** [comment]
If user navigates from New UI to old UI and then back to the new UI, they user will see the dashboard but no navigation on the new UI.
![image](https://cloud.githubusercontent.com/assets/18315382/18797882/f96081c2-819d-11e6-8481-ba98f5577403.png)

**Comment by fenichelar** [comment]
@DmitryIsakbayev Can you link to `/ui/login` as we discussed?

**Comment by DmitryIsakbayev** [comment]
Implemented in 8.12.7 - o Changed redirect link to the New UI from /ui to /ui/login
It is already running in the lab.

**Comment by DmitryIsakbayev** [comment]
Please test.

**Comment by DmitryIsakbayev** [comment]
In order to allow https to proxy to an http server - https://sourceforge.net/p/j2ep/feature-requests/5/

**Comment by JimDalton** [comment]
Closing this issue - Thank you.
