### ISSUE TITLE
Partial URL encoding of paths and drowpdownUrl values

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#186]
@fenichelar,

It would simplify page configuration if the URls could include spaces and pluses.

Also, having a comment text area could be useful for documenting API.

**Comment by fenichelar** [comment]
@DmitryIsakbayev What characters need to be encoded? Spaces and ... I don't remember

**Comment by DmitryIsakbayev** [comment]
@fenichelar, spaces and the plus sign.

**Comment by fenichelar** [comment]
```
String.prototype.encode = function() {
  return this.replaceAll("+", "%2B").replaceAll("#", "%23").replaceAll(" ", "%20");
};
```

**Comment by fenichelar** [comment]
Done.
