### ISSUE TITLE
Make Details View more usable

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#187]
#### Description of Issue

View of Details is hard to read because the description column is too narrow.  Need a way to fix column width, or let users vary the column width.

![image](https://cloud.githubusercontent.com/assets/18315382/18017969/3d211618-6ba2-11e6-87a5-fb2ac92206ea.png)

**Comment by fenichelar** [comment]
@JimDalton Done. Please test.

**Comment by JimDalton** [comment]
Better!
