### ISSUE TITLE
404 when trying to view fileCDR

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#188]
#### Description of Issue
Working with KPU and tried to drill down to view CDRs in Traffic Analyzer/Call Completion/By Customer/By Time and Dial Code.  CDR details view was 404.  Replicated the problem on .32.
![image](https://cloud.githubusercontent.com/assets/18315382/18105131/4a011734-6ecc-11e6-9b1c-1b6cb7d86ab4.png)

**Comment by fenichelar** [comment]
@JimDalton Resolved, please test tomorrow.

**Comment by JimDalton** [comment]
Works as expected.
