### ISSUE TITLE
Default value for Device IP Port should be empty, not 0.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#19]
#### Page Title
Devices

#### Legacy URL
http://172.16.4.32:7080/oss_rp_devices.htm

#### New URL
http://172.16.4.93:9080/ui2/Accounts/Devices

#### Description of issue
Device IP port is an optional value.  For 99.9% of use cases, this value is not configured.  If it is not configured the data should be empty.  In the screenshot below, the IP port = 0.
![image](https://cloud.githubusercontent.com/assets/18315382/15093681/b2a3cfb8-145c-11e6-8c13-2bbc1ad15e4d.png)

**Comment by fenichelar** [comment]
This appears to be coming from NexOSS.

**Comment by DmitryIsakbayev** [comment]
That is correct.  The port property is of type integer and the default
value is 0.  0 indicates that the port number should not be reported in the
OSP Authorization Response message.  The GUI is instructed to display 0 as
empty.

**Comment by fenichelar** [comment]
I am not sure how this can be implemented in the new UI. When should 0 not be displayed?

**Comment by DmitryIsakbayev** [comment]
I think it is a fairly unique use case.

**Comment by DmitryIsakbayev** [comment]
Implemented in NexOSS 8.9.17

**Comment by fenichelar** [comment]
Done.
