### ISSUE TITLE
Dashboard-Logs directory is gone!

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#192]
@fenichelar   I cannot find the directory that holds all the json pages for log files.  I probably lost it yesterday when I changed the directory name 01-Dashboard to 09-Server.

I need your help with this problem.

**Comment by JimDalton** [comment]
Hello Alec,

> Do you want me to reset everything back to "Fix links to Rate Provisioning templates, Devices and Destination Att…"?

Not sure.  Will this undo all the changes I have made since then?  I do not want to lose my recent changes.

Maybe I should upload a config file that only has log pages.  However, I think I should do that when you are in the office to avoid unintended consequences.

 

What is your suggestion?

 

Thank you,

 

Jim D.

**Comment by fenichelar** [comment]
Let's look at this tomorrow when I am in the office. I can recover any file that was ever in the repository. Nothing is lost.

**Comment by JimDalton** [comment]
Great!

**Comment by fenichelar** [comment]
@JimDalton Is this resolved?

**Comment by JimDalton** [comment]
Log pages have been restored.
