### ISSUE TITLE
Cannot provision Destination to a Provider Route

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#193]
I added two new Provider Route Breakouts as shown in the following screenshot.  Providers 00-TestNewUI and Ameritech, Breakout = 1.
![image](https://cloud.githubusercontent.com/assets/18315382/18324028/68ca89ce-7508-11e6-8812-202fa5d69522.png)

But when I go to add destinations to these Provider Route Breakout, the two new Breakouts do not appear.
![image](https://cloud.githubusercontent.com/assets/18315382/18324136/dc13aa8c-7508-11e6-80f0-f37660b7bdc6.png)

This may be related.  It is not possible to have a Provider Route Breakout with no Destination.  This was possible in the old UI.  In the new UI, you cannot update a Provider Route Breakout to have no Destination.  No Destination is not a choice in the dropdown menu.
![image](https://cloud.githubusercontent.com/assets/18315382/18324184/2fba8138-7509-11e6-9c0f-07ae0975fee2.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton

For the breakouts that do not have a destination, should the destination and weight be empty?
The legacy UI had the 1st choice in the dropdown box as "--Select--".  Do you want the same choice here as well?

**Comment by JimDalton** [comment]
@DmitryIsakbayev   An empty destination makes sense for me if the Breakout should not have a destination.  Not sure if I care if rank and weight are 1 or empty if no destination is configured.

The modal includes a little x in the box with the Destination.  If a user clicks this x, it removes the Destination and leaves the box empty as expected.  I expected that I could click on the submit button and I would have a Provider Route Breakout with no Destination.  You can see the modal below.
At this point, I am not sure what is best.  Maybe we can brainstorm on Friday
![image](https://cloud.githubusercontent.com/assets/18315382/18327497/c9dccd70-7518-11e6-93b9-fe3730ec5c81.png)

**Comment by fenichelar** [comment]
What is the status of this issue? Any action items for me?

**Comment by JimDalton** [comment]
@DmitryIsakbayev   Still an issue adding a Destination to a Provider Route. I am testing this on .32 which has NexOSS V8.12.5

In the screenshot below, you see that provider 00-TestNewUI has been assigned the breakouts 1 , 2 and All Other Numbers.
![image](https://cloud.githubusercontent.com/assets/18315382/18924830/9d63b278-857f-11e6-9b3f-f5fdd020fa20.png)

When I go to add a Destination to a Breakout for Provider 00-TestNewUI, you will see that the dropdown box includes a lot of breakouts that have not been provisioned to the Provider 00-TestNewUI.
![image](https://cloud.githubusercontent.com/assets/18315382/18925252/3e81952a-8581-11e6-90b6-5a5663af05d5.png)

If I select one of these breakouts that has not been provisioned to 00-TestNewUI
![image](https://cloud.githubusercontent.com/assets/18315382/18925273/5689cb4c-8581-11e6-997c-7b222c098490.png)

The Submit fails, which makes sense, but this is annoying for the customer.  The breakouts in the Dropdown box should only breakouts provisioned to the Provider.  Could this be a problem with "Dependency" not configured to the Breakout's column?  I cannot tell because I cannot get to the UI on .101.
![image](https://cloud.githubusercontent.com/assets/18315382/18925307/7b551ae4-8581-11e6-8a6a-b40337b3bd65.png)

**Comment by DmitryIsakbayev** [comment]
Looks like the Column configuration for Breakout and Destination are missing "dependency" property and "?provider=PATHMASK" parameter in the API field.  I will fix it when the UI login issue is resolved on .100

**Comment by DmitryIsakbayev** [comment]
Configured dependency of breakouts and destinations on the selected provider

**Comment by JimDalton** [comment]
Work as expected
