### ISSUE TITLE
Cannot Provision a Provider to a Product Breakout

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#194]
I provisioned a new breakout = 1770 to the ATT-PIC product as shown in the screenshot below.  This worked as expected.
![image](https://cloud.githubusercontent.com/assets/18315382/18325608/ff230746-750f-11e6-8897-4f5a595aea22.png)

However, when I go to the page shown below to provision Providers for the breakout = 1770, it is not available.  I realize now that this was my error,  If I click the Add button, I can add the breakout and a Provider (or no Provider).  After submitting, the breakout appears which is technically correct, but was confusing to me.  It might be better to see all the breakouts in this table, with no Providers configured.
![image](https://cloud.githubusercontent.com/assets/18315382/18325641/2ccd7f3c-7510-11e6-85e6-a01bd6f58dbb.png)

In a similar problem, if I try to update a breakout be removing the provider, I get the message something went wrong.
![image](https://cloud.githubusercontent.com/assets/18315382/18325568/d68a3714-750f-11e6-8513-f196f762d8ed.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton, in order to delete a provider, you need to select it and click on "Delete".  I don't think the UI should allow users to leave the property empty.
@fenichelar, can we mark a dropdown property as required?

**Comment by JimDalton** [comment]
@DmitryIsakbayev   Isn't having a Product Breakout with no provider how we block routes?  If this is correct, how can we configure this in the new UI?

**Comment by JimDalton** [comment]
@DmitryIsakbayev    Hmm... I see that I deleted a Provider in the new UI and broke the NexOSS config.  OK, I think I understand your point.  

Hear are my thoughts:
1) If a user deletes a Provider from a Product Breakout, all the other properties need to be deleted to avoid the error I just caused.
2) I think our existing users may have the same experience I have had since they are accustomed to the legacy UI.  Longer term, it might help to implement pages for Provider and Product routes on the new UI that were similar to the legacy interface.
3) I think we need to use what we have for awhile before we make any changes.

**Comment by JimDalton** [comment]
FYI,  The highlighted row in the screenshot is a Product route with no Provider.
![image](https://cloud.githubusercontent.com/assets/18315382/18329651/8d78ad9a-7522-11e6-8483-348ccd478615.png)

**Comment by JimDalton** [comment]
"All Other Numbers" is a not an option in the dropdown menu to add route to a product.
![image](https://cloud.githubusercontent.com/assets/18315382/18601581/aa88161c-7c31-11e6-96bd-0c373d1c1ce8.png)

**Comment by JimDalton** [comment]
Closing this issue and re-opening as issue 214.
