### ISSUE TITLE
Edits to Users page

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#195]
1) Change "Ready Only" to "Read Only"
2) The page title "Users" appears twice.  Remove one and change page title to "User Access Administration"
3. This is not an issue worth fixing, but it is worth noting that the columns and column titles do not align.  This occurs when you click "Edit this Page", which takes the user to the "Edit this Interface" page. and then return to the users page.

![image](https://cloud.githubusercontent.com/assets/18315382/18352362/2471f420-75ac-11e6-8499-c78609e15397.png)

**Comment by fenichelar** [comment]
1 - Fixed.
2 - Fixed.
3 - I am unable to reproduce.

**Comment by fenichelar** [comment]
@JimDalton Please test after the next build.

**Comment by JimDalton** [comment]
Thank you
