### ISSUE TITLE
Missing Fraud Rates Pages

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#196]
The page /ui/Fraud-Control_CDR-Analytics-Basic_Configuration_Fraud-Rates_EDefault returns a 404.

I think I may have named the json file 03-E.164-Default.  But in my Github directory I see the file name is 03-E164-Default.  Any ideas about why the page returns a 404?
 
![image](https://cloud.githubusercontent.com/assets/18315382/18391331/ae25e1c0-767b-11e6-8743-5b90dce1f07b.png)

**Comment by DmitryIsakbayev** [comment]
I see the file name as 03-E164-Default.json
@fenichelar, maybe it is because of the number (164) in the file name.

**Comment by fenichelar** [comment]
Resolved.
