### ISSUE TITLE
QoS API

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#197]
None of the QoS pages are loading data. It appears to be an issue with `paths.view`.

**Comment by DmitryIsakbayev** [comment]
@fenichelar, you are right.  The `path.view` was missing a block of parameters.  I have updated the config/pages/NexOSS/07-QoS/01-QoS-Summary/01-By-Customer/01-By-Customer-and-Provider.json report and now the server is sending a response.  There is something else going on, the page is still not displaying the report.

**Comment by DmitryIsakbayev** [comment]
Used this script to update all QoS reports.  It replaced -
report&forKey=FILTERMASK&displayMinusOneAs=
with
report,tree-report-viewer&includeHeaders=false&forReportFileName=PATHMASK&forKey=FILTERMASK&displayMinusOneAs=


for f in `ls NexOSS-Web-Server/config/pages/*/*QoS/*/*/*json `
do
	echo $f
	sed -e 's|report\&forKey=FILTERMASK\&displayMinusOneAs=|report,tree-report-viewer\&includeHeaders=false\&forReportFileName=PATHMASK\&forKey=FILTERMASK\&displayMinusOneAs=|g' $f > $f.new
	mv $f.new $f
done

**Comment by JimDalton** [comment]
tested /ui/QoS_QoS-Summary_By-Customer_By-Customer-and-Provider
Works as expected
