### ISSUE TITLE
Links from Dashboard to Triggers page is broken

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#198]
@fenichelar   Alec, when I click on the red Fraud Analytics Trigger icon on the dashboard, I get a 404 Page nott Found error.  Will this error be fixed in the new dashboard?
![image](https://cloud.githubusercontent.com/assets/18315382/18451933/fefbe1ac-7906-11e6-92b2-1050d31a942f.png)

**Comment by fenichelar** [comment]
@JimDalton Yes.

**Comment by JimDalton** [comment]
@fenichelar    Links from the new dashboard still get a 404.
![image](https://cloud.githubusercontent.com/assets/18315382/18482134/f8119b88-79ac-11e6-9a9f-edb62aa52bd6.png)

**Comment by fenichelar** [comment]
@JimDalton Resolved. Please test tomorrow.

**Comment by JimDalton** [comment]
Work as expected.
