### ISSUE TITLE
Change NexOSS to return empty values instead of -1

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#2]
#### New URL
Example page: Fraud-Control/SIP-Analytics/Advanced/By-Calling-Number/Theft-of-Service/History-Report

**Comment by DmitryIsakbayev** [comment]
Edit config file - edit paths.view for reports to include &displayMinusOneAs=
Do not provide any value after the equal sign.

**Comment by JimDalton** [comment]
Updated config file.

**Comment by JimDalton** [comment]
@DmitryIsakbayev 
The path.view in the config file has been changed to include &displayMinusOneAs=.  Also, a ? proceeds this in the url.
/applet/cgi-bin/data/viewReport.exe?appPrefix=Analyzer&appSubPrefix=&contextName=OSS-2-Customer-PFS-Report&contextResources=tree-report-viewer&includeHeaders=false&forReportFileName=PATHMASK&forKey=FILTERMASK&displayMinusOneAs=

However, -1 is still displayed in the report: http://172.16.4.93:9080/ui2/Fraud-Control/CDR-Analytics-Advanced/By-Customer-Device/Traffic-Pumping/Trigger-Report

Any ideas why the -1 is still displayed?

The legacy url is /analyzer/oss_ta_fss_Fraud_Analytics_for_CDRs_for_Advanced_for_By_Customer_Device_for_Traffic_Pumping_for_Trigger_Report_for_Traffic_Report.htm

Screenshot:
![image](https://cloud.githubusercontent.com/assets/18315382/14882989/9a8d2500-0d09-11e6-8106-139c22293f2d.png)

**Comment by DmitryIsakbayev** [comment]
This feature requires a new release of NexOSS, after version  8.09.08

**Comment by JimDalton** [comment]
Done
