### ISSUE TITLE
key value is present in the Number Translation Modal

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#20]
#### Page Title
Any Number Translation Page, DID page

#### New URL
http://172.16.4.93:9080/ui2/Number-Translation/Routing/Called-Number-Manipulation

#### Description of issue
The value column.0.title = key is visible in the modal, even though column.0.visible=false.  It is not visible in the page, but it is viewable and editable in the modal.
![image](https://cloud.githubusercontent.com/assets/18315382/15093801/0e0c31ee-1460-11e6-86b6-a9363feab9a6.png)

**Comment by fenichelar** [comment]
When the Sails API is updating to use the new NexOSS API, this column will no longer be needed.

**Comment by fenichelar** [comment]
Please set the order of key to -1.

Also, it appears the dropdown url for customer account is wrong.

**Comment by fenichelar** [comment]
Also, please remove unique from the Excel file.
