### ISSUE TITLE
Using the required value for validations

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#200]
Please see the screenshot below.  You will see a couple of triggers with no Account and no Device.  I think this is a use case we want to avoid.  To fix this, I entered required as the validations property.  No, the modal will not close with the submit buttom until the required fields are submitted.  But there is no message to the user why the submit does not work.  Need a message to the user so they know what fields are incomplete.
![image](https://cloud.githubusercontent.com/assets/18315382/18478969/352d009a-79a1-11e6-8477-9f6cb85ec44d.png)

**Comment by fenichelar** [comment]
@JimDalton I have identified the issue and will address it. Please do not use the required validation until then as some modifications might be needed.

**Comment by fenichelar** [comment]
@JimDalton Resolved. No changes to design required. Please use like previously discussed.

**Comment by JimDalton** [comment]
Works as expected.
