### ISSUE TITLE
Default setting for Suspend Time is not applied

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#201]
When adding a Fraud Trigger Threshold, the default setting of 60 is not being applied.  Also, when the suspend time is manually changed to 60, it is recorded as -1. This field should only be a positive integer.  I cannot remember the validations we defined.  Would it be possible for the validation box on the Edit Interface to be a dropdown box?
![image](https://cloud.githubusercontent.com/assets/18315382/18479472/233b2856-79a3-11e6-9904-c1412c5cc9b0.png)

**Comment by fenichelar** [comment]
@JimDalton I will alter the validations box to be a dropdown.

**Comment by JimDalton** [comment]
@fenichelar   It appears that none of the default values for fraud triggers are working as expected.

**Comment by fenichelar** [comment]
@JimDalton I am not able to reproduce this error. I do not see suspend time. Please fix the config `tabTitle` errors and test again.

**Comment by JimDalton** [comment]
@fenichelar   Hi Alec, I fixed the tabTitle for Suspend Calling and it now works as expected.  However, I created a new trigger and the suspend time is still -1

**Comment by DmitryIsakbayev** [comment]
The setting is applied but the order of the suspendTime column is wrong.  I will need to revisit the script I used for generating configuration for the trigger pages, fix it, and regenerate the pages.

**Comment by DmitryIsakbayev** [comment]
Here is the correct order of columns
0,key
1,forReport
2,matchGroupPattern
3,matchDevicePattern
4,calling
5,breakout
6,minSampleCount
7,minDestASR
8,minCSR
9,minACD
10,maxACD
11,PDD
12,maxRoR
13,calledMOS
14,callingMOS
15,sourceAssessment
16,destinationAssessment
17,callingAssessment
18,calledAssessment
19,suspendTime
20,shouldSuspendDevice
21,shouldAlarm
22,tUpACD
23,maxCallAttempts
24,tUpCallAttempts
25,maxCompletedCalls
26,tUpCompletedCalls
27,maxDuration
28,tUpDuration
29,maxCallTransferStatusBySourceCount
30,tUpCallTransferStatusBySourceCount
31,maxCallAttemptsScore
32,tUpCallAttemptsScore
33,maxCompletedCallsScore
34,tUpCompletedCallsScore
35,maxDurationScore
36,tUpDurationScore
37,maxCallTransferStatusBySourceCountScore
38,tUpCallTransferStatusBySourceCountScore
39,oBillingAmount
40,tBillingAmount
41,calculatedScoreFactor
42,minScoreAnd
43,minHistoricalCDRsProcessed

**Comment by JimDalton** [comment]
For the Tigger Thresholds, three columns are out of place in the UI configuration. Column numbers range from 0-43 in this note, not 1-44 as referenced in the Edit Interface.
Correct Not Correct
Col #, api api in UI Config
19 suspendTime

20 shouldSuspendDevice

21 shouldAlarm
~
26 tUpCompleteCalls suspendTime
27 maxDuration shouldSuspendDevice
28 tUpDuration shouldAlarm

Need to swap columns 19-21 in UI config with columns 26-28 for the following pages.
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Basic_By-Customer-Device_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Basic_By-Calling-Number_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Basic_By-Calling-Number_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Basic_Blacklisted-User-Agents_Blocked-Calls_By-Customer_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Basic_Blacklisted-User-Agents_Blocked-Calls_By-Calling-Number_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Basic_Blacklisted-Called-Numbers_By-Customer_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Basic_Blacklisted-Called-Numbers_By-Calling-Number_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Basic_Blacklisted-Countries_By-Customer_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Advanced_By-Customer-Device_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Advanced_By-Customer-Device_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Advanced_By-Calling-Number_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Advanced_By-Calling-Number_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_By-Customer-Device_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_By-Calling-Number_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_By-Calling-Number_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_By-GroupId_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_By-GroupId_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_By-UserId_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_By-UserId_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Called-Numbers_By-Customer_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Called-Numbers_By-Calling-Number_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Called-Numbers_By-Calling-UserId_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Countries_By-Customer_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Advanced_By-Customer-Device_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Advanced_By-Customer-Device_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Advanced_By-Calling-Number_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Advanced_By-Calling-Number_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Advanced_By-GroupId_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Advanced_By-GroupId_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Advanced_By-Calling-UserId_Traffic-Pumping_Trigger-Thresholds
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Advanced_By-Calling-UserId_Theft-of-Service_Trigger-Thresholds
http://172.16.4.101:7080/ui/Traffic-Analyzer_Triggers_By-Customer_By-Account_Thresholds
http://172.16.4.101:7080/ui/Traffic-Analyzer_Triggers_By-Customer_By-Device_Thresholds
http://172.16.4.101:7080/ui/Traffic-Analyzer_Triggers_By-ServiceProviderId_Thresholds
http://172.16.4.101:7080/ui/Traffic-Analyzer_Triggers_By-Proxy-Device_Thresholds
http://172.16.4.101:7080/ui/Traffic-Analyzer_Triggers_By-Provider_By-Account_Thresholds
http://172.16.4.101:7080/ui/Traffic-Analyzer_Triggers_By-Provider_By-Device_Thresholds
http://172.16.4.101:7080/ui/Traffic-Analyzer_Triggers_By-Provider_By-Device-and-Dial-Code_Thresholds
http://172.16.4.101:7080/ui/Traffic-Analyzer_CDRs_Processed_By-Reporting-Device_Trigger-Thresholds
http://172.16.4.101:7080/ui/QoS_Source-QoS_Triggers_Thresholds
http://172.16.4.101:7080/ui/QoS_Destination-QoS_Triggers_Thresholds
http://172.16.4.101:7080/ui/QoS_Calling-Party-QoS_Triggers_Thresholds
http://172.16.4.101:7080/ui/QoS_Called-Party-QoS_Triggers_Thresholds
http://172.16.4.101:7080/ui/Billing_Credit-Controls_By-Customer_By-Hour_Trigger-Thresholds
http://172.16.4.101:7080/ui/Billing_Credit-Controls_By-Customer_By-Day_Trigger-Thresholds
http://172.16.4.101:7080/ui/Billing_Credit-Controls_By-Calling-Number_By-Hour_Trigger-Thresholds
http://172.16.4.101:7080/ui/Billing_Credit-Controls_By-Calling-Number_By-Day_Trigger-Thresholds
http://172.16.4.101:7080/ui/Billing_Credit-Controls_By-GroupId_By-Hour_Trigger-Thresholds
http://172.16.4.101:7080/ui/Billing_Credit-Controls_By-GroupId_By-Day_Trigger-Thresholds

**Comment by DmitryIsakbayev** [comment]
The 3 new triggers under pages/NexOSS/05-Fraud-Control/00-SIP-Analytics-Registrations/Fraud Control should have the columns in the right order.

**Comment by fenichelar** [comment]
Done. Please test.

**Comment by JimDalton** [comment]
Works as expected.
