### ISSUE TITLE
Fraud Trigger Suspend Calling box not visible in modal.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#202]
http://172.16.4.101:7080/ui/Fraud-Control_SIP-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Thresholds

The Suspend Calling column is in the Trigger Report, but not in the modal.

![image](https://cloud.githubusercontent.com/assets/18315382/18486552/896d330a-79bf-11e6-8774-642b768797f9.png)

**Comment by fenichelar** [comment]
@JimDalton This is caused by the `tabtitle` not being set to "Suspend Calling" for any columns.

**Comment by JimDalton** [comment]
Fixed!  - Thank you.
