### ISSUE TITLE
Does Markdown Editor for Add button support tables?

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#203]
Creating a Markdown table looks really simple.  I tried to add a Markdown table to the button to add a Number Translation rule, but it did not work for me.  Any idea of what I am doing wrong?
![image](https://cloud.githubusercontent.com/assets/18315382/18529605/cbb57f9c-7a9b-11e6-8565-00f972692f7f.png)

**Comment by fenichelar** [comment]
@JimDalton Tables are disabled by default. I have enabled tables. Should work tomorrow.
