### ISSUE TITLE
Link to CDR files is broken 

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#204]
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Advanced_By-Customer-Device_Traffic-Pumping_Trigger-Events

Clicking on the View CDRs button in the trigger events page returns a 404.  Maybe this link was broken when we migrated to port 7080.  This is my first test since the change to port 7080.

![image](https://cloud.githubusercontent.com/assets/18315382/18559296/aab43974-7b44-11e6-9c74-e57bac8ab0a1.png)

**Comment by fenichelar** [comment]
I suspect it is related to the changing of '/' to '/ui/'. Should be an easy fix.

**Comment by JimDalton** [comment]
Works as expected
