### ISSUE TITLE
Cannot Download Rate Provisioning Tool or Rate Templates

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#205]
When I try to download the rate provisioning tool (/ui/Rate-Provisioning_Rate-Provisioning-Tool) on both .101 and .32, I get the message "This site can’t be reached  lib’s server DNS address could not be found."  See screenshot below.  Also, when I try to download rate plan template (/ui/Rate-Provisioning_Provider-Rates_Manual-Upload) the result is a blank web page with the word "unauthorized".

![image](https://cloud.githubusercontent.com/assets/18315382/18676503/d0d18d9a-7f23-11e6-9efb-edf600d7b1f3.png)

**Comment by fenichelar** [comment]
@JimDalton @DmitryIsakbayev The rate plan template issue was caused by a breaking change I made. This broke all downloads from Sails. I have fixed the issue.

@DmitryIsakbayev The rate provisioning tool is another issue. We should discuss Friday.

**Comment by JimDalton** [comment]
Rate plan templates can be downloaded as expected.

**Comment by fenichelar** [comment]
Resolved.

**Comment by JimDalton** [comment]
I was unable to open the route provisioning tool from .101 and .32.

![image](https://cloud.githubusercontent.com/assets/18315382/18852280/bf2a28ba-840d-11e6-993c-59af192fc0c6.png)

ExitException[ 3]com.sun.deploy.net.FailedDownloadException: Unable to load resource: http://localhost:7080/lib/NexOSS_rate_provisioning_tool.jsp
	at com.sun.javaws.Launcher.updateFinalLaunchDesc(Unknown Source)
	at com.sun.javaws.Launcher.updateFinalLaunchDesc(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by fenichelar** [comment]
@JimDalton Which link did you use?

**Comment by JimDalton** [comment]
The rate provisioning tool works when downloading from .32.  
I think I downloaded from .101 when it failed to started.
