### ISSUE TITLE
No search boxes for tables on .101

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#208]
@fenichelar   Alec, I do not see search boxes at the top of each column table on the new UI on .101.  However, I do see the search boxes on the top of each column on .32.  I think something changed with the new UI build on .101.  See the comparison below.

Screenshot of .101
![image](https://cloud.githubusercontent.com/assets/18315382/18746629/7b1d4884-8096-11e6-81a4-4ef8b84db3db.png)

Screenshot on .32
![image](https://cloud.githubusercontent.com/assets/18315382/18746640/911804d0-8096-11e6-8ad7-53b93752f9ea.png)

**Comment by fenichelar** [comment]
@JimDalton Resolved.
