### ISSUE TITLE
Need to port ui/Billing_Prepaid-Billing_Warning-Accounts page

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#209]
The Prepaid Billing page that lists accounts that have been warned their credit is too low needs to be ported to new UI.  This page is still an iframe.

http://172.16.4.101:7080/ui/Billing_Prepaid-Billing_Warning-Accounts

**Comment by DmitryIsakbayev** [comment]
Implemented Warning and Blocked accounts using All Accounts as a template.  Please test.

**Comment by JimDalton** [comment]
Working as expected.
