### ISSUE TITLE
Need to port Prepaid Billing Block Accounts page to new UI

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#210]
Need to port /ui/Billing_Prepaid-Billing_Blocked-Accounts to new UI.

This page is still an iFrame

**Comment by DmitryIsakbayev** [comment]
Implemented Warning and Blocked accounts using All Accounts as a template.  Please test.

**Comment by JimDalton** [comment]
Working and blocking calls as expected
