### ISSUE TITLE
Cannot View CDR Details

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#212]
#### Page Path  Cannot View CDR Details from /ui/Traffic-Analyzer_Call-Completion_By-Customer_By-Time-and-Dial-Code

/ui/special/fileCDR/Call%20Completion%20Report%20by%20Customer%20-%20Time%20-%20Dial%20Code/%20%2F%20Home%20%2F%20Day%202016-09-26%20EDT(-0400)%20%2F%20Customer-17/2016-09-26-20160922114351-CDRs-Source.report.details%2FDay%2B2016-09-26%2BEDT%2528-0400%2529%2FCustomer-17%2FHour%2B00
#### Description of Issue
![image](https://cloud.githubusercontent.com/assets/18315382/18843014/198637c8-83e5-11e6-9f54-488195ffcb91.png)

**Comment by fenichelar** [comment]
@DmitryIsakbayev What is wrong with this url - `/analyzer/cgi-bin/data/getReportFile.exe?dir=../../../REPORTS/2016-09-26-20160922114351-CDRs-Source.report.details/Day%2B2016-09-26%2BEDT(-0400)/Customer-17/Hour%2B00&file=details.txt&zippedDirLevel=5&fromLine=2&tokenDelimiter=%09&sortBy=3&sortOrder=asc&sortType=text&offset=0&limit=100`

**Comment by DmitryIsakbayev** [comment]
@fenichelar  Spaces are encoded as %2B which is +.  Maybe there is a conflict with the partial encoding of spaces and pluses for NexOSS API calls.

**Comment by fenichelar** [comment]
Caused by an encoding issue. Resolved. Please test.

**Comment by JimDalton** [comment]
Works as expected.
