### ISSUE TITLE
All Other Numbers interpret as blank

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#213]
#### Page Path
Route-Provisioning_Least-Cost_Products_Breakouts

#### Description of Issue
Add a breakout to a product and leave the breakout blank. Then attempt to update the breakout. I believe this is caused by me giving you "All Other Numbers" for breakout instead of blank.

**Comment by DmitryIsakbayev** [comment]
You are correct.  NexOSS needs to convert "All Other Numbers" to an empty string before using the value.  Let's test after the lab is upgraded to 8.12.5

**Comment by JimDalton** [comment]
Works as expected
