### ISSUE TITLE
Minimum Call Setup Default is -1, not 0

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#216]
When adding a Fraud Trigger, the Minimum Call Setup Count box is empty.  If the user does not enter a number, then -1 is configured.  -1 does not make sense.  The default value is 0, type=number.  It would be better is the Minimum Call Setup Count box in the modal was 0 by default rather than empty. 
![image](https://cloud.githubusercontent.com/assets/18315382/18853876/879b3792-8415-11e6-9006-5cc0b5a6d4d5.png)

**Comment by fenichelar** [comment]
Resolved. Please test.

**Comment by JimDalton** [comment]
Work as expected
