### ISSUE TITLE
Cannot drill to the end of fraud trigger reports.  Unable to view data by time.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#217]
Page: /ui/Fraud-Control_SIP-Analytics-Advanced_By-Customer-Device_Traffic-Pumping_Trigger-Report
Cannot drill down to final level to view data by time.  500 Error returned.
Same problem occurs with other fraud trigger reports.
![image](https://cloud.githubusercontent.com/assets/18315382/18895523/3a69809a-84e8-11e6-89ee-5fbd5f475fcc.png)

**Comment by fenichelar** [comment]
Caused by an encoding issue. Resolved. Please test.

**Comment by JimDalton** [comment]
Works as expected.
