### ISSUE TITLE
Better Error message for too many characters in a modal field.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#218]
When I enter 101 characters in the Note data entry box for the Number Translation modal, the error is "Something went wrong".  It would be better if the error indicated which modal value was in error and why.  For example, "Note cannot exceed 100 characters."  This is a lower priority than documenting the Edit Interface.
![image](https://cloud.githubusercontent.com/assets/18315382/18969760/79fc66ee-865c-11e6-898b-162665f1d1cd.png)

**Comment by fenichelar** [comment]
@JimDalton Use validation `note_100`.

**Comment by JimDalton** [comment]
Added Note_100 validation to Number Translation Notes and Breakout Code Comments.
Works as expected, except that this validation allows \ and /.  No check for bad characters.

**Comment by JimDalton** [comment]
Close this issue and leave the issue about bad characters still need to be checked in the Note_100 validation in the Validations Issue.
