### ISSUE TITLE
No link to CDRAnalyzer on new UI

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#221]
Need a link on the new UI that takes the user to the CDRAnalyzer IP address in the NexOSS license.

**Comment by fenichelar** [comment]
@DmitryIsakbayev What is the API to get the IP?

**Comment by DmitryIsakbayev** [comment]
@fenichelar  How about we use API similar to the one for the license page -
`/cgi-bin/data/licdata.exe?useKeyValuePairEncoding=true&includeBuildInfo=false&key=RemoteCDRAnalyzer&type=string&alias=RemoteCDRAnalyzer`

It will return a key/value pair

`RemoteCDRAnalyzer<TAB>http://172.16.4.24:7080`

If it works for you, I will extend the api to support includeBuildInfo=false parameter.

**Comment by DmitryIsakbayev** [comment]
Implemented in NexOSS 8.12.6

**Comment by fenichelar** [comment]
@DmitryIsakbayev looks good. Implementing my side.

**Comment by fenichelar** [comment]
@JimDalton Please test tomorrow.

**Comment by JimDalton** [comment]
Works on .101 as expected.
