### ISSUE TITLE
SIP Registration Reports not working

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#222]
All SIP Registration reports are failing NexOSS V8.12.5 running .32 with "Internal Server Error".  These reports were working.  Need to retest when .101 is up.
![image](https://cloud.githubusercontent.com/assets/18315382/18973951/56c00ed0-866e-11e6-820f-b9eb398c1b88.png)

**Comment by JimDalton** [comment]
Same error still exists on NexOSS 8.12.5

**Comment by DmitryIsakbayev** [comment]
@JimDalton I think it has to do with trying to view reports in compressed format (they have .gz extension).  I will need to extend the NexOSS server to handle it.

**Comment by DmitryIsakbayev** [comment]
Should work after lab is upgraded to NexOSS 8.12.6.

**Comment by DmitryIsakbayev** [comment]
Please test

**Comment by JimDalton** [comment]
Works as expected.
