### ISSUE TITLE
Add Explicit Wild Card term for Default Triggers for ServiceProviderId, GroupId and UserId

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#225]
Defaults triggers are configured in NexOSS and SDReporter so there will be initial trigger without the customer having to make any configurations.  However, Wild Cards are displayed in the default triggers as empty values.  This is a little confusing.  It would be better if the default triggers for ServiceProviderId, GroupId and UserId had an explicit "Wild Card" value.  The screen shot below is an example of the current implementation. 

![image](https://cloud.githubusercontent.com/assets/18315382/19055728/7fd1f798-8993-11e6-8b7e-eb3f2379555b.png)

**Comment by DmitryIsakbayev** [comment]
Please test after upgrading to NexOSS 8.12.7 - Updated default Triggers to explicitly spell out "Wild Card"
In order to see the change, must use the Triggers.etc file included in the build.

**Comment by JimDalton** [comment]
Looks good.
