### ISSUE TITLE
Cannot view CDR Details for SIP Registrations

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#226]
#### Page Path
http://45.24.188.171:7080/ui/Fraud-Control_SIP-Analytics-Registrations_Analysis-Reports_By-Calling-Number
and
http://45.24.188.171:7080/ui/Fraud-Control_SIP-Analytics-Registrations_Fraud%20Control_By-Calling-Number_Trigger-Report

#### Description of Issue
Cannot view CDR details.
![image](https://cloud.githubusercontent.com/assets/18315382/19090496/c7bfceae-8a4c-11e6-9efb-69c62d562dc8.png)

**Comment by DmitryIsakbayev** [comment]
Since the report is old, the details are no longer available.  The server logs "ERROR  |Status 404 - The requested file does not exist on disk and there is no compressed folder" and returns HTTP 404 "Not Found".

@fenichelar  Can the UI display the code and message?

**Comment by fenichelar** [comment]
@DmitryIsakbayev Done.

**Comment by JimDalton** [comment]
Works as expected.
