### ISSUE TITLE
Cannot Replicate Number Translation files to OSPrey

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#229]
#### Page Path
http://172.16.4.101:7080/ui/Number-Translation_Replicate-to-OSPrey-Servers
This problem with replication of all configuration files, not just Number Translation

#### Description of Issue
![image](https://cloud.githubusercontent.com/assets/18315382/19097444/caf7b12e-8a72-11e6-9a64-7632d2ba9ff2.png)

**Comment by DmitryIsakbayev** [comment]
I think it is because the server is not selected.  Perhaps all available servers should be selected by default.

**Comment by fenichelar** [comment]
All servers are now automatically selected.

**Comment by JimDalton** [comment]
HA! Good catch and good suggestion.  Testing like a novice user is my best skill set.
Tested on .32 and it works as expected.  VPN into .32 and it worked as expected.
However, I could not download the rate provisioning tool with Waterfox.
