### ISSUE TITLE
Page Sections are not in order

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#23]
#### Page Title
Provider Rate Plans - Rejected

#### New URL
http://172.16.4.93:9080/ui2/editor/Rate-Provisioning_Provider-Rates_Rejected

#### Description of issue
Warnings (section 4) are presented above Errors (section 3).  Errors should be listed above Warnings.
![image](https://cloud.githubusercontent.com/assets/18315382/15119311/52749f22-15de-11e6-9392-672be381fb0b.png)

**Comment by fenichelar** [comment]
Please create some files so that I can reproduce the error. Thank you.

**Comment by fenichelar** [comment]
Done.
