### ISSUE TITLE
Waterfox compatibility problem - cannot download rate provisioning tool

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#230]
#### Page Path  
http://172.16.4.32:7080/ui/Rate-Provisioning_Rate-Provisioning-Tool

#### Description of Issue
Rate provisioning tool will do not download using Weterfox.  But is does download with Chrome and MS Edge.

**Comment by fenichelar** [comment]
@JimDalton Resolved. Please test.

**Comment by JimDalton** [comment]
Problem still exists.
![image](https://cloud.githubusercontent.com/assets/18315382/19539646/8257c6cc-9628-11e6-82d9-324fc44f3014.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton launching the rate provisioning tool or going to legacy UI require NexOSS to run on the same box.  They will not run on .101, .100 or .93.  Looks like your request came from .101

**Comment by JimDalton** [comment]
Doh... Good point.  I think you guys have told me that three times, maybe more.  I tried from .32 and got the same result. 
![image](https://cloud.githubusercontent.com/assets/18315382/19565517/1c02fbca-96b5-11e6-91c8-8b1b9919dd48.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton I can not reproduce the problem.  Would you please try it from the legacy ui /rates/oss_rate_prov_new_rates_upload.htm

**Comment by JimDalton** [comment]
Now, I cannot replicate the problem on .32
