### ISSUE TITLE
Pages do not display

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#231]
#### Page Path
http://172.16.4.101:7080/ui/Route-Provisioning_Least-Cost_Routes_Rates
http://172.16.4.101:7080/ui/Route-Provisioning_Least-Cost_Routes_Full-View
http://172.16.4.101:7080/ui/Route-Provisioning_Least-Cost_Products_Rates
http://172.16.4.101:7080/ui/Route-Provisioning_Least-Cost_Products_Full-View

#### Description of Issue
Nav bar is diplayed, but nothing else.  Alec says it is a encoding issue and has been fixed.
Need to test.

**Comment by JimDalton** [comment]
Fixed.

**Comment by JimDalton** [comment]
I spoke to soon.  These pages are now visible but all the data is NA

/ui/Route-Provisioning_Least-Cost_Routes_Full-View
![image](https://cloud.githubusercontent.com/assets/18315382/19170927/480596ba-8be8-11e6-99e8-4a6948332448.png)

/ui/Route-Provisioning_Least-Cost_Routes_Rates
![image](https://cloud.githubusercontent.com/assets/18315382/19170953/6ba5dbfc-8be8-11e6-9d26-b83fd23792f8.png)

/ui/Route-Provisioning_Least-Cost_Products_Full-View
![image](https://cloud.githubusercontent.com/assets/18315382/19170974/88b83d7a-8be8-11e6-9742-aa09b8789a19.png)

/ui/Route-Provisioning_Least-Cost_Products_Rates
![image](https://cloud.githubusercontent.com/assets/18315382/19170987/9bdfda16-8be8-11e6-8325-afdb162ff4cf.png)

**Comment by fenichelar** [comment]
@JimDalton @DmitryIsakbayev That is the data from NexOSS. Is this not correct

**Comment by DmitryIsakbayev** [comment]
Please test after upgrading to NexOSS 8.12.7
Explicitly send empty values for the summary views of Rates, Full Product View and Full Route Plan View

**Comment by JimDalton** [comment]
Fixed
