### ISSUE TITLE
No Details for Trigger Events

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#233]
#### Page Path

/ui/special/fileCDR/Traffic%20Pumping%20Fraud%20Events%20by%20UserId//201
/ui/special/fileCDR/Advanced%20Traffic%20Pumping%20Fraud%20Events%20by%20Source%20Device//201
/ui/special/fileCDR/Advanced%20Traffic%20Pumping%20Fraud%20Events%20by%20Calling%20Number//201
/ui/special/fileCDR/Advanced%20Traffic%20Pumping%20Fraud%20Events%20by%20GroupId//201
/ui/special/fileCDR/Advanced%20Traffic%20Pumping%20Fraud%20Events%20by%20Calling%20UserId//201
#### Description of Issue

Click and view CDRs and get a 404 Not Found
![image](https://cloud.githubusercontent.com/assets/18315382/19129828/bcc30d20-8b16-11e6-91a9-0d92d2ef47c2.png)

**Comment by DmitryIsakbayev** [comment]
There is a difference in the way Reports and Trigger events provide links to cdr details -
Report link includes page name with dir and file key/value pairs.
/analyzer/oss_ta_cdrs.htm?dir=2016-10-07-20161004145253-TFSS-ServiceProviderId-CallingGroupId-Code-Time.report.details%2FDay+2016-10-07+EDT%28-0400%29%2Fnone%2Fnone%2F1++++++++Canada%2FMinutes+15%3A00+-+%3A04&file=details.txt

Trigger event link includes just the dir value (the file name is always details.txt) and it is not URL encoded.
2016-10-06-20161004145253-PTFSS-Source-Source-Code-Time.report.details/Day 2016-10-06 EDT(-0400)/Customer-28/sipPclient-28/1        USA/Minutes 23:50 - :54
 
I will look into making the trigger event links look like the report links.

**Comment by DmitryIsakbayev** [comment]
The problem is for all products, not just SDReporter.  The solution is to use the new column 111 instead of 101.  The pages can be updated after upgrading to version 8.12.7 - Extended TriggerEvents to include link to CDR details in the same format used by reports (column 111 instead of 101)

**Comment by DmitryIsakbayev** [comment]
Updated the config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/01-By-Customer-Device/01-Traffic-Pumping/03-Trigger-Events.json page to use column 112 instead of 102, but something is still not right.

The link appears to look OK -
/analyzer/oss_ta_cdrs.htm?dir=2016-10-12-20161011181708-PTFSS-Source-Source-Code-Time.report.details%2FDay+2016-10-12+EDT%28-0400%29%2FCustomer-44%2FsipPclient-44%2F1++++++++USA%2FMinutes+08%3A40+-+%3A44&file=details.txt

The details page logs Error 404 Not Found, but I don't think it even tries to request the file.  I don't see a file request reaching NexOSS.

@fenichelar, please take a look.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Resolved. CDRs required a breadcrumb for the subtitle. It now supports no breadcrumb.

**Comment by fenichelar** [comment]
@JimDalton Please test.

**Comment by JimDalton** [comment]
@DmitryIsakbayev   Tested Page  /ui/Fraud-Control_CDR-Analytics-Basic_By-GroupId_Traffic-Pumping_Trigger-Events
Still cannot view CDRs.
/ui/special/fileCDR/Traffic%20Pumping%20Fraud%20Events%20by%20GroupId/201
We need this view for Exponetial-e's SDReporter implementation
![image](https://cloud.githubusercontent.com/assets/18315382/19400922/79046bda-9226-11e6-8ddc-6bbfdeb0bad6.png)

**Comment by DmitryIsakbayev** [comment]
So far only one file was updated to use the new format.  Updated the other 63 files for all products.
Please test.

**Comment by JimDalton** [comment]
@DmitryIsakbayev   This problem still exists.
Page tested: /ui/Fraud-Control_CDR-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Events

![image](https://cloud.githubusercontent.com/assets/18315382/19488119/8a0563de-9533-11e6-974d-a137f151c4a1.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton the changes were committed today and .101 did not have the latest changes.  It is now in sync.

**Comment by JimDalton** [comment]
Fixed
