### ISSUE TITLE
SDReporter Blacklisted Numbers Call Attempts trigger Threshold presented as NaN 

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#235]
#### Page Path
/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Called-Numbers_By-Calling-Number_Trigger-Thresholds

#### Description of Issue
I am expecting to see 0 for the number of call attempts to the Blacklisted Numbers.  Instead I see NaN.
![image](https://cloud.githubusercontent.com/assets/18315382/19131266/cfdbd12a-8b1c-11e6-806b-a25e2a28c8f0.png)

When I try to provision a trigger with 1 call attempt threshold, it is accepted, but is presented as NaN
![image](https://cloud.githubusercontent.com/assets/18315382/19131476/8feb0436-8b1d-11e6-8569-b1b0efb8ce2f.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton the page on .100 looks different.
![screensho](https://cloud.githubusercontent.com/assets/14879700/19132262/bdc005f2-8b20-11e6-8c62-89791a0102c6.png)

**Comment by JimDalton** [comment]
Your screenshot is from NexOSS.  You need to click on the Admin - Edit Interface and select SDReporter.  I think .101 and 100 have the same view for SDReporter.  I think this may be a case where we changed the json files for NexOSS after I created the SDReporter json file and we left the Excel speadsheet.
I will do some more trouble shooting and compare NexOSS and SDReporter at the same time.  That may be the most efficient way forward.

**Comment by JimDalton** [comment]
Comparison of NexOSS on .100 to SDReporter on .101

http://172.16.4.100:7080/ui/editor/05-Fraud-Control_03-CDR-Analytics-Basic_05-Blacklisted-Called-Numbers_02-By-Calling-Number_02-Trigger-Thresholds
paths.view = /analyzer/cgi-bin/data/viewReportTriggers.exe?forReportName=FraudBlacklistTriggerByCallingNumber
![image](https://cloud.githubusercontent.com/assets/18315382/19151361/3485afd8-8b9a-11e6-849c-6e2c653fb982.png)

http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Called-Numbers_By-Calling-Number_Trigger-Thresholds
/analyzer/cgi-bin/data/viewReportTriggers.exe?forReportName=FraudBlacklistTriggerByCallingNumber
![image](https://cloud.githubusercontent.com/assets/18315382/19151393/5d348724-8b9a-11e6-9435-ce94616acd26.png)

**Comment by JimDalton** [comment]
For comparison: similar issue on this page
http://172.16.4.100:7080/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Countries_By-Customer_Trigger-Thresholds
![image](https://cloud.githubusercontent.com/assets/18315382/19168000/1eaac8aa-8bdc-11e6-8d60-ab0f5ff767f8.png)

**Comment by DmitryIsakbayev** [comment]
Updated the following pages for OSS
NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/01-By-Customer/02-Trigger-Thresholds.json
NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/02-By-Calling-Number/02-Trigger-Thresholds.json
NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/03-By-Calling-UserId/02-Trigger-Thresholds.json
NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/06-Blacklisted-Countries/01-By-Customer/02-Trigger-Thresholds.json

**Comment by DmitryIsakbayev** [comment]
@JimDalton and @fenichelar I will fix the SDReporter pages after the columns are swapped.

**Comment by DmitryIsakbayev** [comment]
Updated SDReporter pages
modified:   config/pages/SDReporter/01-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/01-By-Source/02-Trigger-Thresholds.json
#	modified:   config/pages/SDReporter/01-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/02-By-Calling-Number/02-Trigger-Thresholds.json
#	modified:   config/pages/SDReporter/01-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/03-By-Calling-UserId/02-Trigger-Thresholds.json
#	modified:   config/pages/SDReporter/01-Fraud-Control/03-CDR-Analytics-Basic/06-Blacklisted-Countries/01-By-Source/02-Trigger-Thresholds.json

**Comment by JimDalton** [comment]
Fixed!
