### ISSUE TITLE
SDReporter OCI Commands by UserId missing

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#236]
#### Page Path
/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Called-Numbers_By-Calling-UserId_Broadsoft-Configuration

#### Description of Issue
No OCI commands are in the Broadsoft configuration.
![image](https://cloud.githubusercontent.com/assets/18315382/19132198/78600ec6-8b20-11e6-94de-507a73ea73a5.png)

**Comment by DmitryIsakbayev** [comment]
Typo in the column API - FraudBlackbooleanTriggerByCallingGroupId instead of FraudBlacklistTriggerByCallingGroupId.  FIxed for both OSS and SDReporter.

**Comment by JimDalton** [comment]
@DmitryIsakbayev   Thank you.  I think have noticed BlackBoolean in other api values.  I will look for them.  As a global rule, should I replace BlackBoolean with Blacklist?

**Comment by JimDalton** [comment]
@DmitryIsakbayev  Should api values shown below be edited from FraudBlackboolean to FraudBlacklisted?
/ui/editor/01-Fraud-Control_03-CDR-Analytics-Basic_Configuration_Reports

Col. 9 api = FraudBlackbooleanTriggerBySourceSource
Col. 10 api = FraudBlackbooleanTriggerByCallingNumber
Col. 11 api = FraudBlackbooleanTriggerByCallingGroupId
Col. 12 api = FraudBlackbooleanCountriesTriggerBySourceSource

**Comment by DmitryIsakbayev** [comment]
Yes.

**Comment by JimDalton** [comment]
Fixed

**Comment by DmitryIsakbayev** [comment]
Looks like the change was applied only to SDReporter, edited from FraudBlackboolean to FraudBlacklisted for NexOSS.
