### ISSUE TITLE
Need Review of SDReporter Trigger Events for Broadsoft by UserId

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#237]
#### Page Path
/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Called-Numbers_By-Calling-UserId_Broadsoft-Suspension-Events

#### Description of Issue
@DmitryIsakbayev   I need you help to review the Trigger Events page for BroadWorks by UserId.  UserId is entered twice as a Column Title and I do not know which is correct.
![image](https://cloud.githubusercontent.com/assets/18315382/19132474/9a10e314-8b21-11e6-8c1a-9370ec527a9a.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton The 2nd Calling User Id (Column 6) should be Calling Number.

**Comment by DmitryIsakbayev** [comment]
Changed title for column 6 to Calling Number and set its order to -1 for bot NexOSS and SDReporter.

**Comment by JimDalton** [comment]
Thank you
