### ISSUE TITLE
SDReporter - Cannot View Blacklisted Subnets

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#239]
#### Page Path
/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Countries_Configuration_Blacklisted-Subnets

#### Description of Issue
Bad Request message when trying to view Blacklisted subnets.
paths.view=/logs/cgi-bin/data/getLogFile.exe?dir=../../../WebServer/webapps/analyzer/WEB-INF/ETC&file={0} 

![image](https://cloud.githubusercontent.com/assets/18315382/19133003/306179b2-8b24-11e6-8b33-0803638db81f.png)

**Comment by DmitryIsakbayev** [comment]
Typos in the paths.view and download, replaced {0} with BlacklistedSubnets.etc
Updated pages for both NexOSS and SDReporter.

**Comment by JimDalton** [comment]
Fixed.
