### ISSUE TITLE
SDReporter & NexOSS - Time Data displayed in Dial Code columns

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#241]
#### Page Path
http://172.16.4.101:7080/ui/Fraud-Control_CDR-Analytics-Advanced_By-GroupId_Theft-of-Service_History-Report

Need help figuring out what is misconfigured on this page.  There is no data presented until drilling down to the Dial Code level - and then the data presented is hours, not Breakouts.

SDReporter paths.view = /applet/cgi-bin/data/viewReport.exe?appPrefix=Analyzer&appSubPrefix=&contextName=OSS-5-Customer-Duration-HFS-Report&contextResources=tree-report-viewer&includeHeaders=false&forReportFileName=PATHMASK&forKey=FILTERMASK&displayMinusOneAs=

NexOSS paths.view = /applet/cgi-bin/data/viewReport.exe?appPrefix=Analyzer&appSubPrefix=&contextName=OSS-5-Customer-Duration-HFS-Report&contextResources=tree-report-viewer&includeHeaders=false&forReportFileName=PATHMASK&forKey=FILTERMASK&displayMinusOneAs=

NexOSS has the same issue as SDReporter

#### Description of Issue
![image](https://cloud.githubusercontent.com/assets/18315382/19163591/9a3b1a0e-8bca-11e6-926d-14ce3f61b198.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton Theft Of Service reports do not include breakouts, only Traffic Pumping reports do.  I think the solution is to remove dial code from Column 4.

**Comment by JimDalton** [comment]
Fixed
