### ISSUE TITLE
Make Titles and search boxes bottom justified.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#242]
#### Page Path
/ui/QoS_Source-QoS_Summary_By-Source-and-Time

#### Description of Issue
When columnGroupTitles are used, the vertical alignment of search boxes above columns varies and looks odd.  Can you make column titles and search boxes bottom justified so they align on pages that have columnGroupTitles? 
![image](https://cloud.githubusercontent.com/assets/18315382/19170641/462efa6c-8be7-11e6-96a2-1e2b52e0aa24.png)

**Comment by fenichelar** [comment]
@JimDalton Done. Please test.

**Comment by JimDalton** [comment]
Looks good.
