### ISSUE TITLE
Need Broadsoft Suspensions for Advanced CDR Fraud Detection

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#249]
#### Description of Issue

We never implemented Broadsoft suspensions for Advanced CDR Fraud detection.
![image](https://cloud.githubusercontent.com/assets/18315382/19202103/c12c9438-8c9e-11e6-8f8f-e3b28e5dd625.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton triggers for Broadsoft need to be adjusted -

Suspension time does not apply.
Instead of suspend, the title should be "Send OCI-P command".
New UI
The server does not generate OSPrey suspensions for Broadsoft and can not reject redirect requests.
![screenshot2](https://cloud.githubusercontent.com/assets/14879700/19391135/37533784-91f9-11e6-8f8a-01efcfaf3ab4.png)

Old UI
![screenshot1](https://cloud.githubusercontent.com/assets/14879700/19391210/8ddcec26-91f9-11e6-9cad-65731c666a36.png)

**Comment by DmitryIsakbayev** [comment]
8 new pages for NexOSS
config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/03-By-GroupId/01-Traffic-Pumping/04-Broadsoft/Configuration.json 
config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/03-By-GroupId/01-Traffic-Pumping/04-Broadsoft/Suspension-Events.json
config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/03-By-GroupId/02-Theft-of-Service/04-Broadsoft/Configuration.json
config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/03-By-GroupId/02-Theft-of-Service/04-Broadsoft/Suspension-Events.json
config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/04-By-Calling-UserId/01-Traffic-Pumping/04-Broadsoft/Configuration.json
config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/04-By-Calling-UserId/01-Traffic-Pumping/04-Broadsoft/Suspension-Events.json
config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/04-By-Calling-UserId/02-Theft-of-Service/04-Broadsoft/Configuration.json
config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/04-By-Calling-UserId/02-Theft-of-Service/04-Broadsoft/Suspension-Events.json

**Comment by DmitryIsakbayev** [comment]
Copied configuration from NexOSS to SDReporter.
Please test after NexOSS in the lab is upgraded to 8.13.1

**Comment by JimDalton** [comment]
We decided to use our own fraud suspension rather than send OCI-P to BroadWorks.

**Comment by DmitryIsakbayev** [comment]
@JimDalton, when we spoke on the phone I thought you were referring to the SIP reports.
Looks like the changes I thought I added on Oct 14 were not actually committed.  I re-added pages for both NexOSS and SDReporter.

**Comment by JimDalton** [comment]
@DmitryIsakbayev   I was referring to SIP Analytics when we spoke on the phone and you reminded me that we decided not to use BroadWorks OCI-P for SIP Analytics.  However, I confused that conversation with this issue when I closed this issue.  Thank you for re-opening.  Please re-assign me when I can test the new pages.

**Comment by DmitryIsakbayev** [comment]
@jim, the pages are ready.  I checked them in yesterday.

**Comment by JimDalton** [comment]
@DmitryIsakbayev   I do not see the pages in the navigation on .32.  I did a sync this morning from my laptop GitHub repository could this have deleted the new pages?  Do I need to add the new page to the web config?

**Comment by DmitryIsakbayev** [comment]
@jim, the pages were added yesterday.  .32 is probably running an older release.  The pages exist on .100 and .101.

**Comment by JimDalton** [comment]
Thank you.
