### ISSUE TITLE
Cannot delete rejected currency exchange file

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#25]
#### Page Title
Rejected Currency Exchange Rate page

#### New URL
http://172.16.4.93:9080/ui2/Rate-Provisioning/Exchange-Rates/Rejected

#### Description of issue
Server error when trying to delete a .cxr file.
paths.deleteFile=/cgi-bin/action/rates/deleteRejected?file=PATHMASK
This file is successfully deleted from the legacy UI.
![image](https://cloud.githubusercontent.com/assets/18315382/15125344/59893f90-15fa-11e6-9936-ad5b25e5e3c5.png)

**Comment by fenichelar** [comment]
Please create some rejected files so that I can reproduce the error. Thank you.

**Comment by JimDalton** [comment]
A rejected currency file is in place cannot be deleted from the new UI.  A rejected can be deleted from the old UI. 
![image](https://cloud.githubusercontent.com/assets/18315382/16079745/1e758eae-32d3-11e6-8041-5eaa64149ec5.png)

**Comment by fenichelar** [comment]
Fixed.
