### ISSUE TITLE
Problems with QoS Report

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#251]
#### Page Path
/ui/QoS_Source-QoS_Details_By-Source-and-Time

#### Description of Issue
Search boxes missing, titles missing, need to change visible to false for some columns.
![image](https://cloud.githubusercontent.com/assets/18315382/19325221/1a79b9ce-9093-11e6-91f7-786bad91bfce.png)

**Comment by fenichelar** [comment]
@JimDalton Resolved. Please test.

**Comment by JimDalton** [comment]
Fixed

**Comment by JimDalton** [comment]
Fixed
