### ISSUE TITLE
Cannot view dropdown edit menu

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#252]
#### Page Path

The dropdown edit menu goes out of view on my screen.  Please see the screenshot below.
#### Description of Issue

![image](https://cloud.githubusercontent.com/assets/18315382/19325338/a747b018-9093-11e6-8504-15e9d4bd9aee.png)

**Comment by fenichelar** [comment]
@JimDalton Done. Please test.

**Comment by JimDalton** [comment]
@fenichelar 
I still have the same issue with the menu being off my screen.
![image](https://cloud.githubusercontent.com/assets/18315382/19487440/d3131042-9530-11e6-827d-e85ef889214b.png)

**Comment by fenichelar** [comment]
@DmitryIsakbayev Can you reproduce?

**Comment by DmitryIsakbayev** [comment]
No.

![screen](https://cloud.githubusercontent.com/assets/14879700/19648156/39466a9c-99cf-11e6-8462-33e8630d065c.png)

**Comment by fenichelar** [comment]
@JimDalton Please clear your browser cache and try again.

**Comment by JimDalton** [comment]
I cannot reproduce.
