### ISSUE TITLE
Change sorting of status

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#253]
#### Page Path

/ui/Server_Monitors_Triggers_Fraud-Analytics
Fraud Triggers page should sort with red on top, then yellow, then green.  Sort order is reversed.
#### Description of Issue

![image](https://cloud.githubusercontent.com/assets/18315382/19325444/2df06592-9094-11e6-92bf-9a5aa87a95e0.png)

**Comment by fenichelar** [comment]
@DmitryIsakbayev Can you swap the order for color sorting?

**Comment by DmitryIsakbayev** [comment]
@fenichelar are you saying that the ascending sort for colors should be
red,yellow, green, gray, white
instead of
white,gray,green,yellow,red

**Comment by fenichelar** [comment]
@DmitryIsakbayev Yes, that would be ideal. Data is sorted ascending by default.

**Comment by DmitryIsakbayev** [comment]
Implemented in NexOSS 8.12.3.
Please test after the lab is upgraded.

**Comment by JimDalton** [comment]
@DmitryIsakbayev   The lab is running NexOSS 8.13.1.  The problem still exists,  What version of NexOSS will fix this issue?
![image](https://cloud.githubusercontent.com/assets/18315382/19487386/94aad164-9530-11e6-94e1-9155022fee0a.png)

**Comment by DmitryIsakbayev** [comment]
Sorry, I meant NexOSS 8.13.3

**Comment by JimDalton** [comment]
The Process Monitor on the dashboard shows red when grey status exists.  This false positive for a problem will be annoying for users.  
Please implement the following dashboard monitor rules:
1) Display red if any red status exists
2) Display yellow is any status is yellow and no status is red
3) Display green if no red or yellow exists and at least 1 green status exists
4) Display gray if no red, yellow or green status exists.

![image](https://cloud.githubusercontent.com/assets/18315382/20435023/70a3664a-ad78-11e6-87a9-0893f96e57f4.png)

![image](https://cloud.githubusercontent.com/assets/18315382/20435039/7d50aca4-ad78-11e6-96cf-664222afa775.png)

**Comment by DmitryIsakbayev** [comment]
Strange.  The lab shows green while there is one process with gray status and errors.

![1](https://cloud.githubusercontent.com/assets/14879700/20435619/c52ba504-ad7a-11e6-88ff-12473fbfc06c.png)

![2](https://cloud.githubusercontent.com/assets/14879700/20435627/cab39932-ad7a-11e6-93ee-bccdf19e8b78.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton I think it is because there is one process that has Errors.
![1](https://cloud.githubusercontent.com/assets/14879700/20489077/58fd7f60-afd7-11e6-84c1-8353ca560966.png)

**Comment by DmitryIsakbayev** [comment]
Please retest.

**Comment by JimDalton** [comment]
Fixed
