### ISSUE TITLE
Chart Title is undefined

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#255]
#### Page Path
Page: /ui/Fraud-Control_CDR-Analytics-Advanced_By-GroupId_Traffic-Pumping_Trigger-Report
Chart: /ui/special/fraudAdvChart/undefined/detailLevel%3D4%26file%3D2016-10-14-20161014125702-PTFSS-ServiceProviderId-CallingGroupId-Code-Time.report%26reportSearchKey%3D.*%3Anone%3Anone%3A1%2B%2B%2B%2B%2B%2B%2B%2BCanada%3A.*%26dataSet%3DcallAttemptsScore%26day%3DDay%2B2016-10-14%2BEDT%2528-0400%2529%26account%3Dnone%26device%3Dnone%26breakout%3D1%2B%2B%2B%2B%2B%2B%2B%2BCanada/detailLevel%3D4%26file%3D2016-10-14-20161014125702-PTFSS-ServiceProviderId-CallingGroupId-Code-Time.report%26reportSearchKey%3D.*%3Anone%3Anone%3A1%2B%2B%2B%2B%2B%2B%2B%2BCanada%3A.*%26dataSet%3DcallAttemptsScore%26day%3DDay%2B2016-10-14%2BEDT%2528-0400%2529%26account%3Dnone%26device%3Dnone%26breakout%3D1%2B%2B%2B%2B%2B%2B%2B%2BCanada
#### Description of Issue
![image](https://cloud.githubusercontent.com/assets/18315382/19401139/9d28d7f2-9227-11e6-9d1b-5f0f4c13ff58.png)

**Comment by fenichelar** [comment]
@JimDalton Fixed. Please test.

**Comment by JimDalton** [comment]
Fixed
