### ISSUE TITLE
No Dropdown Box Options

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#257]
#### Page Path
/ui/Traffic-Analyzer_Triggers_By-Provider_By-Device-and-Dial-Code_Thresholds

#### Description of Issue
@fenichelar Cannot create a new trigger.  No response from the provider dropdown menu in the modal.
![image](https://cloud.githubusercontent.com/assets/18315382/19445943/6fde16b0-9464-11e6-8639-cb606b87ce0f.png)

**Comment by fenichelar** [comment]
@JimDalton This appears to be an issue on all pages. Investigating.

**Comment by fenichelar** [comment]
@JimDalton Resolved. Please test.

**Comment by JimDalton** [comment]
Fixed
