### ISSUE TITLE
Check for bug in Call Completion by Provider Trigger Events

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#258]
#### Page Path

Old UI: /analyzer/oss_ta_ccd_trigger_events_6.htm
#### Description of Issue

Arkadin, using NexOSS V8.9.6, Trigger Events by provider to not make sense. Call Success ratio exceeds 100%.
![image](https://cloud.githubusercontent.com/assets/18315382/19446112/450110b8-9465-11e6-8864-5320da107612.png)

**Comment by DmitryIsakbayev** [comment]
This problem does not seem to exist in the current release -
![1](https://cloud.githubusercontent.com/assets/14879700/19452018/47aa23a0-947d-11e6-8e84-1231a23b31ec.png)

**Comment by JimDalton** [comment]
Cannot replicate.
