### ISSUE TITLE
Hide Copy button?

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#26]
#### Description of issue
I have been testing the Copy button.  For our use cases, I cannot find any difference between the Copy and Update buttons.  Perhaps I am overlooking something.  If not, then I think  it makes sense to hide the Copy button.  More choices confuse users.

**Comment by fenichelar** [comment]
Copy is the same thing as Add except one small difference. When you click Add, all of the fields in the form are filled with their default value. When you click Copy, all of the fields in the form are filled with the value of the currently selected item. This is designed to make creating multiple entries that are almost exactly the same faster. The Copy button is only shown if the Add button is shown. Would you still like it removed? Or renamed to "Duplicate" or something else that is more clear?

**Comment by JimDalton** [comment]
Hmm...  Thank you for elaboration.  I need to mull this over.
