### ISSUE TITLE
Add page to enable/disable Registration reports

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#261]
#### Description of Issue
Create config page for registration reports
Api is the same as other report config files
Need Key names?

**Comment by DmitryIsakbayev** [comment]
Key names:
FraudRegisterTriggerByCallingSourceAgent
FraudRegisterTriggerByCountryCallingAgentSource
FraudRegisterTriggerByAgentCallingSource
FraudRegisterTriggerBySourceCallingAgent
FraudRegisterTriggerByCalling
FraudRegisterTriggerByCountry
FraudRegisterTriggerBySource

**Comment by JimDalton** [comment]
Done
