### ISSUE TITLE
Add Customization Notes

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#262]
#### Description of Issue

Multi-Column page as a template
Paths.view?
Paths.add?
paths.download is same as paths.view
page type = table-viewer

Phase 1:  Create Config File when Dmitry provides paths.
Four columns: 
Column 1 = Date
Column 2 = Who added the entry
Column 3 = Title for the note 
Column 4 = Detailed description with line breaks, Column Type = text.  (line breaks not supported)

Phase 2: Need new column type = markdown.  This is Di-Shi's challenge

**Comment by DmitryIsakbayev** [comment]
This page is similar to /ui/Accounts_Subscribers

paths.view `/analyzer/cgi-bin/data/viewMultiColumnConfig.exe?setKey=CustomizationNotes`
paths.add `/analyzer/cgi-bin/action/addMultiColumnConfig.exe?setKey=CustomizationNotes&columnNumber=4`

Column API:
column0
column1
column2
column3

The primary key is based on column0, the Dates must be unique for each entry.

**Comment by di-shi** [comment]
When I tested it with multiple lines, 2 lines, description, the add part looked fine, but view part returned 2 rows instead of 1.
[customnote.txt](https://github.com/TransNexus/NexOSS/files/594819/customnote.txt)

**Comment by DmitryIsakbayev** [comment]
The request comes in url encoded -
`/analyzer/cgi-bin/action/addMultiColumnConfig.exe?setKey=CustomizationNotes&columnNumber=4&undefined=&column0=2016-11-16&column1=ossadmin&column2=test-X&column3=test-X%20line%201.%0Atext-X%20line%202`

By the time the servlet receives extracts the key/value pairs, they are already decoded -
`[2016-11-16, ossadmin, test-X, test-X line 1.
text-X line 2.]`

Sounds like the server should explicitly encode the line before saving it to file.

**Comment by DmitryIsakbayev** [comment]
@di-shi please try with rel-c6-64

**Comment by di-shi** [comment]
@DmitryIsakbayev It works for the line part. I will handle the decode part for the returned text.

**Comment by di-shi** [comment]
textarea is used to edit the description column, and markdown is used to display it.
