### ISSUE TITLE
New special CDR Details page for Registration Messages

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#264]
#### Description of Issue

@fenichelar   We create CDRs for Registration messages.  It is convenient, but fields in Registration messages do not map exactly to CDRs.  So when the details are viewed, there are column titles that do not make sense.  Edit registrationCDR page
![image](https://cloud.githubusercontent.com/assets/18315382/19539436/63764bbc-9627-11e6-87ae-9afce4c24fb1.png)

**Comment by di-shi** [comment]
Done.
