### ISSUE TITLE
Add mapping widget

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#267]
- [x] Country maps
- [x] State maps

**Comment by fenichelar** [comment]
Done.

**Comment by DmitryIsakbayev** [comment]
Data feed BySourceCountry from reports -
MC-SourceCountry-Day (NexOSS)
MQC-SourceCountry-Day (NexOSS-FC)

Requires NexOSS after v.8.24.0

**Comment by DmitryIsakbayev** [comment]
Data feed ByCalledCountry from reports -
MC-CalledCountry-Day (NexOSS)
MQC-CalledCountry-Day (NexOSS-FC)

Requires NexOSS after v.8.24.0

**Comment by DmitryIsakbayev** [comment]
Sample
paths.list `/logs/cgi-bin/data/listLogFiles.exe?dir=../../../REPORTS&lastFileFirst=false&fileMask=.*MC-CalledCountry.*`
paths.view `/analyzer/cgi-bin/action/reportToChart.exe?detailLevel=1&reportSearchKey=.*&dataSet=map&file=PATHMASK`

**Comment by DmitryIsakbayev** [comment]
@JimDalton and @fenichelar 

What should the default country code be when we don't have a match for the called number or the IP address?  Right now it is `_All Other_`

What should the country code be for the private IP addresses?  Right now it is `Private`

**Comment by JimDalton** [comment]
_All Other_ and Private make sense to me
For maps display, I think we ignore calls that cannot be mapped to a country code.
@fenichelar   What value does the Widget code need to ignore data than cannot be mapped?  Can it use _All Other_ and Private?

**Comment by fenichelar** [comment]
@DmitryIsakbayev 

`other`
`private`

Would be ideal.

**Comment by DmitryIsakbayev** [comment]
Will change in the next release (after 8.25)

**Comment by fenichelar** [comment]
@DmitryIsakbayev I have added the widgets but not updated the paths and columns config. Is the path `/analyzer/cgi-bin/action/reportToChart.exe?detailLevel=1&reportSearchKey=.*&dataSet=map&file=PATHMASK` for By Destination or By Source widgets?

**Comment by DmitryIsakbayev** [comment]
paths.view is the same, but paths.list are different.

Here is a template paths.list `/logs/cgi-bin/data/listLogFiles.exe?dir=../../../REPORTS&lastFileFirst=false&fileMask=.*-MC-CalledCountry.*`

Replace the `-MC-CalledCountry` according to the use case -
By Source Country
`-MC-SourceCountry-Day`     (CDRs)
`-MQC-SourceCountry-Day`  (SIP)
By Called Country
`-MC-CalledCountry-Day` (CDRs)
`-MQC-CalledCountry-Day` (SIP)

**Comment by fenichelar** [comment]
@DmitryIsakbayev @JimDalton Widgets updated. Please check data.

**Comment by fenichelar** [comment]
@JimDalton No maps are currently part of the default dashboard. Please let me know if you want the default dashboard changed.
