### ISSUE TITLE
Add comma as thousands separator for number format.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#27]

**Comment by fenichelar** [comment]
This is extremely easy however I need to know when to do it. Should I do it for every column with the type "number"? If not, we might need to add another column in the Excel file.

**Comment by JimDalton** [comment]
I cannot think of a use case when adding a thousands comma separator would not be appropriate.  Please make that the default for type=number.  If we discover we need to add a column to the Excel file in the future for a new use case - I will do it.

**Comment by fenichelar** [comment]
Done.
