### ISSUE TITLE
Cannot View CDRs on SDReporter

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#271]
#### Description of Issue

Gave a demo to Exponential-e.  Could not view CDRs.  Not a problem on SDReporter at BroadRiver.  Same version of SDReporter on both servers.  However UI for BroadRiver was built on Oct 26th.  Expoential-e UI was built on Oct 27th.
![image](https://cloud.githubusercontent.com/assets/18315382/19776721/3fa08776-9c43-11e6-8173-cd9340b6402b.png)

**Comment by fenichelar** [comment]
Caused by the plus symbol. Resolved by double encoding the symbol. Please test.

**Comment by JimDalton** [comment]
Works on .25!
