### ISSUE TITLE
Post Dial Delay (PDD) Widget displays -1 when PDD not Available

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#272]
#### Description of Issue

BroadWorks CDRs do not report Post Dial Delay (PDD).  PDD value is NA in reports.  In the Widget, PDD is displayed as -1.  This is confusing.  It would be better if there was no PDD trace in the chart.  Or even, better, the works Post Dial Delay = NA.
![image](https://cloud.githubusercontent.com/assets/18315382/19777040/6f9888ba-9c44-11e6-95e7-db2b833e1f70.png)

**Comment by fenichelar** [comment]
Putting this on the back burner for now. Please let me know if you wish to implement this. It will take some planning.

**Comment by JimDalton** [comment]
This is a low priority, enhancement

**Comment by fenichelar** [comment]
@DmitryIsakbayev Would you be able to handle this? Don't record/return -1 but blank.

**Comment by DmitryIsakbayev** [comment]
The server supports searchFor/replaceWith parameters.  We can try `searchFor=-1&replaceWith=`

**Comment by fenichelar** [comment]
Fixed by adding `&searchFor=-1.0&replaceWith=undefined`
