### ISSUE TITLE
Widget X-Axis - Editing time stamp values

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#274]
#### Description of Issue

What is the best way to edit time stamps on the X-Axis in widgets?  Change the data or the widget.  For current Widgets hh:mm would be better that yyyy-mm-dd hh:mm:ss.  Let's discuss on Friday.
![image](https://cloud.githubusercontent.com/assets/18315382/19777299/8d1caa96-9c45-11e6-9003-62893f24da12.png)

**Comment by DmitryIsakbayev** [comment]
Let's add timeStampFormat=HH:mm parameter to the reportToChart API

**Comment by DmitryIsakbayev** [comment]
Updated, please test

	modified:   config/widgets/NexOSS-FC/Other/CallStatistics.json
	modified:   config/widgets/NexOSS/Other/CallDurations.json
	modified:   config/widgets/NexOSS/Other/CallStatistics.json
	modified:   config/widgets/NexOSS/Other/ConcurrentCalls.json
	modified:   config/widgets/NexOSS/Other/PDDStatistics.json
	modified:   config/widgets/SDReporter/Other/CallDurations.json
	modified:   config/widgets/SDReporter/Other/CallStatistics.json
	modified:   config/widgets/SDReporter/Other/ConcurrentCalls.json
	modified:   config/widgets/SDReporter/Other/PDDStatistics.json

**Comment by JimDalton** [comment]
Looks Good - Thank you
