### ISSUE TITLE
SIP Analytics Reports Configuration - Cannot Enable Reports by Blacklisted Numbers

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#276]
#### Page Path
/ui/Fraud-Control_SIP-Analytics-Basic_Configuration_Reports

#### Description of Issue
Changes made to Check boxes, to enable Blacklisted reports do persist after hitting the submit button and going to a different page. Navigate away and return and the Check boxes for Blacklisted Reports are always unchecked.  It is like the following APIs do not work.   Change Boolean value to have default of true, but this do not change anything.
FraudQueryBlacklistedUserAgentsTriggerBySourceSource
FraudQueryBlacklistedUserAgentsTriggerByCallingNumber
FraudQueryBlacklistedTriggerBySourceSource
FraudQueryBlacklistedTriggerByCallingNumber
FraudQueryBlacklistedCountriesTriggerBySourceSource

![image](https://cloud.githubusercontent.com/assets/18315382/19902958/29fa77c0-a043-11e6-9c37-7c9b78572ea4.png)

**Comment by DmitryIsakbayev** [comment]
Typos in API for blacklist reports - should be Blacklist instead of Blacklisted.
Please test.

**Comment by JimDalton** [comment]
Fixed.
