### ISSUE TITLE
Provider Accounts show up in Customer Dropdown list

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#277]
#### Page Path
Fraud-Control_SIP-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Thresholds

#### Description of Issue
ATT is a Provider Only Account.  But, when adding a fraud trigger by customer, ATT is included in the Customer Account dropdown.
![image](https://cloud.githubusercontent.com/assets/18315382/19905777/88bb0698-a04e-11e6-994c-71adeb1fee3d.png)

**Comment by DmitryIsakbayev** [comment]
The dropdownUrl for customers was missing `customerType=.*Orig.*`
The full url should be `/cgi-bin/data/grpdata2.exe?type=customer&customerType=.*Orig.*&addChoices=Wild%20Card`

Please test

**Comment by JimDalton** [comment]
Fixed
