### ISSUE TITLE
Widget - Gross Profit

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#279]
The widget could request this information from the /ui/Billing_Profit-Reports_By-Customer report
Configuration could be similar to the "Call Duration" widget.

The paths.list will request the list of current reports and will use the top (most recent one)
`/analyzer/billing/cgi-bin/data/listReportFiles.exe?dir=../../../FREPORTS&lastFileFirst=false&fileMask=.*BillingBy-Customer-Code.*`

The paths.view will request the first (summary) row of the report
`/applet/cgi-bin/data/viewReport.exe?appPrefix=Analyzer&appSubPrefix=&contextName=OSS-BillingReport1-Billing-Customer-Report&contextResources=tree-report-viewer&includeHeaders=false&forReportFileName=PATHMASK&forKey=&displayMinusOneAs=`

Column API (Ignore everything except the target data like Orig Fee, Term Fee and Gross Profit)
level
children
key
titles
Call Attempts
Call Success Ratio
Completed Calls
Avg Call Duration
Total Duration
Post Dial Delay
Orig Fee
Term Fee
Gross Profit
Profit Margin

**Comment by di-shi** [comment]
question, where should it be, right of concurrent calls or under pdd?

**Comment by di-shi** [comment]
Done.
