### ISSUE TITLE
Number Translation URL for Customer Account Dropdown

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#28]
#### Description of issue
The URL is: /analyzer/cgi-bin/data/viewChoices.exe?setKey=SourceGroups
Is this correct? It returns a lot of data. It is actually crashing the pages.

**Comment by DmitryIsakbayev** [comment]
The URL for getting all Customer (Originating) accounts is
/cgi-bin/data/grpdata2.exe?type=customer&customerType=.*Orig.*

all Provider (Terminating) accounts is
/cgi-bin/data/grpdata2.exe?type=customer&customerType=.*Term.*

**Comment by fenichelar** [comment]
@JimDalton, please change these in the Excel file when you get a chance.
