### ISSUE TITLE
Widget - Top Customers

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#281]
Similar to Widget - Gross Profit #279
Instead of requesting the top row, we want to skip the top row (instead of searchKey= use skipTopLevel=true) and get one row per customer.  We also want to sort the data by OrigFee in descending order (tokenDelimiter=%09&sortBy=10&sortOrder=desc&sortType=number)

Not sure yet how to generate the "All Other" and "Total" rows.

paths.list same as #129 

paths.view
`/applet/cgi-bin/data/viewReport.exe?appPrefix=Analyzer&appSubPrefix=&contextName=OSS-BillingReport1-Billing-Customer-Report&contextResources=tree-report-viewer&includeHeaders=false&forReportFileName=PATHMASK&skipTopLevel=true&displayMinusOneAs=&tokenDelimiter=%09&sortBy=10&sortOrder=desc&sortType=number`

Column API same #129

**Comment by di-shi** [comment]
@DmitryIsakbayev 
do you mean #279 instead of #129?

**Comment by DmitryIsakbayev** [comment]
@di-shi, yes -  #279

**Comment by di-shi** [comment]
I see. Done.
