### ISSUE TITLE
Cannot View Basic SIP Analytics Trigger Reports

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#282]
#### Page Path
/ui/Fraud-Control_SIP-Analytics-Basic_By-GroupId_Theft-of-Service_Trigger-Report

#### Description of Issue
Internal Server Error  when trying to view an Basic SIP Analytics Trigger Report.
No problem viewing Advanced SIP Analytics Trigger reports or Basic and Advanced CDR Trigger Reports.
![image](https://cloud.githubusercontent.com/assets/18315382/20109584/b617b5ae-a5ae-11e6-89b0-84c26b2b73a7.png)

**Comment by DmitryIsakbayev** [comment]
Looks like I broke it while implementing Subscriber reports in 8.15.3.  NexOSS 8.16.1 should fix it.
Please test after the lab is upgraded.

**Comment by JimDalton** [comment]
Fixed
