### ISSUE TITLE
Widget - Top Providers

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#284]
Similar to #281, but will use BillingBy-Provider instead of BillingBy-Customer report and sort by TermFee (column 11) instead of OrigFee (column 10)

paths.list
`/analyzer/billing/cgi-bin/data/listReportFiles.exe?dir=../../../FREPORTS&lastFileFirst=false&fileMask=.*BillingBy-Provider-Code.*`

paths.view
`/applet/cgi-bin/data/viewReport.exe?appPrefix=Analyzer&appSubPrefix=&contextName=OSS-BillingReport2-Billing-Provider-Report&contextResources=tree-report-viewer&includeHeaders=false&forReportFileName=PATHMASK&skipTopLevel=true&displayMinusOneAs=&tokenDelimiter=%09&sortBy=11&sortOrder=desc&sortType=number`

**Comment by di-shi** [comment]
Done.
