### ISSUE TITLE
Widget - Customer minutes

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#285]
Based on /ui/Traffic-Analyzer_Call-Completion_By-Customer_By-Time-and-Dial-Code report sort by Total Minutes (column 11)

paths.list
`/analyzer/cgi-bin/data/listReportFiles.exe?dir=../../../FREPORTS&lastFileFirst=false&fileMask=.*-CCS-Time-Code-Source.*`

paths.view
`/applet/cgi-bin/data/viewReport.exe?appPrefix=Analyzer&appSubPrefix=&contextName=OSS-1-Customer-CC-Report&contextResources=tree-report-viewer&includeHeaders=false&forReportFileName=PATHMASK&skipTopLevel=true&displayMinusOneAs=&tokenDelimiter=%09&sortBy=11&sortOrder=desc&sortType=number&offset=0&limit=100`

Column API
As configured for the /ui/Traffic-Analyzer_Call-Completion_By-Customer_By-Time-and-Dial-Code pages.

**Comment by di-shi** [comment]
Done.
