### ISSUE TITLE
New Fraud Query reports by ServiceProvder and CallingGroup

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#288]
A number of problems after initial implementation.

**Comment by DmitryIsakbayev** [comment]
Fixed CDR link and added Calls Blocked column in 
03-By-GroupId/01-Traffic-Pumping/01-Trigger-Report.json
03-By-GroupId/02-Theft-of-Service/01-Trigger-Report.json
04-By-UserId/01-Traffic-Pumping/01-Trigger-Report.json
04-By-UserId/02-Theft-of-Service/01-Trigger-Report.json

**Comment by DmitryIsakbayev** [comment]
Added column for blocked calls.  In order to properly configure links to charts split context names for TheftOfServiceReports.  Requires NexOSS 8.16.3.  Updated files:
03-By-GroupId/01-Traffic-Pumping/01-Trigger-Report.json
03-By-GroupId/02-Theft-of-Service/01-Trigger-Report.json
04-By-Calling-UserId/01-Traffic-Pumping/01-Trigger-Report.json
04-By-Calling-UserId/02-Theft-of-Service/01-Trigger-Report.json

**Comment by DmitryIsakbayev** [comment]
In order to properly configure historic reports, split context names for TheftOfServiceReports. Requires NexOSS 8.16.3. Updated files:
03-By-GroupId/02-Theft-of-Service/02-History-Report.json  
04-By-Calling-UserId/02-Theft-of-Service/02-History-Report.json

**Comment by DmitryIsakbayev** [comment]
Please test.

**Comment by JimDalton** [comment]
Completed!
