### ISSUE TITLE
SIP Analytics Triggers are not activated

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#289]
#### Page Path
/ui/Fraud-Control_SIP-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Events

#### Description of Issue
Fraud scores in trigger report exceed Fraud trigger threshold, but no trigger is activated.  No event logged.

**Comment by DmitryIsakbayev** [comment]
Looks like a Regression Bug (introduced in 8.16.0).  Should be fixed in 8.16.4

**Comment by DmitryIsakbayev** [comment]
The lab has been upgraded to 8.16.4 and trigger events are being generated.
