### ISSUE TITLE
Add Custom Black/White List for Subnets

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#290]

**Comment by DmitryIsakbayev** [comment]
Added two pages, they require NexOSS 8.17.0
config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/07-Blacklisted-Countries/02-Configuration/Custom-Blacklisted-Subnets.json
config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/06-Blacklisted-Countries/Configuration/Custom-Blacklisted-Subnets.json

**Comment by DmitryIsakbayev** [comment]
Please test.

**Comment by JimDalton** [comment]
When I try to add a Custom Blacklisted Subnet, I get the error below: No Response from API server.
Question: what is the proper syntax to provision a subnet?  Is it a range (1.1.1.1-1.1.1.24) or a submask (1.1.1.1\31) or something else?
![image](https://cloud.githubusercontent.com/assets/18315382/20765423/3bcf66c6-b700-11e6-933a-e544ebfcec5d.png)

**Comment by DmitryIsakbayev** [comment]
The format is 1.1.1.1\31
The server logged 
Sending Error 580:Failed to split subnet 1.1.1.1 into its ip part and length part

**Comment by JimDalton** [comment]
@DmitryIsakbayev   Tried to provision 1.1.1.1\31, but got the same error.  Failed to split subnet 1.1.1.1\31 into its ip part and length part
![image](https://cloud.githubusercontent.com/assets/18315382/20797843/99e8ee62-b7aa-11e6-9356-8624b36be1c4.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton, I am sorry.  It is the other slash - 1.1.1.1/31  The format is similar to
/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Countries_Configuration_Blacklisted-Subnets

**Comment by DmitryIsakbayev** [comment]
For some reason the column type for subnet is set to 'subnetIPaddress'.  I think it is intended for the /ui/Accounts_Subnets page.

'subnetIPaddress' - And IPv4 address that also displays the calculated subnet range based on a bit mask.

In this case, the subnets are in x.x.x.x/y format.  Where "x.x.x.x" is an IP address and "y" is the bit mask length between 1 and 32.  I think we need to set the type to "text" and have a special validation rule.

**Comment by di-shi** [comment]
@DmitryIsakbayev I am confused. What do you want me to do? Add a new column type or a new validation rule?

**Comment by DmitryIsakbayev** [comment]
@di-shi, I think it would be a validation rule.

**Comment by di-shi** [comment]
done.

**Comment by DmitryIsakbayev** [comment]
Works as expected.  Thank You.

For the subnets column, changed type to text and set validation to IPrange.  Also updated description of the subnet format.  Updated the following 4 pages:

config/pages/NexOSS-FC/05-Fraud-Control/01-SIP-Analytics-Basic/07-Blacklisted-Countries/02-Configuration/Custom-Blacklisted-Subnets.json

config/pages/NexOSS-FC/05-Fraud-Control/03-CDR-Analytics-Basic/06-Blacklisted-Countries/Configuration/Custom-Blacklisted-Subnets.json

config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/07-Blacklisted-Countries/02-Configuration/Custom-Blacklisted-Subnets.json

config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/06-Blacklisted-Countries/Configuration/Custom-Blacklisted-Subnets.json

**Comment by JimDalton** [comment]
Works as expected.
