### ISSUE TITLE
/special/fileCDR does not preserve the path when redirects to /login

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#291]
@fenichelar  If you try to use a bookmark to a regular page such as Accounts_Accounts and you are not yet logged in, you are redirected to /login?redirect=Accounts_Accounts.  After logging in, you see the Accounts_Accounts page right away.

If you try to use a bookmark to /special/fileCDR (followed by a long list of variables), you are simply redirected to /login  After logging in, you see the default dashboard page.

The use case for the bookmark to the /special/fileCDR page is to include a link to CDR details in trigger alerts emails.  Here is a sample bookmark -
`http://172.16.4.32:7080/ui/special/fileCDR/Traffic%20Pumping%20Fraud%20Events%20by%20Customer%20Device/2016-11-17-20161115173338-TFQSS-Source-Source-Code-Time.report.details%252FDay%2B2016-11-17%2BEST%2528-0500%2529%252FCustomer-17%252FsipPclient-17%252F1%2B%2B%2B%2B%2B%2B%2B%2BUSA%252FMinutes%2B00%253A00%2B-%2B%253A04/2016-11-17-20161115173338-TFQSS-Source-Source-Code-Time.report.details%25252FDay%252B2016-11-17%252BEST%252528-0500%252529%25252FCustomer-17%25252FsipPclient-17%25252F1%252B%252B%252B%252B%252B%252B%252B%252BUSA%25252FMinutes%252B00%25253A00%252B-%252B%25253A04`

**Comment by fenichelar** [comment]
@DmitryIsakbayev Done. Added support for automatic subtitle. Routes:

`/special/:type/:mainTitle/:subTitle/:key`
`/special/:type/:mainTitle/:key` `subTitle` is set to `key`

**Comment by DmitryIsakbayev** [comment]
Please test bookmark to cdr details in trigger alert emails.

**Comment by JimDalton** [comment]
@DmitryIsakbayev I cut and pasted the url http://172.16.4.32:7080/ui/special/fileCDR/Traffic%20Pumping%20Fraud%20Events%20by%20Customer%20Device/2016-11-17-20161115173338-TFQSS-Source-Source-Code-Time.report.details%252FDay%2B2016-11-17%2BEST%2528-0500%2529%252FCustomer-17%252FsipPclient-17%252F1%2B%2B%2B%2B%2B%2B%2B%2BUSA%252FMinutes%2B00%253A00%2B-%2B%253A04/2016-11-17-20161115173338-TFQSS-Source-Source-Code-Time.report.details%25252FDay%252B2016-11-17%252BEST%252528-0500%252529%25252FCustomer-17%25252FsipPclient-17%25252F1%252B%252B%252B%252B%252B%252B%252B%252BUSA%25252FMinutes%252B00%25253A00%252B-%252B%25253A04 into Chrome.  The sccreenshot below is what I see.  Is this what you are expecting?

![image](https://cloud.githubusercontent.com/assets/18315382/20764255/6697f1c0-b6fb-11e6-8a58-c762825cf486.png)

**Comment by DmitryIsakbayev** [comment]
It seems to work.  The important part is to do it while not being logged in.  You should first be redirected to the log-in page and then to the cdr details page.

**Comment by JimDalton** [comment]
Checked using Microsoft Edge.  I was not logged in.  It worked as you describe.

**Comment by DmitryIsakbayev** [comment]
I think it is broken again.  The browser redirects to http://172.16.4.32:7080/ui/login?redirect=special_fileCDR without any query parameters fro the special_fileCDR page.

Click on the link to test -
http://172.16.4.32:7080/ui/special/fileCDR/Blacklist%2520Fraud%2520By%2520Calling%2520GroupId%2520%2526%2520UserId/2017-02-23-20170221155953-TFB-CallingGroup-Id-Time.report.details%252FDay%25202017-02-23%2520EST%2528-0500%2529%252F1900%252FGroupId_for_19899962003%252FUserID_for_19899962003%252FMinutes%252015%253A25%2520-%2520%253A29/2017-02-23-20170221155953-TFB-CallingGroup-Id-Time.report.details%252FDay%25202017-02-23%2520EST%2528-0500%2529%252F1900%252FGroupId_for_19899962003%252FUserID_for_19899962003%252FMinutes%252015%253A25%2520-%2520%253A29
