### ISSUE TITLE
need a validation rule for multiple line text, such as customization notes.

### ISSUE THREAD

**Issue by di-shi** [TransNexus/NexOSS#292]
the "required" validation rule does not allow \r and \n. for multiple line text, we should either weaken this rule or make a new rule.

**Comment by fenichelar** [comment]
`requiredAllowNewLine` and `optionalAllowNewLine` added. Allows `\n` but not `\r`.

**Comment by di-shi** [comment]
We only input from GUI using keyboard, \n should be fine. In fact, even copy/paste \r into editor window, it still works.

**Comment by di-shi** [comment]
works fine.
