### ISSUE TITLE
Cannot search table using the + sign

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#293]
#### Page Path
/ui/Fraud-Control_CDR-Analytics-Basic_Configuration_Breakout-Codes_Templates_By-Country-Code

#### Description of Issue
No results found when a + is entered in the search box for a column full of telephone numbers.
![image](https://cloud.githubusercontent.com/assets/18315382/20407199/50ade2f6-acde-11e6-9a2f-121bb2d3e68b.png)

**Comment by DmitryIsakbayev** [comment]
It is our old friend the plus sign.

The request to NexOSS is
`/analyzer/cgi-bin/data/getReportFile.exe?dir=WEB-INF/ETC/&file=BreakoutCodes_for_E164_by_CC.txt&tokenDelimiter=%09&searchString=+&excludeColumns=&filterString0=+&filterType0=startsWith&sortBy=1&sortOrder=asc&sortType=text&offset=0&limit=100`

But by the time the servlet looks at the filterString0 it looks like a space.

Sails should encode the filterString.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Yay.......

**Comment by di-shi** [comment]
After encoding filterString value, plus sign works. But I am thinking about to encode the whole URI parameter string once instead of to encode selected parameters one by one. We may have to debug/patch for other URI items.

**Comment by JimDalton** [comment]
Fixed!
