### ISSUE TITLE
canNotSeeOnAdd and canNotSeeOnUpdate flags added

### ISSUE THREAD

**Issue by di-shi** [TransNexus/NexOSS#295]
@JimDalton One thing must be mentioned, canNotSeeOnAdd flag does not work with any "required" validation rule. In another word, if a field is configured with both canNotSeeOnAdd and a "required" validation rule, the add editor window will stay there when you click summit, without any prompt, until you cancel it.

**Comment by JimDalton** [comment]
OK, this feature works as expected.  Thank you
