### ISSUE TITLE
Add widget editor

### ISSUE THREAD

**Issue by di-shi** [TransNexus/NexOSS#297]

**Comment by di-shi** [comment]
@fenichelar The following issues I want to discuss
1. Nested array in Ember and Handlebars. Simple tech question.
2. How to handle widgets files (path and editor)
  i. Totally separated from Pages. Or
  ii. Totally same as Pages.
  From the code, option 1 is used. It causes some issues, we have to have two sets of code doing almost the same thing. The issue of option 2 is we have to add parameters for existing api/routes, such as /editor and /api/structure. I would prefer option 2. My thinking is to treat Pages and Widgets totally same. Add one parameter to all api/routes handle Pages for page or widget. It is not difficult, but involves some code adjustment.
3. Schema. We need something like Page schema and Widget schema, and both include Column schema. It involves changes for /api/schema. Other things for schema
  i.  Widget has totally different types
  ii. Widget has size property
  iii. Widget column type "link"

**Comment by fenichelar** [comment]
https://github.com/jdorn/json-editor

**Comment by di-shi** [comment]
@fenichelar Need your help for the following error, "Don't make functions within a loop." 

```
    util.httpGet('widgets', token).then(function(categorynames) {
      for (let categoryname of categorynames) {
        util.httpGet('widgets/' + categoryname, token).then(function(widgets) {
          var categories = _this.get('categories');
          categories.pushObject({
            name: categoryname,
            widgets: widgets
          });
          _this.set('categories', categories);
        });
      }
    });
```
I understand the function should not be defined in the loop, but I cannot find the correct syntax to move it out.

**Comment by di-shi** [comment]
@fenichelar Please ignore the help request. I figured it out. :)

**Comment by di-shi** [comment]
done.

**Comment by JimDalton** [comment]
Good Feature for me - Thank you.
