### ISSUE TITLE
Internal Server Error when drilling down in Fraud Trigger Reports

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#298]
#### Page Path
/ui/Fraud-Control_SIP-Analytics-Advanced_By-Customer-Device_Traffic-Pumping_Trigger-Report

#### Description of Issue
Internal Server Error when I try drill down to time buckets in Trigger Report.  Sam problem for Basic and Advanced Trigger Reports.
![image](https://cloud.githubusercontent.com/assets/18315382/20541596/f74e00aa-b0cb-11e6-949e-0f2044d276de.png)

**Comment by fenichelar** [comment]
I am requesting with search key `1%2B%2B%2B%2B%2B%2B%2B%2BCanada`. I think I should be requesting with search key `%20%20%20%20%20%20%20%20Canada`. We should discuss the best way to handle this without breaking other things. Encoding.....

**Comment by DmitryIsakbayev** [comment]
@fenichelar I maybe able to change the server to encode spaces as %20 instead of +
I don't think I can change the server to not decode + as space.

**Comment by DmitryIsakbayev** [comment]
For encoding, I could use https://google.github.io/guava/releases/19.0/api/docs/com/google/common/net/UrlEscapers.html#urlFragmentEscaper()

The function I currently use encodes like 
https://google.github.io/guava/releases/19.0/api/docs/com/google/common/net/UrlEscapers.html#urlFormParameterEscaper()

**Comment by fenichelar** [comment]
@DmitryIsakbayev That would solve the problem. You send me a `+` and I change it to a `%2B` which is what causes the problem.

**Comment by fenichelar** [comment]
I think that would work.

**Comment by JimDalton** [comment]
Cannot test this fix since drill down stops at 1 level (issue 305).

**Comment by JimDalton** [comment]
Fixed!
