### ISSUE TITLE
Add link to Charts in reports

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#3]
#### New URL
Example Pages:
http://172.16.4.93:9080/ui2/Traffic-Analyzer/Concurrent-Calls/By-Customer/By-Account
http://172.16.4.93:9080/ui2/Fraud-Control/CDR-Analytics-Advanced/By-Customer-Device/Theft-of-Service/Trigger-Report

**Comment by fenichelar** [comment]
Done.
