### ISSUE TITLE
Need to wrap column titles

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#300]
#### Page Path
/ui/Fraud-Control_CDR-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Thresholds

#### Description of Issue
This is one page of many pages that could be improved if column titles could be wrapped.  We need to revisit this requirement.  Adding more reports is a lot of work.  Adding more columns would save work and make the UI easier to use.
![image](https://cloud.githubusercontent.com/assets/18315382/20682809/88db06ee-b577-11e6-925f-d3030ff8f822.png)

**Comment by fenichelar** [comment]
@JimDalton Done. Maximum of two lines supported.

**Comment by JimDalton** [comment]
Great!

 

Thank you
