### ISSUE TITLE
Cannot search table column value with a + sign

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#301]
#### Page Path
/ui/Fraud-Control_CDR-Analytics-Basic_Configuration_Fraud-Rates_Manage

#### Description of Issue
1/2 of all the fraud rates begin with a + sign.  Cannot not search for values beginning with +

![image](https://cloud.githubusercontent.com/assets/18315382/20684354/89274792-b57d-11e6-9682-1fb49dfc2588.png)

**Comment by DmitryIsakbayev** [comment]
I believe @di-shi  has already addressed this issue in the latest UI.

**Comment by JimDalton** [comment]
Yes, it is fixed on .101!
