### ISSUE TITLE
Can only drill down 1 level.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#305]
#### Page Path
Any report page.

#### Description of Issue
This problem exists on multiple fraud and traffic report pages.  I can only drill down one level and then the drill down button stops working.
![image](https://cloud.githubusercontent.com/assets/18315382/20763599/b2c19f36-b6f8-11e6-99c4-c64dc624db8f.png)

**Comment by di-shi** [comment]
@DmitryIsakbayev I think the issue may be on NexOSS side

GET /applet/cgi-bin/data/viewReport.exe?appPrefix=Analyzer&appSubPrefix=&contextName=OSS-1-Customer-CC-Report&contextResources=tree-report-viewer&includeHeaders=false&forReportFileName=2016-12-01-20161130120745-CCS-Time-Code-Source.report&forKey=&displayMinusOneAs=&tokenDelimiter=%09&sortBy=3&sortOrder=asc&sortType=text&offset=0&limit=100 HTTP/1.1


0	true	%3ADay+2016-12-01+EST%28-0500%29	Day 2016-12-01 EST(-0500)	1938	1924	0.99277604	1466	0.75644994	0.0	0:10	262	0.092555806		0	0.0

GET /applet/cgi-bin/data/viewReport.exe?appPrefix=Analyzer&appSubPrefix=&contextName=OSS-1-Customer-CC-Report&contextResources=tree-report-viewer&includeHeaders=false&forReportFileName=2016-12-01-20161130120745-CCS-Time-Code-Source.report&forKey=:Day%2B2016-12-01%2BEST(-0500)&displayMinusOneAs=&tokenDelimiter=%09&sortBy=3&sortOrder=asc&sortType=text&offset=0&limit=100 HTTP/1.1


1	true	%3ADay+2016-12-01+EST%28-0500%29%3ACustomer-17	Customer-17	690	690	1.0	244	0.35362318	0.0	0:13	55	0.0066927504		0	0.0
1	true	%3ADay+2016-12-01+EST%28-0500%29%3ACustomer-28	Customer-28	625	625	1.0	613	0.9808	0.0	0:10	105	0.017908791		0	0.0
1	true	%3ADay+2016-12-01+EST%28-0500%29%3ACustomer-44	Customer-44	623	609	0.9775281	609	0.9775281	0.0	0:10	101	0.26253974		0	0.0

GET /applet/cgi-bin/data/viewReport.exe?appPrefix=Analyzer&appSubPrefix=&contextName=OSS-1-Customer-CC-Report&contextResources=tree-report-viewer&includeHeaders=false&forReportFileName=2016-12-01-20161130120745-CCS-Time-Code-Source.report&forKey=:Day%2B2016-12-01%2BEST(-0500):Customer-17&displayMinusOneAs=&tokenDelimiter=%09&sortBy=3&sortOrder=asc&sortType=text&offset=0&limit=100 HTTP/1.1


1	true	%3ADay+2016-12-01+EST%28-0500%29%3ACustomer-17	Customer-17	690	690	1.0	244	0.35362318	0.0	0:13	55	0.0066927504		0	0.0
1	true	%3ADay+2016-12-01+EST%28-0500%29%3ACustomer-28	Customer-28	625	625	1.0	613	0.9808	0.0	0:10	105	0.017908791		0	0.0
1	true	%3ADay+2016-12-01+EST%28-0500%29%3ACustomer-44	Customer-44	623	609	0.9775281	609	0.9775281	0.0	0:10	101	0.26253974		0	0.0

**Comment by DmitryIsakbayev** [comment]
@di-shi, would you please elaborate on what you think the issue is?

**Comment by DmitryIsakbayev** [comment]
@di-shi, I think I see it.

**Comment by DmitryIsakbayev** [comment]
@di-shi, let's test with NexOSS 8.18.6.  It will have two changes -
Extended the use urlPathSegmentEscaper instead of urlFormParameterEscaper for encoding report search keys.  It should encode spaces as '%20' instead of '+'
Regression Bug-Fix (introduced in 8.18.02) while key decoding was using the new ";;;" delimiter, key encoding continued to use the old delimiter ":"

**Comment by di-shi** [comment]
it works on .32 running 8.18.7.

**Comment by JimDalton** [comment]
Fixed!
