### ISSUE TITLE
Bad Request when opening the Blacklisted Subnets page

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#306]
#### Page Path
/ui/Fraud-Control_SIP-Analytics-Basic_Blacklisted-Countries_Configuration_Blacklisted-Subnets

#### Description of Issue
Open the Blacklisted Subnets page and Bad Request Error pops up.
![image](https://cloud.githubusercontent.com/assets/18315382/20765170/30df6c58-b6ff-11e6-9f96-8d997cd7d6ec.png)

**Comment by DmitryIsakbayev** [comment]
Invalid paths.view and paths.download.  Pages updated.

NexOSS-FC/05-Fraud-Control/01-SIP-Analytics-Basic/07-Blacklisted-Countries/02-Configuration/02-Blacklisted-Subnets.json

NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/07-Blacklisted-Countries/02-Configuration/02-Blacklisted-Subnets.json

**Comment by DmitryIsakbayev** [comment]
Please test.

**Comment by JimDalton** [comment]
Fixed
