### ISSUE TITLE
Cannot Download Subscribers from web interface

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#307]
#### Page Path
/ui/Accounts_Subscribers

#### Description of Issue
Nothing happens when the download button is clicked on the Subscribers page.  There is no error message
download paths = /analyzer/cgi-bin/data/viewMultiColumnConfig.exe?setKey=Subscribers&promptFileName=Subscribers.etc

**Comment by DmitryIsakbayev** [comment]
It seems to work with Chrome.
@JimDalton, what browser did you use?

**Comment by JimDalton** [comment]
Hmm...  I am using Chrome.  But I CAN download the file using MS Edge and Firefox.  I wonder what the problem is with my Chrome client?

**Comment by JimDalton** [comment]
I restarted Chrome and got the message below.  Perhaps it is the cause of this issue.
![image](https://cloud.githubusercontent.com/assets/18315382/20769922/dd35a140-b711-11e6-8d36-16009c027637.png)
