### ISSUE TITLE
SDReporter - Processes Row on Processes page is redundant

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#308]
#### Page Path
/ui/Server_Monitors_Processes

#### Description of Issue
The Processes row on this page is redundant and a little confusing.  Can the Processes row (Top row in screenshot below) be removed from this view?
I think this issue exists with all the monitor reports.  The summary row value used for widgets is displayed in the report.
![image](https://cloud.githubusercontent.com/assets/18315382/20796574/bf9cced6-b7a4-11e6-8e56-643ebdc68b02.png)

**Comment by DmitryIsakbayev** [comment]
Duplicate of issue #270

**Comment by JimDalton** [comment]
Fixed on .32.  I was looking at Expoential-e's server.
