### ISSUE TITLE
Cannot Update Fraud Trigger

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#310]
#### Page Path
/ui/Fraud-Control_SIP-Analytics-Basic_By-GroupId_Traffic-Pumping_Trigger-Thresholds

#### Description of Issue
Click on the Submit button of the Update modal and nothing happens.  No Error, no Update.  The Modal remains open.  Close the modal manually to view that the trigger has not changed.
paths.update = /analyzer/cgi-bin/action/updateReportTrigger.exe

**Comment by DmitryIsakbayev** [comment]
@di-shi, it looks like the request never makes it to NexOSS or even Sails.  Maybe a failed validation blocks the submit action.

**Comment by di-shi** [comment]
@DmitryIsakbayev You are right. It is validation for "key". I tested it using "validations": "any", it passed. There are two questions,
1. In this case, key="fraudqueryscoresourcetriggerbyserviceprovideridcallinggroupidcountrycode;wild card;wild card;wild card;wild card". I think either ';' or space caused this issue. Did you change it recently?
2. For my understanding, a column without validation option is configured, it should be treated as "any". What do you think?

**Comment by DmitryIsakbayev** [comment]
@di-shi, I don't think the key format changed recently.  In order to avoid problems like this, let's go with "any".

**Comment by di-shi** [comment]
@JimDalton All "key" columns add "any" validation rule.
