### ISSUE TITLE
Error dialog box does not show error details

### ISSUE THREAD

**Issue by di-shi** [TransNexus/NexOSS#311]
#### Page Path
http://172.16.4.103:7080/ui/Accounts_Subscribers

#### Description of Issue
![image](https://cloud.githubusercontent.com/assets/4260644/20887738/ed1147b6-bac9-11e6-9474-08c4f133f4fa.png)

**Comment by di-shi** [comment]
There are two issues,
1. HTTP headers are case insensitive, and javascript request library automatically converts them to lowercase. So, it must use "x-error-description" instead of "X-Error-Description" to parse the error details.
2. res.serverError function ignores its argument in production environment. It says

  // Only include errors in response if application environment
  // is not set to 'production'.  In production, we shouldn't
  // send back any identifying information about errors.

It may need a fully review for the error reporting implementation in our code. Here, I will only modify the error reporting code (from serverError to send) for the error (as string) returned by uitl.post/get/getTable.

**Comment by di-shi** [comment]
Also for the error returned by util.getList/getObject/getProperties, which call util.get.

**Comment by di-shi** [comment]
Also modify res.badRequest/forbidden/notFound with error message to res.send.

**Comment by di-shi** [comment]
Done.

**Comment by fenichelar** [comment]
Error handling revamped for more detailed messages. `serverError()` now returns data in production environments.
