### ISSUE TITLE
Error dialog box does not show up when try to upload wrong file again.

### ISSUE THREAD

**Issue by di-shi** [TransNexus/NexOSS#312]
#### Page Path
http://172.16.4.103:7080/ui/Accounts_Subscribers

#### Description of Issue
Upload the wrong file first time, a error dialog box is showed, after click OK and try to upload the wrong file again, no error dialog box is showed.

**Comment by di-shi** [comment]
The reason of the issue is the upload action is bound on EmberUploader.FileField->filesDidChange. If the selected file is not changed, the action is not triggered again.

**Comment by di-shi** [comment]
I do not find a simple way to clean up the selected file. The same question has been posted on GitHub, https://github.com/benefitcloud/ember-uploader/issues/134, by others. Let's wait for the answer.

**Comment by di-shi** [comment]
@fenichelar Any idea to use the following approach?

{{#if files}}
  <button {{action "clear"}}>Clear</button>
{{else}}
  {{file-field files=files}}
{{/if}}

It can reset the status.

**Comment by Amerr** [comment]
is this issue resolved ?

**Comment by fenichelar** [comment]
Done: 69c5b368a63a1f0deb8627fbdfd9933427b8b441
