### ISSUE TITLE
Implement new direct API to NexOSS

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#313]
#### Description of Issue
Need to implement new /api/direct/username/password/<NexOSS api>
Needs to support multipart Post messages and HTTP Get messages
Please provide wiretrace example message to Jim for documentation.

**Comment by fenichelar** [comment]
Get: `curl -u USERNAME:PASSWORD http://IP:7080/api/direct/NEXOSS_PATH`
Post: `curl -X POST -u USERNAME:PASSWORD -F files=@FILENAME http://IP:7080/api/direct/NEXOSS_PATH`

Please let me know what other information you need.

**Comment by JimDalton** [comment]
Thank you.
