### ISSUE TITLE
Cannot view fraud suspensions

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#316]
#### Page Path
/ui/Fraud-Control_Suspensions

#### Description of Issue
The table never loads.  This issue was reported by Hotwire.
![image](https://cloud.githubusercontent.com/assets/18315382/20934083/f1792060-bba7-11e6-866e-3abd6b301e7a.png)

**Comment by DmitryIsakbayev** [comment]
The page was missing paths.view

**Comment by JimDalton** [comment]
Thank you!
