### ISSUE TITLE
Reseting thresholds to default causes error

### ISSUE THREAD

**Issue by di-shi** [TransNexus/NexOSS#317]
#### Page Path
http://172.16.4.103:7080/ui/Fraud-Control_SIP-Analytics-Basic_By-GroupId_Traffic-Pumping_Trigger-Thresholds

#### Description of Issue
![image](https://cloud.githubusercontent.com/assets/4260644/20972683/b1edd1b8-bc63-11e6-9c03-e66a7d0d2999.png)

When update selected row, click default, then submit, an error dialog box popups. It was found during #310 troubleshoot. It looks like the default button action resets too much stuff.

**Comment by fenichelar** [comment]
@di-shi I think the function that handles this clears the contents of `form` and sets the variables to the defined default. We could have it not clear certain keys: `key`, `level`, `child`? Thoughts?

**Comment by di-shi** [comment]
@fenichelar @DmitryIsakbayev It is not enough. We also have to handle the difference between add/copy and update. For add/copy, the fields such as key must be reseted.

**Comment by di-shi** [comment]
This issue is too complicated. The simplest solution is to remove the clear button.

**Comment by fenichelar** [comment]
@di-shi Please test to confirm.
