### ISSUE TITLE
Unchecked box submits empty value instead of false.

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#323]
#### Page Path
/ui/Fraud-Control_CDR-Analytics-Basic_Blacklisted-Called-Numbers_Custom-List_Manage
or any other page that has a check box.

#### Description of Issue
As expected:
If the check box is checked, the api value is populated as  - `label=true`
If the check box is checked and then unchecked, the api value is populated as  - `label=false`

Wrong:
If the check box is left unchecked, the api value is blank instead of false = `label=`

**Comment by di-shi** [comment]
done.

**Comment by DmitryIsakbayev** [comment]
Works as expected.  Thank You.
