### ISSUE TITLE
Cannot get to Legacy UI from new UI

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#327]
#### Description of Issue
When I select "Java User Interface" under More dropdown menu, I get the following error.
The 172.16.4.101 page isn’t working
172.16.4.101 is currently unable to handle this request.
HTTP ERROR 500

**Comment by DmitryIsakbayev** [comment]
The link to Java user interface and Java rate provisioning tool expect NexOSS to run on the same box as the new UI.  Since .93, .100, .101 and .103 do not have a local NexOSS (they point to .32), these links do not work.  The link works on .32

**Comment by DmitryIsakbayev** [comment]
Added test-proxy-java-data.xml (similar to test-local.js and test-users.json) for pointing UI in the lab (on .93, .100, .101 and .103) to NexOSS on .32

@JimDalton, please test
@di-shi, I have not updated .103.  If you want the change please do cvs update in the ui2 project and restart the applications.

**Comment by di-shi** [comment]
ok.
