### ISSUE TITLE
Cannot update fraud trigger threshold - No response from API server

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#328]
#### Page Path
/ui/Fraud-Control_CDR-Analytics-Basic_By-GroupId_Theft-of-Service_Trigger-Thresholds

#### Description of Issue
Cannot update fraud trigger threshold.  No response from API server.
path.update = /analyzer/cgi-bin/action/updateReportTrigger.exe
![image](https://cloud.githubusercontent.com/assets/18315382/21622898/cedf5dd0-d1cd-11e6-932e-a3e8fc947c94.png)

**Comment by DmitryIsakbayev** [comment]
Looks like this issue is not specific to this page or this operation.  Sails often restarts.  No errors in production mode.  In development mode it logs -

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at Pipe.onread (net.js:559:26)

**Comment by DmitryIsakbayev** [comment]
No issues on .32.  It is running build-on-20161223.  I suspect a new version of a 3rd party module is causing this issue.

**Comment by DmitryIsakbayev** [comment]
@di-shi  and @fenichelar, maybe we should restrict what version of 3rd party libraries we use.

**Comment by di-shi** [comment]
No problem on .103 for build 20170104 (UpdateDist). It happens again.

I have to mention again the idea of unit test. It should work for this case.

Dmitry's idea can be to define a set "good" 3rd party libs and use them until have to upgrade to support our features or meet errors. The issue is how we know they are "good". A exhausting test is required. A weakened requirement should be they run long enough without any problem.

Another requirement of Dmitry's idea is to modify BuildDist rules not to upgrade 3rd libraries. It should be a little easier.

**Comment by DmitryIsakbayev** [comment]
@fenichelar 
Versions of node_modules used by the 20161223 build

server - 
activedirectory/package.json:  "version": "0.7.2",
ajv/package.json:  "version": "4.10.0",
ansi-to-html/package.json:  "version": "0.4.2",
assert/package.json:  "version": "1.4.1",
async/package.json:  "version": "2.1.4",
blocked/package.json:  "version": "1.2.1",
captains-log/package.json:  "version": "0.11.11",
codeclimate-test-reporter/package.json:  "version": "0.3.3",
csvtojson/package.json:  "version": "1.0.3",
dot-object/package.json:  "version": "1.5.4",
ejs/package.json:  "version": "2.3.4",
forever/package.json:  "version": "0.15.3",
glob/package.json:  "version": "7.1.1",
grunt-contrib-clean/package.json:  "version": "1.0.0",
grunt-contrib-coffee/package.json:  "version": "1.0.0",
grunt-contrib-concat/package.json:  "version": "1.0.1",
grunt-contrib-copy/package.json:  "version": "1.0.0",
grunt-contrib-cssmin/package.json:  "version": "1.0.1",
grunt-contrib-jst/package.json:  "version": "1.0.0",
grunt-contrib-less/package.json:  "version": "1.3.0",
grunt-contrib-uglify/package.json:  "version": "1.0.1",
grunt-contrib-watch/package.json:  "version": "1.0.0",
grunt/package.json:  "version": "1.0.1",
grunt-sails-linker/package.json:  "version": "0.10.1",
grunt-sync/package.json:  "version": "0.5.2",
include-all/package.json:  "version": "1.0.8",
istanbul/package.json:  "version": "0.4.5",
jquery/package.json:  "version": "3.1.1",
jshint/package.json:  "version": "2.9.4",
jsonlint/package.json:  "version": "1.6.2",
jsonwebtoken/package.json:  "version": "7.2.1",
mocha/package.json:  "version": "2.5.3",
moment/package.json:  "version": "2.17.1",
node-dir/package.json:  "version": "0.1.16",
object-hash/package.json:  "version": "1.1.5",
progress/package.json:  "version": "1.1.8",
q/package.json:  "version": "1.4.1",
rc/package.json:  "version": "1.0.1",
request/package.json:  "version": "2.79.0",
rmdir/package.json:  "version": "1.2.0",
sails-disk/package.json:  "version": "0.10.10",
sails-hook-winston/package.json:  "version": "1.1.0",
sails/package.json:  "version": "0.12.9",
supertest/package.json:  "version": "2.0.1",
winston-daily-rotate-file/package.json:  "version": "1.4.0",
winston/package.json:  "version": "2.3.0",

interface -
bower-npm-resolver/package.json:  "version": "0.4.0",
bower/package.json:  "version": "1.8.0",
broccoli-asset-rev/package.json:  "version": "2.5.0",
broccoli-funnel/package.json:  "version": "1.1.0",
broccoli-merge-trees/package.json:  "version": "1.2.1",
ember-bootstrap/package.json:  "version": "0.8.0",
ember-bootstrap-validations/package.json:  "version": "0.1.0",
ember-cli-app-version/package.json:  "version": "1.0.1",
ember-cli-babel/package.json:  "version": "5.2.1",
ember-cli-blanket/package.json:  "version": "0.8.0",
ember-cli-content-security-policy/package.json:  "version": "0.5.0",
ember-cli-dependency-checker/package.json:  "version": "1.3.0",
ember-cli-htmlbars-inline-precompile/package.json:  "version": "0.3.6",
ember-cli-htmlbars/package.json:  "version": "1.1.1",
ember-cli-ic-ajax/package.json:  "version": "0.2.4",
ember-cli-inject-live-reload/package.json:  "version": "1.4.1",
ember-cli-less/package.json:  "version": "1.5.3",
ember-cli/package.json:  "version": "1.13.15",
ember-cli-qunit/package.json:  "version": "1.4.2",
ember-cli-release/package.json:  "version": "0.2.8",
ember-cli-showdown/package.json:  "version": "2.7.0",
ember-cli-sri/package.json:  "version": "2.1.1",
ember-cli-uglify/package.json:  "version": "1.2.0",
ember-cli-uploader/package.json:  "version": "0.3.11",
ember-data/package.json:  "version": "2.10.0",
ember-disable-proxy-controllers/package.json:  "version": "1.0.1",
ember-export-application-global/package.json:  "version": "1.1.1",
ember-inflector/package.json:  "version": "1.9.6",
ember-notify/package.json:  "version": "5.1.4",
ember-power-select/package.json:  "version": "0.10.11",
ember-radio-button/package.json:  "version": "1.0.7",
ember-simple-auth/package.json:  "version": "1.0.1",
ember-simple-auth-token/package.json:  "version": "1.1.1",
ember-validations/package.json:  "version": "2.0.0-alpha.4",
phantomjs-prebuilt/package.json:  "version": "2.1.14",
rsvp/package.json:  "version": "3.3.3",
showdown/package.json:  "version": "1.4.1",

**Comment by fenichelar** [comment]
https://docs.npmjs.com/cli/shrinkwrap

**Comment by DmitryIsakbayev** [comment]
Added npm-shrinkwrap.json to NexOSS-Web-Interface and NexOSS-Web-Server based on the 20161223 build.  Works on .100.  The problem should go away on .93, .101, and .103 after the next daily build.

**Comment by JimDalton** [comment]
Works as expected.
