### ISSUE TITLE
Add support for dropdown trees

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#33]
#### Description of issue
See title

**Comment by fenichelar** [comment]
Can you make this:

`/cgi-bin/data/destinationsForProvider.exe?provider=`

Return the same thing as this:

`/cgi-bin/data/destinationsForProvider.exe`

I want to store a single URL:

`/cgi-bin/data/destinationsForProvider.exe?provider=PATHMASK`

If I replace `PATHMASK` with an empty string, then I receive every destination. If I replace `PATHMASK` with the provider name, then I just see the destinations for that provider. We can also use something like `*` instead of an empty string if that is better for you.

**Comment by fenichelar** [comment]
Set the `dependency` attribute of the column to the title of the column is is dependent on.

**Comment by DmitryIsakbayev** [comment]
Will change /cgi-bin/data/xxxxForProvider.exe?provider= to interpret empty provider value as the wild card in the next release - 8.9.14. 
Not including the provider= variable is also interpreted as the wild card.
