### ISSUE TITLE
Links from Server_Monitors_Triggers_Fraud-Analytics to actual Trigger Events pages are broken. 

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#332]
The server sends links to the TriggerEvents pages according to the FileUrl entries in the TriggerMon.etc file.  These values must be in sync with the "uniqueId" values of the Trigger Events pages.

[TriggerMon.etc.txt](https://github.com/TransNexus/NexOSS/files/694008/TriggerMon.etc.txt)

**Comment by DmitryIsakbayev** [comment]
Using the FileUrl of the old pages as the uniqueId for the new pages proved to be error prone. 

Let's use the actual report name.
Each trigger events page has the report name in the paths.view variable
`/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&searchKey=.*BillingBy-ServiceProviderId-CallingGroupId-Hour.*&file=PATHMASK`

We will set the uniqueId to "EventsFor-" + reportname.
Pages like /ui/Server_Monitors_Triggers_Traffic-Analyzer can then use Column 6 of TriggerMon2.stat file for the page link

Used scripts/setUniqueIdsForTriggerEventsPages.js for the bulk update.

Modified pages:
modified:   config/pages/NexOSS-FC/09-Server/Monitors/03-Triggers/01-Fraud-Analytics.json
	modified:   config/pages/NexOSS/05-Fraud-Control/00-SIP-Analytics-Registrations/02-Fraud-Control/01-By-Calling-Number/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/00-SIP-Analytics-Registrations/02-Fraud-Control/02-By-Source-IP/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/00-SIP-Analytics-Registrations/02-Fraud-Control/03-By-Source-Country/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/01-By-Customer-Device/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/01-By-Customer-Device/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/02-By-Calling-Number/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/02-By-Calling-Number/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/03-By-GroupId/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/03-By-GroupId/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/04-By-UserId/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/04-By-UserId/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/05-Blacklisted-User-Agents/02-Blocked-Calls/01-By-Customer/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/05-Blacklisted-User-Agents/02-Blocked-Calls/02-By-Calling-Number/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/06-Blacklisted-Called-Numbers/01-By-Customer/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/06-Blacklisted-Called-Numbers/02-By-Calling-Number/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/07-Blacklisted-Countries/01-By-Customer/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/02-SIP-Analytics-Advanced/01-By-Customer-Device/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/02-SIP-Analytics-Advanced/01-By-Customer-Device/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/02-SIP-Analytics-Advanced/02-By-Calling-Number/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/02-SIP-Analytics-Advanced/02-By-Calling-Number/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/02-SIP-Analytics-Advanced/03-By-GroupId/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/02-SIP-Analytics-Advanced/03-By-GroupId/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/02-SIP-Analytics-Advanced/04-By-Calling-UserId/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/02-SIP-Analytics-Advanced/04-By-Calling-UserId/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/01-By-Customer-Device/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/01-By-Customer-Device/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/02-By-Calling-Number/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/02-By-Calling-Number/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/03-By-GroupId/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/03-By-GroupId/01-Traffic-Pumping/04-Broadsoft/Suspension-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/03-By-GroupId/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/03-By-GroupId/02-Theft-of-Service/04-Broadsoft/Suspension-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/04-By-UserId/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/04-By-UserId/01-Traffic-Pumping/04-Broadsoft/Suspension-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/04-By-UserId/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/04-By-UserId/02-Theft-of-Service/04-Broadsoft/Suspension-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/01-By-Customer/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/02-By-Calling-Number/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/03-By-Calling-UserId/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/03-By-Calling-UserId/05-Broadsoft-Suspension-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/06-Blacklisted-Countries/01-By-Customer/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/01-By-Customer-Device/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/01-By-Customer-Device/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/02-By-Calling-Number/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/02-By-Calling-Number/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/03-By-GroupId/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/03-By-GroupId/01-Traffic-Pumping/04-Broadsoft/Suspension-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/03-By-GroupId/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/03-By-GroupId/02-Theft-of-Service/04-Broadsoft/Suspension-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/04-By-Calling-UserId/01-Traffic-Pumping/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/04-By-Calling-UserId/01-Traffic-Pumping/04-Broadsoft/Suspension-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/04-By-Calling-UserId/02-Theft-of-Service/03-Trigger-Events.json
	modified:   config/pages/NexOSS/05-Fraud-Control/04-CDR-Analytics-Advanced/04-By-Calling-UserId/02-Theft-of-Service/04-Broadsoft/Suspension-Events.json
	modified:   config/pages/NexOSS/06-Traffic-Analyzer/03-Triggers/01-By-Customer/01-By-Account/03-Events.json
	modified:   config/pages/NexOSS/06-Traffic-Analyzer/03-Triggers/01-By-Customer/02-By-Device/03-Events.json
	modified:   config/pages/NexOSS/06-Traffic-Analyzer/03-Triggers/02-By-ServiceProviderId/03-Events.json
	modified:   config/pages/NexOSS/06-Traffic-Analyzer/03-Triggers/03-By-Proxy-Device/03-Events.json
	modified:   config/pages/NexOSS/06-Traffic-Analyzer/03-Triggers/04-By-Provider/01-By-Account/03-Events.json
	modified:   config/pages/NexOSS/06-Traffic-Analyzer/03-Triggers/04-By-Provider/02-By-Device/03-Events.json
	modified:   config/pages/NexOSS/06-Traffic-Analyzer/03-Triggers/04-By-Provider/03-By-Device-and-Dial-Code/03-Events.json
	modified:   config/pages/NexOSS/06-Traffic-Analyzer/04-CDRs/05-Processed/01-By-Reporting-Device/05-Trigger-Events.json
	modified:   config/pages/NexOSS/07-QoS/02-Source-QoS/04-Triggers/03-Events.json
	modified:   config/pages/NexOSS/07-QoS/03-Destination-QoS/04-Triggers/03-Events.json
	modified:   config/pages/NexOSS/07-QoS/04-Calling-Party-QoS/04-Triggers/03-Events.json
	modified:   config/pages/NexOSS/07-QoS/05-Called-Party-QoS/04-Triggers/03-Events.json
	modified:   config/pages/NexOSS/08-Billing/02-Credit-Controls/01-By-Customer/01-By-Hour/03-Trigger-Events.json
	modified:   config/pages/NexOSS/08-Billing/02-Credit-Controls/01-By-Customer/02-By-Day/03-Trigger-Events.json
	modified:   config/pages/NexOSS/08-Billing/02-Credit-Controls/02-By-Calling-Number/01-By-Hour/03-Trigger-Events.json
	modified:   config/pages/NexOSS/08-Billing/02-Credit-Controls/02-By-Calling-Number/02-By-Day/03-Trigger-Events.json
	modified:   config/pages/NexOSS/08-Billing/02-Credit-Controls/03-By-GroupId/01-By-Hour/03-Trigger-Events.json
	modified:   config/pages/NexOSS/08-Billing/02-Credit-Controls/03-By-GroupId/01-By-Hour/05-Broadsoft-Suspension-Events.json
	modified:   config/pages/NexOSS/08-Billing/02-Credit-Controls/03-By-GroupId/02-By-Day/03-Trigger-Events.json
	modified:   config/pages/NexOSS/08-Billing/02-Credit-Controls/03-By-GroupId/02-By-Day/05-Broadsoft-Suspension-Events.json
	modified:   config/pages/NexOSS/09-Server/Monitors/03-Triggers/01-Fraud-Analytics.json
	modified:   config/pages/NexOSS/09-Server/Monitors/03-Triggers/02-Traffic-Analyzer.json
	modified:   config/pages/NexOSS/09-Server/Monitors/03-Triggers/03-QoS.json
	modified:   config/pages/NexOSS/09-Server/Monitors/03-Triggers/04-Billing.json
	modified:   config/pages/SDReporter/04-Server/Monitors/03-Triggers/01-Fraud-Analytics.json
	modified:   config/pages/SDReporter/04-Server/Monitors/03-Triggers/02-Traffic-Analyzer.json
	modified:   config/pages/SDReporter/04-Server/Monitors/03-Triggers/03-QoS.json

**Comment by DmitryIsakbayev** [comment]
Please test.

**Comment by JimDalton** [comment]
Fixed
