### ISSUE TITLE
Suspensions cannot be deleted in the new GUI - PressOne & Aslo

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#334]
#### Page Path
/ui/Fraud-Control_Suspensions

#### Description of Issue
Suspensions cannot be deleted in the new GUI, it has to be done via the legacy.
You can select and delete a suspension from the new UI.  The new UI accepts the change and it looks like a successful transaction, but the suspension remains in the Suspensions view.

**Comment by DmitryIsakbayev** [comment]
Two things.  Removed single quotes around values by appending to the paths.view
`&searchFor='&replaceWith=`

Also, the UI was not including one of the invisible columns because (I think) it did not have the title property. @fenichelar and @di-shi what do you think?

**Comment by DmitryIsakbayev** [comment]
@JimDalton, please test.

**Comment by JimDalton** [comment]
Fixed
