### ISSUE TITLE
Cannot update Post Dial Delay (PDD) Trigger Threshold

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#335]
#### Page Path
/ui/Traffic-Analyzer_Triggers_By-Customer_By-Account_Thresholds

#### Description of Issue
It is possible to configure a new Traffic Analyzer Threshold, the PDD value is always -1.  When I try to update the trigger, the result is the following error response.
![image](https://cloud.githubusercontent.com/assets/18315382/21905045/0679fe8c-d8d4-11e6-81b4-500d1f9c0c7b.png)

**Comment by DmitryIsakbayev** [comment]
Looks like a page configuration issue.  The key column should be invisible, but its order must not be -1.  There were 3 pages where the order was -1

modified:   config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/01-By-Customer/02-Trigger-Thresholds.json
	modified:   config/pages/NexOSS/06-Traffic-Analyzer/03-Triggers/01-By-Customer/01-By-Account/02-Thresholds.json
	modified:   config/pages/SDReporter/02-Traffic-Analyzer/03-Triggers/01-By-Source/01-By-Realm/02-Thresholds.json

Used scripts/setKeyOrderToZerroForTriggerThresholds.js to check all Threshold pages.

**Comment by DmitryIsakbayev** [comment]
Please test.

**Comment by JimDalton** [comment]
When I update the PDD threshold and hit submit, the modal closes and no error is reported.  But the PDD threshold value remains unchanged on the Threshold page.  Refreshing the page makes no diffference.

**Comment by DmitryIsakbayev** [comment]
Strange.  I don't think my changes made in.  I will look into it.

**Comment by DmitryIsakbayev** [comment]
@fenichelar, what is this

Revert "Revert "Edit Trigger thresholds for call completion by custom…

 https://github.com/TransNexus/NexOSS-Web-Server/commit/dcaf0846322444752fee2ffd314bf0eb2a32ce9a

**Comment by DmitryIsakbayev** [comment]
@JimDalton, @fenichelar and I submitted conflicting changes to the same file.  Looks like the changes have been restored.  Please try again.

**Comment by fenichelar** [comment]
Working.
