### ISSUE TITLE
New Column Type Needed: Milliseconds_to_hh:mm:ss

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#336]
#### Page Path
/ui/Traffic-Analyzer_Triggers_By-Source_By-Realm_Thresholds

#### Description of Issue
@fenichelar     TrafficAnalyzer trigger threshold for Average Call Duration is in milliseconds.  Users think about average call duration in minutes and seconds.  The Average Call Duration in milliseconds needs to be displayed in hh:mm:ss format.  Examples
milliseconds           hh:mm:ss format
30,000                     0:30  (30 seconds, note that the hours are not displayed)
3,600,000                1:00:00 (3,600 seconds or 1 hour)
If the average call duration is longer than 99:59:59, then the string "long call" in place of hh:mm:ss would be nice, but is not a critical need.  It is very unlikely the long average call duration use case will ever occur.
![image](https://cloud.githubusercontent.com/assets/18315382/21906433/4dc9f79c-d8d9-11e6-9ef6-88a72a90a195.png)

**Comment by fenichelar** [comment]
Done.
