### ISSUE TITLE
New column type needed: dateAndTime

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#337]
Sample value: 2017-01-16 16:04:25

**Comment by fenichelar** [comment]
Date column types:
date: YYYY-MM-DD
datetime: YYYY-MM-DD HH:mm:ss
dayOfWeek-time: ddd-HH:mm

**Comment by DmitryIsakbayev** [comment]
Sorry.  I overlooked it in the list.  Works as expected.
