### ISSUE TITLE
Disable SIP Analytics Reports by GroupId and UserId

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#338]
#### Page Path
/ui/Fraud-Control_SIP-Analytics-Basic_Configuration_Reports

#### Description of Issue
Need to be able to disable Traffic Pumping, Theft of Service and Blacklisted Numbers reports by GroupId and UserId.
Need the APIs in order by column so they can be added to the json config file.
![image](https://cloud.githubusercontent.com/assets/18315382/21999131/8d155e20-dc06-11e6-92f4-dd8f826ce5ab.png)

**Comment by DmitryIsakbayev** [comment]
@JimDalton, the attached file describes all reports.  The "Name" is what you need for the API.

[TriggerMon.txt](https://github.com/TransNexus/NexOSS/files/709430/TriggerMon.txt)

**Comment by JimDalton** [comment]
Done
