### ISSUE TITLE
New UI Build Date or version number viewable from the web interface

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#339]
#### Description of Issue
For Customer support purposes, it would be helpful if we could see from the web interface when a UI version was built.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Can the build script put the data in local.js? This would make it easy to display.

**Comment by DmitryIsakbayev** [comment]
@fenichelar, that should be possible.  I suppose it should be date and time, sometimes we generate the build more than once a day.  Do you have a preference for the variable name?

**Comment by DmitryIsakbayev** [comment]
@fenichelar, I added buildTime variable to local.js

**Comment by DmitryIsakbayev** [comment]
@di-shi, you will need to update the ui2 project to get the change.

**Comment by di-shi** [comment]
@DmitryIsakbayev done.

**Comment by JimDalton** [comment]
@fenichelar   It would be nice if the UI build date could be viewed from /ui/Server_Software_License-Details
If this is not easy, what needs to be done to display the UI build date from the UI?

**Comment by fenichelar** [comment]
Done.
Interface: https://github.com/TransNexus/NexOSS-Web-Interface/commit/869541170a4cd187a5cdcf1fea677b6e3111b7c8
Server: https://github.com/TransNexus/NexOSS-Web-Server/commit/86951017c84094530f63facd1d2f30b8cb98fbd1

**Comment by fenichelar** [comment]
@DmitryIsakbayev This won't work. Please call me to discuss.
