### ISSUE TITLE
Tomcat Encoding Issue

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#34]
#### Description of issue
It appears that Tomcat or something on .93 is not understanding the file encoding correctly. All files should be encoded as UTF-8.

When I use Apache running on my computer I see the following for the close button on modals: 
![image](https://cloud.githubusercontent.com/assets/3437075/15429077/f49c4a0c-1e6c-11e6-9ec7-978d676d4731.png)

When I use .93 I see the following for the close button on modals: 
![image](https://cloud.githubusercontent.com/assets/3437075/15429098/0f957c16-1e6d-11e6-9ea9-1fa16e067ad3.png)

This is definitely an encoding issue but I am not certain where.

**Comment by DmitryIsakbayev** [comment]
Upgraded Tomcat from 4 to 7 but that did not seem to help.

**Comment by fenichelar** [comment]
I'll see if the ember development server also has the same problem on .93.

**Comment by fenichelar** [comment]
When using the Ember development server I did not have the encoding problem. Therefore, it is most likely a Tomcat issue, not sure why though.

**Comment by JimDalton** [comment]
I know longer see the encoding issue on the Add Accounts modal.  What was done to fix this issue?
![image](https://cloud.githubusercontent.com/assets/18315382/16079881/ba66dfde-32d3-11e6-903e-818a9283ecc8.png)

**Comment by fenichelar** [comment]
This seems to be fixed, did you do something?

**Comment by DmitryIsakbayev** [comment]
Nothing since upgrading tomcat from 4 to 7.

**Comment by JimDalton** [comment]
Seems to be fixed.
