### ISSUE TITLE
New column type needed: file

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#340]
Use case - upload a new rate plan file along with other information - account name, effective date, etc.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Just so you know how this is going. It is a pain to send the file and JSON together so here is what I did:

Ember takes the file from the browser, reads it, encodes the contents using base 64, then sends it as a string with the column name as the key like everything else. Basically as if the file was base 64 encoded and entered into a text box.

I am currently working on the Sails part. Sails is going to decode it and send it to you as a file with the rest of the key/value pairs as query parameters like normal.

Sound good?

**Comment by fenichelar** [comment]
Also, this means you can't have more than 1 column of type `file` on a given page.

**Comment by DmitryIsakbayev** [comment]
@fenichelar, that sounds good.  One file should be enough.

**Comment by fenichelar** [comment]
@DmitryIsakbayev I have implemented the Sails part, I hope it will work, hard to test now.

**Comment by DmitryIsakbayev** [comment]
@fenichelar, I can upload a file with 20K lines (528K) and smaller.  A file with 30K lines (792K) and bigger generates 400 - Bad Request.

**Comment by fenichelar** [comment]
I am going to change the way it works. When you select a file, I will upload it to Sails. Sails will return the filename is used to save it (random string). When you click submit, I will pass the filename back to Sails so Sails knows which file to use. Basically, two requests, one for file and one for data.

**Comment by fenichelar** [comment]
Can you please send me some sample data to upload?

**Comment by DmitryIsakbayev** [comment]
[West-Telecom.csv.gz](https://github.com/TransNexus/NexOSS/files/751455/West-Telecom.csv.gz)

**Comment by fenichelar** [comment]
@DmitryIsakbayev Please rebuild and test: /ui/Rate-Provisioning_Rate-Provisioning-New-Alpha_Provision. Implemented tool with single page.

**Comment by DmitryIsakbayev** [comment]
Seems to work.  I am not sure how I feel about  two pages in one approach.  I will sleep on it.
What is your take on #351?

**Comment by fenichelar** [comment]
#351 might be better server in config files. A config setting for a page to redirect to on success for each button. Nothing means don't redirect.

**Comment by DmitryIsakbayev** [comment]
"A config setting for a page to redirect to on success for each button" sounds good.  There is a case when the fileApprove action could redirect to a number of different pages (depending on the rate plan type - customer, provider, or product), but we can probably work something out.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Closing this out. Still working on #351.
