### ISSUE TITLE
New path needed: approveFile

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#341]
It should be similar to deleteFile.
The use case is for rate provisioning.  The user will examine rate plan file parsed according to the rate plan template and decide whether it should be approved (approveFile) or deleted (deleteFile).

**Comment by fenichelar** [comment]
@DmitryIsakbayev Added but not yet tested.

**Comment by fenichelar** [comment]
@DmitryIsakbayev It appears to be working.

**Comment by DmitryIsakbayev** [comment]
@fenichelar, this action should trigger a refresh of the paths.list.  It renames the file (and just like deleteFile) changes the list of available files.

**Comment by DmitryIsakbayev** [comment]
@fenichelar, looks like if the server response with and error code (580 and X-Error-Description header), the UI pops up "No response from the API server"

**Comment by fenichelar** [comment]
Mmmm. Could you please provide a way for me to replicate?

**Comment by DmitryIsakbayev** [comment]
Fair enough.  I don't have this feature in the lab yet.  I will come back to it.

**Comment by fenichelar** [comment]
I am guessing that this is an error displaying issue because I changed the way errors are handled. I will try and replicate on another page. Let me know if you find it anywhere else.

**Comment by fenichelar** [comment]
#311 Please pull in the latest changes and try again.

**Comment by DmitryIsakbayev** [comment]
Looking good.

![1](https://cloud.githubusercontent.com/assets/14879700/22560294/13271312-e942-11e6-82e8-0c4f071593ad.png)
