### ISSUE TITLE
Problems Product viewing rates

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#344]
#### Page Path
/ui/Route-Provisioning_Least-Cost_Products_Rates
/ui/Route-Provisioning_Least-Cost_Routes_Rates
/ui/Billing_Rates_Current-Rates_Customer-Rates  (Too many rows, page will not load)
/ui/Billing_Rates_Current-Rates_Product-Rates
/ui/Billing_Rates_Current-Rates_Provider-Rates  (Too many rows, page will not load)

#### Description of Issue
The top level view shows both products and breakouts in the first column.  Only Product Names should be visible.
![image](https://cloud.githubusercontent.com/assets/18315382/22398106/a59c381e-e54e-11e6-98ee-0c221b251540.png)

**Comment by fenichelar** [comment]
@DmitryIsakbayev I think this is a NexOSS issue or URL issue.

**Comment by DmitryIsakbayev** [comment]
Looks like a regression bug introduced in 8.24.00.  Will include the fix in the next version (after 8.25.0).

**Comment by JimDalton** [comment]
Fixed

**Comment by DmitryIsakbayev** [comment]
Part of issue #344, rate pages under Billing were missing the forKey=FILTERMASK parameter.

https://github.com/TransNexus/NexOSS-Web-Server/commit/61002af74625e6cabd023a1b5c7d9957257d79a3
