### ISSUE TITLE
Cannot update or delete Calling Number Translation Rules

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#345]
#### Page Path
/ui/Number-Translation_Pre-Routing_Calling-Number-Translation

#### Description of Issue
The following error is returned when I try to update or Delete a calling number translation rule.
![image](https://cloud.githubusercontent.com/assets/18315382/22440050/01252882-e700-11e6-9a96-1dd972333385.png)

**Comment by DmitryIsakbayev** [comment]
A regression bug.  It is also responsible for #344

**Comment by JimDalton** [comment]
Fixed
