### ISSUE TITLE
Cannot Add blacklisted number to Custom List

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#346]
#### Page Path
/ui/Fraud-Control_SIP-Analytics-Basic_Blacklisted-Called-Numbers_Custom-List

#### Description of Issue
When adding a number to the custom blacklist, the error below is returned.  May be the same as issue 344.
![image](https://cloud.githubusercontent.com/assets/18315382/22472269/230f4074-e7a3-11e6-8bca-133f20cd92c5.png)

**Comment by DmitryIsakbayev** [comment]
There is a  regression bug in NexOSS. It is also responsible for #344, #345, #347

**Comment by JimDalton** [comment]
Fixed
