### ISSUE TITLE
NexOSS Error

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#347]
What is wrong with this request?

`curl "http://172.16.4.32:7080/cgi-bin/action/number_trans/updateRule?setKey=RoutePlanMap1&originalGroup=Customer-139&originalCalledNumber=&originalCallingNumber=&originalTime=Mon-00%3A00&originalRule=SysTestProd-1&originalNote=&originalId=eb0754875d0280519d26f1551c72a2fd14ffd5e3&0=true&group=Customer-139&calledNumber=&callingNumber=&time=Mon-00%3A00&rule=SysTestProd-1&note=&id=eb0754875d0280519d26f1551c72a2fd14ffd5e3"`

Thanks.

**Comment by DmitryIsakbayev** [comment]
Nothing.  There is a  regression bug in NexOSS. It is also responsible for #344 and #345

**Comment by fenichelar** [comment]
@DmitryIsakbayev Thanks!
