### ISSUE TITLE
CC doesn't work in email config

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#348]
The setting doesn't stick. I think we have the wrong API value, what should it be?

**Comment by DmitryIsakbayev** [comment]
@fenichelar, which page?  It seems to work in  
/ui/Server_Logs_Email_Configuration
/ui/Fraud-Control_CDR-Analytics-Basic_Configuration_Alerts_Email

**Comment by fenichelar** [comment]
Mmmm. William reports it does not work on Server_Logs_Email_Configuration on .25.

**Comment by DmitryIsakbayev** [comment]
Looks like the etc/LoggingAlerts.etc on .25 was missing a couple of configuration keys -
ERROR_ALERTS_EMAIL_Cc=
TRIGGER_ALERTS_EMAIL_Cc=triggers@TransNexus.com
CDRANALYZER_EMAIL_Cc=
