### ISSUE TITLE
Starts with search for Product Full View does not work

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#349]
#### Page Path
/ui/Route-Provisioning_Least-Cost_Products_Full-View

#### Description of Issue
Please see the screenshot below.  Search of the Breakouts column is not a starts with search.  Note that the 263 in the search box results in any breakout that contains 263.   The Breakouts "Titles" is defined as type=telephone, but the search is type=text search function.
![image](https://cloud.githubusercontent.com/assets/18315382/22555587/21208fbc-e932-11e6-8db2-429e17cee8f0.png)

**Comment by fenichelar** [comment]
Resolved: https://github.com/TransNexus/NexOSS-Web-Server/commit/83a963c62c90647b7804364dc46ad7f841a6c904

**Comment by JimDalton** [comment]
Fixed
