### ISSUE TITLE
No newlines in data received from NexOSS

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#35]
#### New URL
`/Route-Provisioning_Least-Cost_Destinations_Add-or-Update-Device`

#### Description of issue
The URL below does not contain any newlines so it is interpreted by Sails.js as a single row.
`/cgi-bin/data/destinationsData.exe`

**Comment by DmitryIsakbayev** [comment]
Good catch.  Will include the fix in the next release - 8.9.14.

**Comment by JimDalton** [comment]
Fixed
