### ISSUE TITLE
Cannot drilldown into Products Full View

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#350]
#### Page Path
/ui/Route-Provisioning_Least-Cost_Products_Full-View

#### Description of Issue
Drilling down into LCR Product Full View shows no results.
Below is a screenshot of the old UI that shows routes for breakout ##1201200.  There are five providers.
![image](https://cloud.githubusercontent.com/assets/18315382/22556483/4e19d494-e935-11e6-952b-f6a2dfab3459.png)

The screenshot below is the new UI with drilldown for the same breakout ##1201200.  There are no matching records.
![image](https://cloud.githubusercontent.com/assets/18315382/22556541/81f3a844-e935-11e6-85ab-8df551fba77b.png)

**Comment by fenichelar** [comment]
76391d2ac24f9f1fea7046c283007a798961646a

**Comment by DmitryIsakbayev** [comment]
@JimDalton, try clicking on "Clear Filters"

I can replicate this problem if I add a breakout filter (like 200) after drilling into LD and then drill into the breakout.

@fenichelar, looks like the filter conditions should be cleared out after drilling in or out.

**Comment by fenichelar** [comment]
@DmitryIsakbayev https://github.com/TransNexus/NexOSS-Web-Interface/commit/76391d2ac24f9f1fea7046c283007a798961646a

**Comment by DmitryIsakbayev** [comment]
@fenichelar, I like the links to code changes.  How do you generate them?

**Comment by fenichelar** [comment]
It would be much easier if we used the same repository for code as we do for issues. You would just type: `bc568d3` for the first commit on this repository like so: bc568d3.

**Comment by DmitryIsakbayev** [comment]
I think it is a good practice to include links when a ticket is addressed.  Let's try to stick to it when possible.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Sounds good.

**Comment by JimDalton** [comment]
Fixed
