### ISSUE TITLE
SIP Call Attempts by Destination widget stats to not add up

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#352]
#### Description of Issue
Here is what I see from the map widget in the screenshot below.
Only three countries show call attempts.  USA, Canada and China.
Country | Call Attempts | share
USA | 223,839 | 81.45%
Canada | 24,947 | 9.08%
China | 433 | 0.16%
Total | 249,212 | 90.70%
When I calculate the total for each column, the share total is not 100%
![image](https://cloud.githubusercontent.com/assets/18315382/22566463/fdce540e-e959-11e6-9932-31be8ea2c972.png)

**Comment by fenichelar** [comment]
Fixed: https://github.com/TransNexus/NexOSS-Web-Interface/commit/ceeb0626f6ac0b4fc3ad290563268e80bbcc16ce
