### ISSUE TITLE
Help link is not available

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#356]
#### Page Path
Any page

#### Description of Issue
The Help link under the More dropdown is no longer available. 
![image](https://cloud.githubusercontent.com/assets/18315382/22705147/6a736db0-ed38-11e6-8b3f-c30af405183b.png)

**Comment by fenichelar** [comment]
@JimDalton This was caused because the files were not named correctly.
`01-Accounts/04-Subscribers.json`
`01-Accounts/Subscribers.pdf`
The names must be exactly the same. I have renamed the pdf files to include the number for all files under `01-Accounts`.
