### ISSUE TITLE
Supporting multiple subfolders in list view of file-viewer

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#359]
Usually the the list view simply lists files.
In few cases (billing invoices) the list includes a folder / file.  Support for / was added in #170.
Now I am trying to list multiple subfolders, something like folder1/folder2/folder3/file and it looks like the UI supports only one /.  The server gets a request for file 
folder1/folder2 
instead of
folder1/folder2/folder3/file

**Comment by DmitryIsakbayev** [comment]
These pages can be used for testing after NexOSS in the lab is upgraded to 9.03.0

config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/06-Blacklisted-Called-Numbers/00-All-CDRs.json
config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/00-All-CDRs.json

**Comment by fenichelar** [comment]
Done: 95005855187d4ea8cf6d187718e5a8e93e3999c8
