### ISSUE TITLE
Usability Improvement for Modals

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#363]
#### Page Path
Any modal

#### Description of Issue
@fenichelar   I think modals would be more intuitive for users if the "can't be blank" name was in the dropdown box rather than below the box.  Having the "can't be blank" message below the dropdown box creates a lot of space between the dropdown box and descriptive comment.  User's have to think a moment to connect the description to the dropdown box.  Is there anyway to move the "can't be blank" message so it does not separate the dropdown box from its description? 
![image](https://cloud.githubusercontent.com/assets/18315382/23181553/625c433e-f843-11e6-85ef-07476de6055d.png)

**Comment by fenichelar** [comment]
@JimDalton The "can't be blank" message is handled by a third party library. What about changing the order so that the description is between the title and the dropdown/text box?

**Comment by fenichelar** [comment]
Done: c35170793b3c45bed3c5e64a45b141c6d1980195
