### ISSUE TITLE
Need "Loading" indicator

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#367]
#### Page Path
/ui/Rate-Provisioning_Provision-Rate-Plans_Upload-Rates

#### Description of Issue
Adding a large rate plan file can take more than a few seconds.  After the selecting the Upload button and selecting a rate plan file, the user is returned to the modal with no changes in appearance.  It appears that the rate plan file selection failed.  But in fact, the rate plan is in the process of loading.  My reaction to was retry uploading the file.  To prevent this user confusion, the modal needs to  indicate the rate plan selection was successful and the file is being uploaded.
![image](https://cloud.githubusercontent.com/assets/18315382/23205992/ff3713e8-f8b9-11e6-854d-9a349dc57bdf.png)

**Comment by fenichelar** [comment]
Done: 9dfd4166ae7727ba797cf46cd61d6c1b201bb3cd

**Comment by JimDalton** [comment]
@fenichelar I tested this and did not see any change.

**Comment by fenichelar** [comment]
@JimDalton Please update and test again.
