### ISSUE TITLE
Data Formatting requests

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#369]
#### Description of Issue
For the data 2017-02-22 04:59:38
Current the data types "date" and "datetime" both display the same: 2017-02-22 04:59:38
The notes on the UI state 'date' - A date in the format mm/dd/yyyy, but this is not what I observe.
It would be better if the three formats below were available for this data. 
type = date displays 2017-02-22    yyyy-mm-dd (different from mm/dd/yyyy)
type = datetime displays 2017-02-22 04:59:38   yyyy-mm-dd hh:mm:ss
type = time displays 04:59:38   hh:mm:ss

**Comment by fenichelar** [comment]
Added time to formatters. date, datetime, time only affect input, not output.
