### ISSUE TITLE
Error E-mail Alert Config page error

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#39]
#### Page Title
Error Message E-mail Alert

#### Legacy URL
/logs/oss_logs_config_email.htm

#### New URL
/ui2/Dashboard_Logs_Email_Configuration

#### Description of issue
Error is presented when the page opens.  See screenshot.
![image](https://cloud.githubusercontent.com/assets/18315382/15589019/e0926ac2-235e-11e6-85de-854b900e8f2b.png)

**Comment by fenichelar** [comment]
Unable to reproduce.

**Comment by JimDalton** [comment]
This issue is replaced by Issue #60
