### ISSUE TITLE
We should use notInModal for these situations

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#391]
#### Page Path
Route Provisioning / Least Cost / Products / Breakouts

#### Description of Issue
notInModal: true

**Comment by JimDalton** [comment]
@fenichelar   I do not understand the issue.  Do I need to update the config?  If so why?

**Comment by fenichelar** [comment]
![image](https://cloud.githubusercontent.com/assets/3437075/24561453/cb5b109c-1614-11e7-8417-18a4ab1a6e2a.png)
@JimDalton "Number of Providers" should have attribute "notInModal" set to "true" to remove it from the modal.
