### ISSUE TITLE
Cannot add Account Attibute

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#396]
#### Page Path
/ui/Accounts_Accounts

#### Description of Issue
When I update an Account to have an Attribute, the change is submitted with no error.  But the attribute does not appear in the Account page view.

**Comment by DmitryIsakbayev** [comment]
@JimDalton, it requires NexOSS 9.11.0.  Was this in the lab or a customer installation?
#388

**Comment by JimDalton** [comment]
I was looking at V9.10 installed for Arkadin.  Works as expected on 9.12 in the lab.
