### ISSUE TITLE
Unable to connect to server on login

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#399]
What does it mean?  Node is running.

![1](https://cloud.githubusercontent.com/assets/14879700/24712418/ccf79738-19f0-11e7-83fc-c51d482338fc.png)

**Comment by fenichelar** [comment]
`cd Sails`
`npm install --save skipper`
`rm npm-shrinkwrap.json`
`npm shrinkwrap`

**Comment by DmitryIsakbayev** [comment]
Sails could not fully start because it was missing a module.  Should have checked Sails/logs to see the reason.
