### ISSUE TITLE
Error:0 of .93 UI,  Upload Description error

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#43]
#### Description of issue
.[JD] In the last config file I added data for paths.upload and upload.title.  The error below looks like it was cause by upload.description property in the config file.  Is this correct?  Do I need to change the config file?

        "file": "/home/travis/build/TransNexus/NexOSS-Web-Server/config/pages/04-Number-Translation/01-Pre-Routing/01-Called-Number-Translation.json",
        "error": [
            {
                "keyword": "additionalProperties",
                "dataPath": ".upload",
                "schemaPath": "#/properties/upload/additionalProperties",
                "params": {
                    "additionalProperty": "description"
                },
                "message": "should NOT have additional properties",
                "schema": false,

**Comment by fenichelar** [comment]
Yes, upload.description needs to be removed.

On Saturday, May 28, 2016, JimDalton <notifications@github.com> wrote:

> Page Title Legacy URL New URL Description of issue
>
> .[JD] In the last config file I added data for paths.upload and
> upload.title. The error below looks like it was cause by upload.description
> property in the config file. Is this correct? Do I need to change the
> config file?
>
>     "file": "/home/travis/build/TransNexus/NexOSS-Web-Server/config/pages/04-Number-Translation/01-Pre-Routing/01-Called-Number-Translation.json",
>     "error": [
>         {
>             "keyword": "additionalProperties",
>             "dataPath": ".upload",
>             "schemaPath": "#/properties/upload/additionalProperties",
>             "params": {
>                 "additionalProperty": "description"
>             },
>             "message": "should NOT have additional properties",
>             "schema": false,
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TransNexus/NexOSS/issues/43>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADRyEzafqeMt3eZ0G6uQyeiqA5tHmrKJks5qGC5IgaJpZM4IpD44>
> .
>


-- 

Sincerely,

Alec Fenichel
alec.fenichel@gmail.com
407-760-0036

**Comment by JimDalton** [comment]
I have removed the page from the config file that causes the missing type error.  The config file now passes on Travis, but the UI2 on .93 still shows only Error 0
![image](https://cloud.githubusercontent.com/assets/18315382/15633000/2f17d82c-2570-11e6-9ac0-de6e3a5612f9.png)

**Comment by fenichelar** [comment]
@JimDalton  Is this still not working? I just rebuilt .93 and it built successfully.

**Comment by JimDalton** [comment]
UI2 error is now 401
![image](https://cloud.githubusercontent.com/assets/18315382/15655937/19c9496e-2670-11e6-9eac-14fc74182b9e.png)
