### ISSUE TITLE
Unable to Login to new UI

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#49]
#### Description of issue
Went to the new user interface on .93.  I saw the navigation bar for the new UI, but the user name password prompt was from the old interface.  I entered ossadmin/ossadmin and got access to the dashboard in an iframe with the new UI nav bar.  Everything looked good.  
Clicked on the triggers link and saw the trigger monitor page in an iframe- everything looked good. 
Clicked on Accounts and got Error 0.  Logged out and got the message that the page refused to connect.  Tried accessing the page with Waterfox. Same message - Unable to connect
![image](https://cloud.githubusercontent.com/assets/18315382/15705937/3f9f949a-27bf-11e6-8fe1-e4f91b98acac.png)
 Waterfox view
![image](https://cloud.githubusercontent.com/assets/18315382/15705974/6a5240f2-27bf-11e6-9d69-0650936a3df9.png)

**Comment by JimDalton** [comment]
I can now access the new user interface.  What changed?
![image](https://cloud.githubusercontent.com/assets/18315382/15712634/1e504a42-27e1-11e6-9b6e-eb3ed128301d.png)

**Comment by fenichelar** [comment]
I triggered a rebuild. The error was not a programming one, it was something with the build or Tomcat. Not sure what fixed it.
