### ISSUE TITLE
No data in CDR report

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#5]
#### Page Title
http://172.16.4.32:7080/analyzer/oss_ta_fss_Fraud_Analytics_for_CDRs_for_Advanced_for_By_Customer_Device_for_Traffic_Pumping_for_Trigger_Report_for_Traffic_Report.htm

#### Legacy URL
http://172.16.4.32:7080/analyzer/oss_ta_fss_Fraud_Analytics_for_CDRs_for_Advanced_for_By_Customer_Device_for_Traffic_Pumping_for_Trigger_Report_for_Traffic_Report.htm

#### New URL
http://172.16.4.93:9080/ui2/Fraud-Control/CDR-Analytics-Advanced/By-Customer-Device/Theft-of-Service/Trigger-Events

#### Description of issue
CDR report appears, but there is no data.  Verified that there is CDR data for the same page in the legacy interface.

Discussed: Normalize CDR url between Trigger reports and Trigger event,  Change detect if link is url or page name

**Comment by fenichelar** [comment]
@JimDalton I have fixed the url issue. Currently there is another issue. If the number of columns in the Excel config is greater than the number of columns of data returned by the server, the row is ignored. All of the rows returned by the server have fewer columns than the Excel config. Everything should work when the config matches the response.

**Comment by fenichelar** [comment]
Fixed.
