### ISSUE TITLE
Trigger Monitors

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#51]
#### Description of issue
viewURL for all trigger events:
`/logs/cgi-bin/action/getLogFile.exe?dir=../../../LOG&file=TriggerMon2.stat`

viewURL can include a search condition and return specific groups of trigger events.
`logs/cgi-bin/action/getLogFile.exe?dir=../../../LOG&file=TriggerMon2.stat&searchKey=.*\tQoS\t.*`
`/logs/cgi-bin/action/getLogFile.exe?dir=../../../LOG&file=TriggerMon2.stat&searchKey=.*\tBilling\t.*`
`/logs/cgi-bin/action/getLogFile.exe?dir=../../../LOG&file=TriggerMon2.stat&searchKey=.*\tFraud Analytics\t.*`
`/logs/cgi-bin/action/getLogFile.exe?dir=../../../LOG&file=TriggerMon2.stat&searchKey=.*\tTraffic Analyzer\t.*`

Column API:
color (green,yellow or red)
recentEventsCount
dayEventsCount
triggerGroup
description
triggerName (unique)
oldTriggerUrl (unique)

**Comment by DmitryIsakbayev** [comment]
The search  key should include * (star) after each dot - searchKey=.*\tQoS\t.*

**Comment by fenichelar** [comment]
Done.

**Comment by JimDalton** [comment]
API changes have been added to Excel Config file.  Need to test.

**Comment by JimDalton** [comment]
Tested /ui2/Dashboard_Monitors_Triggers_Fraud
Go To Page button does not go to Trigger Events page.  It goes to a 404 page.
From the Excel Config file for the Go To Page button.
api = oldTriggerUrl
type = pageLink
uniqueId = /logs/oss_triggermon_config.htm?selectedGroup=Fraud Analytics

![image](https://cloud.githubusercontent.com/assets/18315382/16093932/eb7b9dc0-330b-11e6-858d-0aeeea76d488.png)

**Comment by DmitryIsakbayev** [comment]
The generated URL does not start with /ui2

**Comment by JimDalton** [comment]
Good point.  This problem will be fixed by eliminating the /ui2 which is an improvement.

**Comment by fenichelar** [comment]
Should now support `ui2` if it is added.
