### ISSUE TITLE
? added to uploaded fraud rates file

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#53]
#### New URL
http://172.16.4.93:9080/ui2/Fraud-Control_CDR-Analytics-Basic_Configuration_Fraud-Rates_Manage

#### Description of issue
I uploaded the attached file of fraud rates.  In the upload process, a ? was added to the file.
![image](https://cloud.githubusercontent.com/assets/18315382/15805504/ca367f68-2afa-11e6-83c9-78ef2fc7b226.png)
 
[Fraud Rates.txt](https://github.com/TransNexus/NexOSS/files/299329/Fraud.Rates.txt)

**Comment by fenichelar** [comment]
Is NexOSS adding these?

**Comment by DmitryIsakbayev** [comment]
I don't think so.  These records actually exist in the configuration file.
?+1	0.1200	Undefined_Code.  Could be a misdial or a fraudulent call to an unallocated number.
<feff>+1204     0.0050  Canada - Manitoba Test

**Comment by fenichelar** [comment]
When I download the file and then upload it, everything works as expected. If I modify a row of the file in any way, and then upload it, that row now contains a `?` at the very beginning of the row. Sails is not aware of what has or hasn't changed so I would expect it to add a `?` to every row if Sails was doing it. Also, I was unable to edit rows contain `?` but I could edit rows without the `?`. NexOSS responded that it could not find the row if it started with a `?`.

**Comment by DmitryIsakbayev** [comment]
I can not reproduce it.

**Comment by fenichelar** [comment]
I can't reproduce this anymore.

**Comment by JimDalton** [comment]
The error still occurs for me.  When I upload a rates file with no ?, a ? is added as the first character to the top row.
I also tried the following:
1) Delete the breakout ?+1 and there was a server error.
2) Remove the ? from ?+1 and update the breakout, but there was a server error.

![image](https://cloud.githubusercontent.com/assets/18315382/16094277/777a18fa-330d-11e6-960a-efed5bef13cd.png)

**Comment by DmitryIsakbayev** [comment]
Jim, please provide the file you are trying to upload.

**Comment by JimDalton** [comment]
Hi Dmitry,

 

Here it is.  This is the NANPA template that I downloaded from NexOSS.

 

Thank you,

 

Jim D.

**Comment by DmitryIsakbayev** [comment]
The template file starts with a binary character.  If I view it as a binary file, here is what it looks like.  We need to update the template.

<feff>+1  0.1200  Undefined_Code.  Could be a misdial or a fraudulent call to an unallocated number.^M
+2  0.1200  Undefined_Code.  Could be a misdial or a fraudulent call to an unallocated number.^M
+3  0.1200  Undefined_Code.  Could be a misdial or a fraudulent call to an unallocated number.^M
+4  0.1200  Undefined_Code.  Could be a misdial or a fraudulent call to an unallocated number.^M
+5  0.1200  Undefined_Code.  Could be a misdial or a fraudulent call to an unallocated number.^M
+6  0.1200  Undefined_Code.  Could be a misdial or a fraudulent call to an unallocated number.^M

**Comment by JimDalton** [comment]
Great catch!  How did you find the binary character?  I do not see it.

 

Thank you,

 

Jim D.

**Comment by DmitryIsakbayev** [comment]
In order to see the binary character, I used the vi editor in binary mode (vi -b <file-name-to-view>)

**Comment by fenichelar** [comment]
Is this handled?

**Comment by fenichelar** [comment]
Fixed, needs testing.
