### ISSUE TITLE
New API needed to view chart for concurrent calls report + CDRs view

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#54]
#### Legacy URL
http://172.16.4.32:7080/analyzer/oss_ta_eccs_report_1.htm

#### New URL
http://172.16.4.93:9080/ui2/Traffic-Analyzer_Concurrent-Calls_By-Customer_By-Account

#### Description of issue
172.16.4.32:7080/analyzer/cgi-bin/action/reportToChart.exe?detailLevel=2&file=2016-06-03-20160603155952-ECCS-Source-Time.report&searchKey=.*:Customer-17:.*

[Dmitry wrote] It seems to match the URL in your email.  I suspect the searchKey value is not what the server expects.  We will probably need to implement a new api that can accept the "key" generated for the report viewer in the new UI.

**Comment by DmitryIsakbayev** [comment]
Extended reportToChart controller to support the new searchKey format.  Requires NexOSS - 8.9.18

**Comment by JimDalton** [comment]
Need to Test

**Comment by DmitryIsakbayev** [comment]
Alec, do you think this problem is similar to https://github.com/spring-projects/spring-boot/issues/1583
and the solution might be to set "org.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH" to "true"?

**Comment by fenichelar** [comment]
Yes! You might need to disable url decoding with `UrlPathHelper ` also but maybe not.

**Comment by DmitryIsakbayev** [comment]
Added unix/run/run_tomcat.sh with JAVA_OPTS="-Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true"

That seems to work.

**Comment by DmitryIsakbayev** [comment]
When converting chart uri in the report, it seems like the value for the "detailLevel" variable is not passed correctly.  For the reports by Account, it should be 2.  For the reports by Device, it should be 3.    Is it hard coded to 2? 


report uri:
/analyzer/oss_ta_report_chart.htm?detailLevel=3&file=2016-06-24-20160621131715-ECCD-Dest-Dest-Time.report&searchKey=.*:Logix:T-7100:.*&day=Day+2016-06-24+EDT%28-0400%29&account=Logix&device=T-7100

converted uri:
/analyzer/cgi-bin/action/reportToChart.exe?detailLevel=2&file=2016-06-24-20160621131715-ECCD-Dest-Dest-Time.report&searchKey=.*:Logix:T-7100:.*&day=Day+2016-06-24+EDT(-0400)&account=Logix&device=T-7100

**Comment by fenichelar** [comment]
It is hard coded, I will need to make another mask for that: DETAILMASK

**Comment by fenichelar** [comment]
@JimDalton For `special/concurrentCallsChart.json` and `special/fraudAdvChart.json` please make the following change:

paths.view = `"/analyzer/cgi-bin/action/reportToChart.exe"`

It used to be the same with more text at the end.

**Comment by JimDalton** [comment]
@fenichelar Works as expected.  However, the chart is a little bit too large.  (Screenshot below)  It would be better if the user could see the whole chart within their screen.  Is this possible?

![image](https://cloud.githubusercontent.com/assets/18315382/16462681/48cd1eb4-3e00-11e6-8ea5-3f690f855c6e.png)

**Comment by fenichelar** [comment]
Padding added on sides and bottom.

**Comment by JimDalton** [comment]
Works as expected.
