### ISSUE TITLE
New Replication Status Log file page needed

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#55]
#### Description of issue
Users need a log of replication status so they can verify their changes have been replicated to OSPrey servers.   Messages should log:
1) When a file replication to an OSPrey server IP address begins. 
2) The file name being replicated.  The log message for replicating nexus.cfg should include the additional description of (Least Cost Routing table).
3) When the replication to the OSPrey IP address is completed.
4) Relevant error message if the replication fails

**Comment by DmitryIsakbayev** [comment]
o Added API for replicating configuration and viewing replication progress in NexOSS 8.9.17
      o View URL:           /cgi-bin/data/listServersToPushTo
      o Sample Request URL: /cgi-bin/action/pushConfig?configuration=ROUTING,TRANSLATION&server=1.1.1.1:1080,2.2.2.2:5040
        Server list can include one or more servers.
        Configuration list can include one or more values from: ROUTING TRANSLATION BREAKOUT_CODES SUSPENSIONS
        PEERS CUSTOM_BLACKLISTED_NUMBERS BLACKLISTED_NUMBERS BLACKLISTED_USERAGENTS BLACKLISTED_SUBNETS DID
      o View URL: /logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=RouteProvision.log&searchKey=.*ReplicationQ.*
        It returns a subset of RouteProvison.log file related to replication

**Comment by fenichelar** [comment]
Does `/cgi-bin/data/listServersToPushTo` return a new line or comma separated list? If it is comma, can you make it new line?

**Comment by DmitryIsakbayev** [comment]
new line.

**Comment by fenichelar** [comment]
page.paths.replicationList = /cgi-bin/data/listServersToPushTo
page.paths.replicate = /cgi-bin/action/pushConfig?configuration=ROUTING,TRANSLATION&server=FILTERMASK

**Comment by fenichelar** [comment]
Done.

**Comment by JimDalton** [comment]
Add replicate.description column
Added replication pages for ROUTING, TRANSLATION, DID and PEERS.
Need to test

**Comment by fenichelar** [comment]
I did not add the button tooltip or description support. I will add first thing Monday, should be very quick.

**Comment by fenichelar** [comment]
Done. Please test.
