### ISSUE TITLE
New API to view Customer, Product and Provider rates.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#56]
#### Legacy URL
Provider Rates: /oss_rp_route_plan_rates.htm
Product Rates: /oss_rp_product_rates.htm

Lower Priority Pages:
Customer Rates: /billing/oss_billing_originating_customer_rates.htm
Product Rates: /billing/oss_billing_product_rates.htm
Provider Rates: /billing/oss_billing_terminating_customer_rates.htm

#### Description of issue
Need new API to view rate data on new UI
Question: Is there in difference in the data from Product Rates: /oss_rp_product_rates.htm and Provider Rates: /billing/oss_billing_terminating_customer_rates.htm

**Comment by DmitryIsakbayev** [comment]
Implemented in NexOSS 8.9.17

 o View URL for Customers: /cgi-bin/data/ratedata2.exe?isOriginating=true&type=customer&customerType=.*Orig.*
      o View URL for Products:  /cgi-bin/data/ratedata2.exe?isOriginating=true&type=product
      o View URL for Providers: /cgi-bin/data/ratedata2.exe?isOriginating=false&type=customer&customerType=.*Term.*
      o Column API:
        o level
        o children
        o key
        o {"Home,"Name","Breakout"} (the "Name" label may be replaced with "Customer", "Product" or "Provider")
        o rate
        o grade

**Comment by JimDalton** [comment]
Excel config file has been updated.  Need to test.

**Comment by fenichelar** [comment]
&forKey=FILTERMASK
