### ISSUE TITLE
New Component needed to Provision Calling Number Order

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#57]
#### Legacy URL
/oss_rp_calling_number_source.htm

#### New URL
/ui2/Route-Provisioning_Configuration_Calling-Number

#### Description of issue
The Calling Party number can presented in SIP messages as five different variables and they cal can be different.  Users use this page to provision which SIP calling number should be used by the routing logic.  Need a component that enables users to rank order a list of five variables.

**Comment by JimDalton** [comment]
URIs from java console:
To view data: /cgi-bin/data/callingNumberSourceView
To post data: /cgi-bin/action/callingNumberSourceUpdate?Diversion=1&P-Asserted-Id=2&Remote-Party-Id=3&P-Charge-Info=4&From=5

**Comment by fenichelar** [comment]
@JimDalton Use the following config:

type = rank-viewer
paths.view = /cgi-bin/data/callingNumberSourceView
paths.update = /cgi-bin/action/callingNumberSourceUpdate

**Comment by fenichelar** [comment]
@DmitryIsakbayev I managed to break nexoss. Could you please fix it? The values are being returned as null instead of a number. Thank you.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Resolved.

**Comment by fenichelar** [comment]
@JimDalton Done. Please change config to:

type = rank-viewer
paths.view = /cgi-bin/data/callingNumberSourceView
paths.update = /cgi-bin/action/callingNumberSourceUpdate

and then test.

**Comment by JimDalton** [comment]
Updated Calling Number page.
Need to test

**Comment by JimDalton** [comment]
Works as expected
