### ISSUE TITLE
Need to complete E-mail Configuration Pages

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#60]
#### Legacy URL
/logs/oss_logs_config_email.htm

#### New URL
/ui2/Dashboard_Logs_Email_Configuration

#### Description of issue
No data is in the e-mail config view from the new UI.  Old UI shows complete email config.  The uri on the java console for the old UI is: /analyzer/cgi-bin/data/getReportFile.exe?includeGeneratedOn=true&dir=..%2F..%2F..%2Fetc&file=LoggingAlerts.etc

The paths.view in the config file for the new UI is: /analyzer/cgi-bin/data/getKeyValueInPropertiesFile.exe?dir=..%2F..%2F..%2Fetc&file=LoggingAlerts.etckeyName=PATHMASK
The paths.upload in the new UI is: /analyzer/cgi-bin/action/setKeyValueInPropertiesFile.exe?dir=..%2F..%2F..%2Fetc&file=LoggingAlerts.etc&keyName=PATHMASK

![image](https://cloud.githubusercontent.com/assets/18315382/15806478/3dee2958-2b12-11e6-957a-caa5d2a1f42a.png)

![image](https://cloud.githubusercontent.com/assets/18315382/15806493/458f3152-2b12-11e6-9a8e-478202a80099.png)

**Comment by DmitryIsakbayev** [comment]
The paths are almost correct.  The PATHMASK should be replace with a list of configuration key names specific to each page.  There are 5 sets of key names:

CDRANALYZER_EMAIL_Cc,CDRANALYZER_EMAIL_From,CDRANALYZER_EMAIL_SMTPDebug,CDRANALYZER_EMAIL_SMTPHost,CDRANALYZER_EMAIL_SMTPPassword,CDRANALYZER_EMAIL_SMTPPort,CDRANALYZER_EMAIL_SMTPUsername,CDRANALYZER_EMAIL_Subject,CDRANALYZER_EMAIL_Text,CDRANALYZER_EMAIL_To

ERROR_ALERTS_EMAIL_Cc,ERROR_ALERTS_EMAIL_EmailCountQuotaEnforce,ERROR_ALERTS_EMAIL_EmailCountQuotaIncludeStats,ERROR_ALERTS_EMAIL_EmailCountQuotaMaxPer24Hours,ERROR_ALERTS_EMAIL_EmailCountQuotaMaxPer60Minutes,ERROR_ALERTS_EMAIL_EmailCountQuotaMaxPer60Seconds,ERROR_ALERTS_EMAIL_From,ERROR_ALERTS_EMAIL_SMTPDebug,ERROR_ALERTS_EMAIL_SMTPHost,ERROR_ALERTS_EMAIL_SMTPPassword,ERROR_ALERTS_EMAIL_SMTPPort,ERROR_ALERTS_EMAIL_SMTPUsername,ERROR_ALERTS_EMAIL_Subject,ERROR_ALERTS_EMAIL_To

PREPAID_ALERTS_EMAIL_From,PREPAID_ALERTS_EMAIL_SMTPDebug,PREPAID_ALERTS_EMAIL_SMTPHost,PREPAID_ALERTS_EMAIL_SMTPPassword,PREPAID_ALERTS_EMAIL_SMTPPort,PREPAID_ALERTS_EMAIL_SMTPUsername,PREPAID_ALERTS_EMAIL_Subject,PREPAID_ALERTS_EMAIL_To

TRIGGER_ALERTS_EMAIL_Cc,TRIGGER_ALERTS_EMAIL_From,TRIGGER_ALERTS_EMAIL_SMTPDebug,TRIGGER_ALERTS_EMAIL_SMTPHost,TRIGGER_ALERTS_EMAIL_SMTPPassword,TRIGGER_ALERTS_EMAIL_SMTPPort,TRIGGER_ALERTS_E
MAIL_SMTPUsername,TRIGGER_ALERTS_EMAIL_Subject,TRIGGER_ALERTS_EMAIL_To

TRIGGER_ALERTS_SNMP_LocalIPAddress,TRIGGER_ALERTS_SNMP_LocalTrapSendPort,TRIGGER_ALERTS_SNMP_ManagementHost,TRIGGER_ALERTS_SNMP_ManagementHostTrapListenPort

**Comment by DmitryIsakbayev** [comment]
In the view URL, there should be "&" delimiter between file=LoggingAlerts.etc and keyName=PATHMASK

file=LoggingAlerts.etckey&Name=PATHMASK

**Comment by fenichelar** [comment]
`paths.view` =  `/analyzer/cgi-bin/data/getKeyValueInPropertiesFile.exe?dir=../../../etc&file=LoggingAlerts.etc&keyName=APIMASK`

`paths.upload` = `/analyzer/cgi-bin/action/setKeyValueInPropertiesFile.exe?dir=../../../etc&file=LoggingAlerts.etc&keyName=APIMASK`

**Comment by JimDalton** [comment]
Excel Config file updated with data from Dmitry.  Need to test

**Comment by JimDalton** [comment]
Tested.  Works as expected.
