### ISSUE TITLE
Need Button to generate test e-mail alert

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#61]
#### Legacy URL
/logs/oss_logs_config_email.htm

#### New URL
/ui2/Dashboard_Logs_Email_Configuration

#### Description of issue
Pages for E-mail configuration include a button to generate a test alert.  This button need to be added to the UI page for E-mail configuration.  A screenshot of the old UI shows the Generate Test Alert button at the bottom of the page next to the submit button.
![image](https://cloud.githubusercontent.com/assets/18315382/15806533/26cca2e4-2b13-11e6-94a0-a59ae1e16b08.png)

**Comment by fenichelar** [comment]
Done. Please add the url and test.

**Comment by DmitryIsakbayev** [comment]
/logs/oss_logs_config_email.htm
/analyzer/cgi-bin/action/logMessage.exe?loggerName=TestLogger&message=Test+Error+Message+generated+from+the+Server+%2F+Logs+%2F+Email+page

/analyzer/oss_ta_config_email.htm
/analyzer/cgi-bin/action/logMessage.exe?loggerName=SuspendDeviceAlertLogger&message=Test+Trigger+Alert+generated+from+the+Traffic+Analyzer+or+Fraud+%2F+Configuration%2F+Email+page&mdcCount=1&mdcKey_0=Key-Email-Subject&mdcVal_0=TestAlert

/analyzer/oss_ta_config_snmp.htm
/analyzer/cgi-bin/action/logMessage.exe?loggerName=SuspendDeviceAlertLogger&message=Test+Trigger+Alert+generated+from+the+Traffic+Analyzer+or+Fraud+%2F+Configuration%2F+Snmp+page&mdcCount=1&mdcKey_0=Key-Email-Subject&mdcVal_0=TestAlert

/analyzer/oss_ta_config_snmp.htm
/analyzer/cgi-bin/action/logMessage.exe?loggerName=SuspendDeviceAlertLogger&message=Test+Trigger+Alert+generated+from+the+Traffic+Analyzer+or+Fraud+%2F+Configuration%2F+Email+page&mdcCount=1&mdcKey_0=Key-Email-Subject&mdcVal_0=TestAlert

/analyzer/Fraud_Analytics_for_SIP_for_Basic_for_Configuration_for_SNMP_for_SNMP_for_SNMP.htm
/analyzer/cgi-bin/action/logMessage.exe?loggerName=SuspendDeviceAlertLogger&message=Test+Trigger+Alert+generated+from+the+Traffic+Analyzer+or+Fraud+%2F+Configuration%2F+Snmp+page&mdcCount=1&mdcKey_0=Key-Email-Subject&mdcVal_0=TestAlert

/analyzer/oss_fd_config_email.htm
/analyzer/cgi-bin/action/logMessage.exe?loggerName=SuspendDeviceAlertLogger&message=Test+Trigger+Alert+generated+from+the+Traffic+Analyzer+or+Fraud+%2F+Configuration%2F+Email+page&mdcCount=1&mdcKey_0=Key-Email-Subject&mdcVal_0=TestAlert

/analyzer/oss_fd_config_snmp.htm
/analyzer/cgi-bin/action/logMessage.exe?loggerName=SuspendDeviceAlertLogger&message=Test+Trigger+Alert+generated+from+the+Traffic+Analyzer+or+Fraud+%2F+Configuration%2F+Snmp+page&mdcCount=1&mdcKey_0=Key-Email-Subject&mdcVal_0=TestAlert

/analyzer/oss_report_credit_control_config_email.htm
/analyzer/cgi-bin/action/logMessage.exe?loggerName=PrepaidBillingAlertLogger&message=Test+Billing+Credit+Control+Alert+generated+from+the+Billing+%2F+Prepaid+%2F+Email+page&mdcCount=2&mdcKey_0=Key-Operation&mdcVal_0=TestOperation&mdcKey_1=Key-Account&mdcVal_1=TestAccount

**Comment by JimDalton** [comment]
I have loaded the paths.sendEmail urls listed above to generate e-mail and SNMP messages

I expected to find a paths.sendEmail url for /analyzer/Fraud_Analytics_for_SIP_for_Basic_for_Configuration_for_Email_for_Email_for_Email.htm  This is the E-mail alerts page for SIP Analytics.
I made the assumption that the [Send Message Button] or url, both SIP and CDR fraud analytics are the same.  Dmitry, is this a correct assumption?

Need to test.

**Comment by DmitryIsakbayev** [comment]
Yes

**Comment by JimDalton** [comment]
Two Requirements:
Alec, need a button for paths.sendEmail.  Please label the button "Send Test Message" since this button will apply to E-mail and SNMP messages.

Dmitry, please provide the paths.sendEmail url for /logs/oss_cdranalyzer_config_email.htm

**Comment by fenichelar** [comment]
Jim, I already implemented this. I will update the button message. Let's change the column from `paths.sendEmail` to `paths.sendMessage` to match the use cases.

**Comment by JimDalton** [comment]
Changed paths.sendEmail to paths.sendMessage.  Need to test,

**Comment by DmitryIsakbayev** [comment]
/logs/oss_cdranalyzer_config_email.htm
/analyzer/cgi-bin/action/logMessage.exe?loggerName=TestLogger&message=Test+Error+Message+generated+from+the+Server+%2F+Logs+%2F+Email+page

**Comment by JimDalton** [comment]
Remove trailing space from paths.sendMessage
Add paths.sendMessage for CDRAnalyzer e-mail page
Need to test

**Comment by JimDalton** [comment]
I do not see the button to Send Test Message button the E-mail configuration pages for:
/Fraud-Control_SIP-Analytics-Basic_Configuration_Alerts_Email
/Dashboard_Logs_Email_Configuration

What is the issue?

**Comment by fenichelar** [comment]
I see the buttons on .93 but not on .32. This is because .32 is running an older version of the interface. .32 is also missing the clear and submit buttons. Should be resolved on the next build for .32.

**Comment by fenichelar** [comment]
Please confirm everything is working as expected on .93 and close. I can't tell if the email is actually sent.

**Comment by JimDalton** [comment]
Works as expected.
