### ISSUE TITLE
Change Utilization Column in .res file from Number to Percentage

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#62]
#### Legacy URL
/logs/oss_resources_disk_space.htm

#### New URL
/ui2/Dashboard_Resources_Host-Server_Disk-Space_Table

#### Description of issue
The .res files created by Jinyoun;s application provide utilization data as a number rather than a percentage.  For example, if the utilization percentage is 40%, the data is 40, not 0.40.  It would be better if this data was 0.40 since it would be consistent with other percentage data in NexOSS and could use the type=percentage to put a % sign with the data in the table view.  This is a nice to have feature so if it is requires significant effort it may not be worth the investment.

**Comment by fenichelar** [comment]
The old interface returns a `%` symbol. The type can't be `number` or `percentage` unless the API is changed.

**Comment by DmitryIsakbayev** [comment]
Extended format of memory utilization by application and NexOSS-DIskSpace.res files to include 3 more columns in % format - utilization, warningThreshold and errorThreshold.  NexOSS version 8.9.18.

For utilization in % format, display column 6 instead of column 5.

**Comment by JimDalton** [comment]
Need to test

**Comment by JimDalton** [comment]
Change from column 5 to Column 6

**Comment by fenichelar** [comment]
Duplicate column titles.

**Comment by JimDalton** [comment]
Resource tables with 4 columns appear correct. 

![image](https://cloud.githubusercontent.com/assets/18315382/16483642/5010b78e-3e83-11e6-818b-8c23fe20bd9c.png)

But, resource table for OSPrey monitor has 5 columns and is not correct.
![image](https://cloud.githubusercontent.com/assets/18315382/16483574/0360f368-3e83-11e6-86b4-658ce46132b0.png)

**Comment by DmitryIsakbayev** [comment]
Exctended format of OSPrey-License-Usage.res and Minutes-Processed-Usage.res files to include a new column for utilization in % format.  NexOSS version 8.9.21

**Comment by JimDalton** [comment]
Works as expected.
