### ISSUE TITLE
Implement pages to view NexOSS Product Status & License

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#63]
#### Legacy URL
/oss_rp_product_status.htm

#### Description of issue
Need new component and API to view status of NexOSS routing table being created.
This new component can probably be the same for this page and for the license page which also needs an update button to load a new license

More Detail of NexOSS status page.
view of <SCRIPT LANGUAGE="JavaScript1.2" SRC="/cgi-bin/data/orig-routedataStatus"></SCRIPT> is shown below:
var toHtml = [['text','Status:','Completed'],['text','','Completed'],['text','Breakouts Considered:','100.0%'],['text','','17546448 out of 17546448'],['text','Breakouts Created:','2493331'],['text','Start Time:','Fri Jun 03 19:05:01 EDT 2016'],['text','Stop Time:','Fri Jun 03 19:05:44 EDT 2016'],['text','Current Time:','Sat Jun 04 06:54:41 EDT 2016'],['text','Memory Stats:','used 3.663G out of 17.778G - 20.6% (presized for 7.386G)'],['button','Compact Memory','/cgi-bin/action/runGC']];
![image](https://cloud.githubusercontent.com/assets/18315382/15806875/b56b8d5a-2b1b-11e6-9a96-b0a76ab733e7.png)

**Comment by fenichelar** [comment]
Text viewer with section view.

**Comment by DmitryIsakbayev** [comment]
/oss_rp_product_status.htm
/cgi-bin/data/orig-routedataStatus?useKeyValuePairEncoding=true

**Comment by DmitryIsakbayev** [comment]
/oss_rp_license.htm
http://localhost:7080/cgi-bin/data/licdata.exe?useKeyValuePairEncoding=true&key=MinutesProcessedPerHour&type=number&alias=Minutes_Processed_per_Hour:&key=CallCompletionReports&type=boolean&alias=Allow_Call_Completion_Reports:&key=QoSReports&type=boolean&alias=Allow_QoS_Reports:&key=FraudReports&type=boolean&alias=Allow_Fraud_Reports:&key=FraudPlusReports&type=boolean&alias=Advanced_Fraud_Control:&key=AllowedNexusServers&type=string&alias=Allowed_Nexus_Servers:

**Comment by JimDalton** [comment]
Excel Config file is updated.  Need to test.

**Comment by fenichelar** [comment]
Done.

**Comment by JimDalton** [comment]
Dmitry,
What is the url to upload a license file?  Is it /cgi-bin/action/rates/upload?fileExt=.lic
Also, it would be nice to download a .lic file from the GUI to store.  Is there a uri I can use for paths.download?

Need to add paths.upload to config and then test.

**Comment by DmitryIsakbayev** [comment]
uploadUrl: '/cgi-bin/action/rates/upload?fileExt=.lic'
downloadUrl: 'http://172.16.4.32:7080/logs/cgi-bin/data/getLogFile.exe?dir=../../..&file=NexOSS.lic'

**Comment by JimDalton** [comment]
paths,download in config is:
/logs/cgi-bin/data/getLogFile.exe?dir=../../..&file=NexOSS.lic

But the download button does not work.

**Comment by fenichelar** [comment]
Resolved. Please test.

**Comment by JimDalton** [comment]
Nothing happens when I click the download button.

**Comment by JimDalton** [comment]
Work as expected
