### ISSUE TITLE
Routes Full View

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#64]
#### Description of issue
Data in view and Column titles do not match.
![image](https://cloud.githubusercontent.com/assets/18315382/15825667/af5bab68-2bd2-11e6-8881-657a01d00702.png)

**Comment by fenichelar** [comment]
I am not sure what the issue is? Is the `paths.view` correct?

**Comment by DmitryIsakbayev** [comment]
Updated in NexOSS 8.9.17
