### ISSUE TITLE
Process Monitor

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#67]
#### Legacy URL
/logs/oss_filemon_config.htm

#### Description of issue
   o Extended FileMon to generate FileMon2.stat in NexOSS 8.9.17
      o View URL:   /logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=FileMon2.stat
      o Update URL: /analyzer/cgi-bin/action/setKeyValueInPropertiesFile.exe?dir=../../../etc&file=FileMon.etc&keyPrefix=Application_&keyUniquePart=key&keyName=PATHMASK
      o Column API:
        o key (invisible, the value must come back in the Update URL)
        o status (color, constant)
        o errors (color, constant)
        o name (constant)
        o IsEnabled (boolean)
        o WarningLastModifiedThresholdInMinutes (integer)
        o ErrorLastModifiedThresholdInMinutes (integer)
        o description (constnat)
        o oldLogUrl (constnat, unique, should be mapped to the new url)

**Comment by fenichelar** [comment]
Update URL not working

**Comment by DmitryIsakbayev** [comment]
I expected that the PATHMASK placeholder will be replaced with the actual list of column API names.

**Comment by fenichelar** [comment]
I append `&key=value` to the url where `key` is the `api` from the config and value is the entered data. I do this for every column. So remove `&keyName=PATHMASK` from the url and change `key` to `keyName` in the config.

**Comment by DmitryIsakbayev** [comment]
I need &keyName=IsEnabled,WarningLastModifiedThresholdInMinutes,ErrorLastModifiedThresholdInMinutes

The list must include the column API names of editable values, but it may include all column API names.

**Comment by fenichelar** [comment]
What about the values?

**Comment by JimDalton** [comment]
Change Update URL: /analyzer/cgi-bin/action/setKeyValueInPropertiesFile.exe?dir=../../../etc&file=FileMon.etc&keyPrefix=Application_&keyUniquePart=key&keyName=PATHMASK to 

Update URL: /analyzer/cgi-bin/action/setKeyValueInPropertiesFile.exe?dir=../../../etc&file=FileMon.etc&keyPrefix=Application_&keyUniquePart=key&keyName=APIMASK

This is the only data-viewer page, at this time, that need APIMASK instead of PATHMASK.
For all property-viewer pages, change PATHMASK to APIMASK for all Paths.

**Comment by JimDalton** [comment]
The page looks good, however, I cannot think of a valid use case for the Graph button.  Probably would be better to remove the Graph button from this page if little effort is required.

Bug: Go To Page button leads to 404 page.  Parameters from Excel Config File:
api = oldLogUrl
type = pageLink
uniqueId = /logs/oss_filemon_config.htm

![image](https://cloud.githubusercontent.com/assets/18315382/16095839/6eee731e-3314-11e6-8339-d065641a3c17.png)

**Comment by JimDalton** [comment]
The generated uril does not have /ui2.  Need to remove /ui2 from the navigation of new UI.
