### ISSUE TITLE
Add Wildcard as a dropdown choice for Triggers

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#7]
#### Description of issue
Change NexOSS and edit config file to add wildcard as a dropdown choice on triggers pages for Account (realm for SDReporter), device, calling number and wildcard.

**Comment by DmitryIsakbayev** [comment]
Edit config file - edit columns.X.dropdownUrl for triggers to include &addChoices=Wild%20Card

**Comment by fenichelar** [comment]
&addChoices=Wild%20Card should be added if there are already query parameters in the url, otherwise add ?addChoices=Wild%20Card
