### ISSUE TITLE
Monitors / CDRs Monitor / Skipped CDRs

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#70]
#### Legacy URL
/logs/oss_cdrs_monitor.htm
/logs/oss_resources_chart_skipped_cdrs.htm
/logs/oss_resources_skipped_cdrs.htm

#### Description of issue
The "Skipped CDRs" section of the Monitors / CDRs Monitor page

View URL: /analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=NexOSS-Skipped-CDRs.res
column delimiter - ; (semicolon)
Column API names:
dateTimeStamp,
index -1
index -1
skippedCDRsCount

**Comment by fenichelar** [comment]
@DmitryIsakbayev Could you make the API function like the exchange rate headers? It would look like this:
`key`**\t**`VALUE`**\n**
`key`**\t**`VALUE`**\n**

where `key` is the column name and `value` is the value.

**Comment by DmitryIsakbayev** [comment]
This data-set has multiple rows.

**Comment by JimDalton** [comment]
OK, I will configure this as a new page in the new UI that is a file-viewer.
I will need the paths.list url
