### ISSUE TITLE
Monitors / CDRs Monitor page,  Rejected CDRs section

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#71]
#### Legacy URL
/logs/oss_cdrs_monitor.htm

#### Description of issue

    o Monitors / CDRs Monitor page,  Rejected CDRs section
      o Updated unix/utils/count_rejected_files.py (output LOG/RejectedFiles.stat) to include status color and generate detailed stats even if there are no rejected files
      o Total Count
        o View URL: /analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=RejectedFiles.stat&toLine=1
        o Column API:
          o totalCount
          o recentCount
          o index -1
          o statusColor
      o Detailed By Folder Count
        o View URL: /analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=RejectedFiles.stat&fromLine=2
        o Column API:
          o folderName
          o totalCount
          o recentCount
          o statusColor

**Comment by fenichelar** [comment]
@DmitryIsakbayev Could you make the API function like the exchange rate headers? It would look like this:
`key`**\t**`VALUE`**\n**
`key`**\t**`VALUE`**\n**

where `key` is the column name and `value` is the value.

**Comment by DmitryIsakbayev** [comment]
The data-set for "Detailed by folder count" has multiple rows.

**Comment by JimDalton** [comment]
I entered the url below in Chrome 
o View URL: /analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=RejectedFiles.stat&toLine=1
and received a RejectedFile.stats file with the following data: 
0,0,Wed 13 Jul 2016 15:34:02 EST,green

I think this data can be presented in a page section if it is provided as the following key pairs:
Time = 13 Jul 2016 15:34:02 EST
Total Rejected CDR files = 0
Total CDR files rejected in the last 10 minutes = 0
Status = Green

I entered the url below in Chrome 
http://172.16.4.32:7080/analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=RejectedFiles.stat&fromLine=2
and received a RejectedFile.stats file with only one row of the following data: 
REJECTED,0,0,green

Let's discuss on Friday July 15th.

**Comment by JimDalton** [comment]
The screenshot of the CDRs Monitor page is below.
sections.0  - CDRs in WORK directory is working as expected, except the section title and description are missing.
section.1 - Rejected CDRs details are missing.  Need new API or url.  Also section title and description is missing.
section.2 - Skipped CDRs table looks as expected, except section title and description are missing.

![image](https://cloud.githubusercontent.com/assets/18315382/16820075/41a088ba-491d-11e6-9923-037a45ffa5e3.png)

**Comment by DmitryIsakbayev** [comment]
Please see issue #134 for the updated url (returns data as key/value pairs instead of a single row) for the rejected CDRs.
