### ISSUE TITLE
Drill Down problem on Routes/Full View page

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#72]
#### New URL
http://172.16.4.93:9080/ui2/Route-Provisioning_Least-Cost_Routes_Full-View

#### Description of issue
User can drill down when there is not data to drill down into.  User can drill down when children=false
![image](https://cloud.githubusercontent.com/assets/18315382/16055916/288c933e-3241-11e6-933a-9eacc79a9d8e.png)

**Comment by fenichelar** [comment]
This is being caused by a problem with the JSON converter. Please add the following to every `report-viewer` page:

`columns.0.title` = `level`
`columns.0.order` = `0`
`columns.0.type` = `text`
`columns.0.visible` = `false`

`columns.1.title` = `children`
`columns.1.order` = `1`
`columns.1.type` = `boolean`
`columns.1.visible` = `false`

`columns.2.title` = `key`
`columns.2.order` = `2`
`columns.2.type` = `number`
`columns.2.visible` = `false`

The only change should be adding the `type`.

**Comment by JimDalton** [comment]
Type values for key, level and children have been changed.  Need to test.

**Comment by fenichelar** [comment]
`Route-Provisioning_Least-Cost_Products_Full-View`

key and level have the wrong type, they are opposite.

**Comment by JimDalton** [comment]
Alec, The current config for Route-Provisioning_Least-Cost_Products_Full-View is:
column.0.title = level         column.0.type = text
column.2.title = key           column.2.type = number
Should this be changed to the following?
column.0.title = level         column.0.type = **number**
column.2.title = key           column.2.type = **text**

**Comment by fenichelar** [comment]
Jim,

Yes. For all report pages:

level should be type = number
key should be type =  text
children should be type = boolean

Sincerely,

Alec Ross Fenichel
alec.fenichel@gmail.com
407-760-0036

**Comment by JimDalton** [comment]
For all report-viewer pages:
Change level type from text to number
Change key type from number to text

Need to test

**Comment by DmitryIsakbayev** [comment]
Bug-Fix in Full Products View: the destination level has children (devices). NexOSS - version 8.9.18

**Comment by JimDalton** [comment]
Drill down past device is possible which is not correct.  Dmitry will modify children.
Change page to display loadding while updating view for drill down,

**Comment by DmitryIsakbayev** [comment]
The children value for level 4 (Devices) of the product view is already false.  
Sample Request - /cgi-bin/data/orig-routedataFullView2?forKey=Products;Dall_Eacs_Nxx_Intra;1903201;IntraLATA_Tandem;Tandem_903
Response:
4	false	Products%3BDall_Eacs_Nxx_Intra%3B1903201%3BIntraLATA_Tandem%3BTandem_903%3BNPA_903_Tandem	NPA_903_Tandem	0.01	0.005	0.5				1	false

**Comment by fenichelar** [comment]
I think it was another issue and is resolved. Please test.
