### ISSUE TITLE
 Monitors / CDRs Monitor page,  CDRs in WORK directory section 

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#73]
#### Legacy URL
/logs/oss_cdrs_monitor.htm

#### Description of issue

      o Updated unix/utils/count_cdr_files.py (output LOG/CDRsInWorkFolder.stat) to include warning and error threholds and status color
        o View URL: /analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=CDRsInWorkFolder.stat&fromLine=2
        o Column API:
          o ageOfOldestFile (in minutes)
          o index -1
          o numberOfFiles
          o warningThreshold (in minutes)
          o errorThreshold (in minutes)
          o statusColor

**Comment by JimDalton** [comment]
I have implemented the CDRs in WORK directory data.  
But I think we need a new component to show Rejected and Skipped CDRs.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Could you make the API function like the exchange rate headers? It would look like this:
`key`**\t**`VALUE`**\n**
`key`**\t**`VALUE`**\n**

where `key` is the column name and `value` is the value.

**Comment by DmitryIsakbayev** [comment]
Extended getFile API to suipport key/value pair encoding using "useKeyValuePairEncoding","tokenDelimiter" and "keyNames" parameters.  Requires NexOSS 8.9.23

Updated View URL: `/analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=CDRsInWorkFolder.stat&fromLine=2&useKeyValuePairEncoding=true&tokenDelimiter=,&keyNames=Age_Of_Oldest_File,SKIP,Number_Of_Files,Warning_Threshold,Error_Threshold,Status_Color`

**Comment by JimDalton** [comment]
When I put the View URL in Chrome I get a file with the following data:
3,WORK,6,10,30,green
I think we need this data in the format of key value pairs so it can be implemented in a section view. 
Please provide the column order when you provide a view url.  If I have to make assumptions on data order it increases the possibility of errors and delays our progress.

This information will be in one of three section views on single page that provides a summary view of CDR stats.

In the Old UI, three data views are shown.
1) CDRs in the WORK directory
2) Rejected CDRs
3) Skipped CDRs

![image](https://cloud.githubusercontent.com/assets/18315382/16806463/96ca4b72-48e2-11e6-9cc5-845ef53c193d.png)

**Comment by DmitryIsakbayev** [comment]
The new URL should start returning data in key/value pair format after we upgrade lab to NexOSS 8.9.23

**Comment by JimDalton** [comment]
Need to test

**Comment by JimDalton** [comment]
Sections.0 which presents information on the CDRs in the WORK folder is working as expected

![image](https://cloud.githubusercontent.com/assets/18315382/16819985/dcf0d2d0-491c-11e6-8ec9-6763b57281f1.png)
