### ISSUE TITLE
Cannot Drill Down on Concurrent Calls Page

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#74]
#### New URL
http://172.16.4.93:9080/ui2/Traffic-Analyzer_Concurrent-Calls_By-Customer_By-Device

#### Description of issue
Cannot drill down from the top row of the report.
![image](https://cloud.githubusercontent.com/assets/18315382/16094482/736c50d8-330e-11e6-934b-82747b78a08e.png)

**Comment by fenichelar** [comment]
Fixed.
