### ISSUE TITLE
Cannot Disable Call Completion Reports - API columns needed for Excel Config.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#75]
#### Page Title
Enable and Disable Traffic Analyzer and QoS Reports

#### Legacy URL
/analyzer/Traffic_Analyzer_for_Traffic_Analyzer_for_Traffic_Analyzer_for_Configuration_for_Reports_for_Reports_for_Reports.htm

#### New URL
/Traffic-Analyzer_Configuration_Reports

#### Description of issue
The page to disable call completion reports only has Reports for concurrent calls (5 reports).  There should be a list of 37 reports that can be disabled.  Dmitry, the original configuration file you sent to me is attached.  Please identify the APIs for the remaining 32 columns.
[property-editor-configuration.txt](https://github.com/TransNexus/NexOSS/files/319213/property-editor-configuration.txt)

![image](https://cloud.githubusercontent.com/assets/18315382/16131308/936ea110-33db-11e6-980e-de5014b235b4.png)

**Comment by DmitryIsakbayev** [comment]
[property-editor-configuration-for-traffic-analyzer-reports.txt](https://github.com/TransNexus/NexOSS/files/332646/property-editor-configuration-for-traffic-analyzer-reports.txt)

**Comment by JimDalton** [comment]
Added columns to config file.
Need to test.

**Comment by JimDalton** [comment]
Works as expected.
