### ISSUE TITLE
Change build script

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#76]
#### Description of issue
Change build script for Sails. Instead of `npm start` please use `npm start -- -p`.

**Comment by DmitryIsakbayev** [comment]
We currently use "npm start --log" 
What does "-- -p" do?

**Comment by fenichelar** [comment]
Production mode.

**Comment by DmitryIsakbayev** [comment]
Changed

**Comment by DmitryIsakbayev** [comment]
Changed
