### ISSUE TITLE
Implement Manual Rate Plan Provisioning Pages

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#77]
#### New URL
paths.downloadFile = /logs/cgi-bin/data/getLogFile.exe?dir=../../../RATING_TEMPLATES&file=Provider_Rate_Plan_Template_example.ProviderRP.xls
 for Excel 2003 Rate Plan Template

#### Description of issue
Need to download a template and upload Excel rate plan file.
text-viewer with (to be determined) and paths.upload = /cgi-bin/action/rates/upload?fileExt=.ProviderRP.txt

**Comment by fenichelar** [comment]
Will use markdown for download links.

**Comment by JimDalton** [comment]
@fenichelar What is ?token=TOKEN)?  What should I enter for TOKEN?
My understanding is these templates will be stored on sails.js.  Do you need copies of the template files?
Also, I think the java webstart applications will be stored on sails.js.  Do you need a copy of that file?  These files can be downloaded from the legacy UI.

**Comment by JimDalton** [comment]
Here are the links to download the provider rate templates.
/logs/cgi-bin/data/getLogFile.exe?dir=../../../RATING_TEMPLATES&file=Provider_Rate_Plan_Template_example.ProviderRP.xls
/logs/cgi-bin/data/getLogFile.exe?dir=../../../RATING_TEMPLATES&file=Provider_Rate_Plan_Template_example.ProviderRP.xlsx"
/logs/cgi-bin/data/getLogFile.exe?dir=../../../RATING_TEMPLATES&file=Provider_Rate_Plan_Template_example.ProviderRP.txt

Will each of these files have a different TOKEN?

**Comment by JimDalton** [comment]
@fenichelar  I want to add a link in the Markdown text box that will download the rate provisioning tool - a .jsp file.  In the old UI the link is: /lib/NexOSS_rate_provisioning_tool.jsp.  The Markdown editor is expecting http:// and then the link.  Can I use http:///lib/NexOSS_rate_provisioning_tool.jsp?  This does not seem correct?  How do I include the IP address for the local server?

![image](https://cloud.githubusercontent.com/assets/18315382/17973578/feec1e02-6ab0-11e6-82bb-39ab6cee19ab.png)

**Comment by JimDalton** [comment]
@DmitryIsakbayev   This is a question about uploading rate plans.  In the old UI I see the following:
<FORM METHOD=post ACTION='/cgi-bin/action/rates/upload?fileExt=.cxr.txt' ENCTYPE='multipart/form-data'>

What part of this command should be configured to the button to upload a rate plan (paths.upload)?  Is the following what I should configure for paths.upload?
'/cgi-bin/action/rates/upload?fileExt=.cxr.txt' ENCTYPE='multipart/form-data'

**Comment by DmitryIsakbayev** [comment]
Yes, for the exchange rates.

**Comment by JimDalton** [comment]
Changes have been made.  Need to test after .jsp file have been moved from sails.js to NexOSS.

**Comment by JimDalton** [comment]
@fenichelar Question, The Rate Provisioning Tool files (.jsp) will be kept on NexOSS, not sails.js.  What do I enter in the Markdown file as the path to the .jsp file?  The path in the old interface is /lib/NexOSS_rate_provisioning_tool.jsp.

**Comment by JimDalton** [comment]
This issue is being closed.  It is redundant to issue 205
