### ISSUE TITLE
Diversion Devices - Is a new component needed?

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#79]
#### Legacy URL
/analyzer/Fraud_Analytics_for_SIP_for_Basic_for_Configuration_for_Diversion_for_Diversion_for_Diversion.htm
![image](https://cloud.githubusercontent.com/assets/18315382/16173157/69f700ac-3566-11e6-863e-77fcb09020da.png)

#### Description of issue
Can this page be implemented with an existing component?  If so, which one.  I need the dropdown urls to configure.

**Comment by fenichelar** [comment]
data-viewer. 4 columns each of type dropdown. I am not sure what the urls and apis would be.

**Comment by DmitryIsakbayev** [comment]
Alec, can the UI support two dependencies?
"Primary Diversion Device"   depends on "Group Of Primary Diversion Device"
"Secondary Diversion Device" depends on "Group Of Secondary Diversion Device"


viewUrl:     /cgi-bin/data/diversionGrpData.exe
updateUrl:   /cgi-bin/action/diversionGrpUpdate

Column API
column:      0
title:       Block Blacklisted Numbers
name:        isBlockBlacklistedNumbers
type:        boolean
isVisible:   false

column:      1
title:       Group Of Primary Diversion Device
name:        diversionGroupPrimary
type:        dropdown
dropdownUrl: /cgi-bin/data/grpdata2.exe?type=customer&customerType=.*Term.*

column:      2
title:       Primary Diversion Device
name:        diversionDevicePrimary
type:        dropdown
dropdownUrl: /cgi-bin/data/devicesForProvider.exe?provider=PATHMASK
dependency:  Group Of Primary Diversion Device

column:      3
title:       Group Of Secondary Diversion Device
name:        diversionGroupSecondary
type:        dropdown
dropdownUrl: /cgi-bin/data/grpdata2.exe?type=customer&customerType=.*Term.*

column:      4
title:       Secondary Diversion Device
name:        diversionDeviceSecondary
type:        dropdown
dropdownUrl: /cgi-bin/data/devicesForProvider.exe?provider=PATHMASK
dependency:  Group Of Secondary Diversion Device

**Comment by fenichelar** [comment]
I believe so. It should also be able to handle a dependency tree: Z depends on Y and Y depends on X.

**Comment by JimDalton** [comment]
Added configuration for Diversion Devices for SIP and CDR fraud detection.
Need to test.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Can you please make the update API return the updated data? The update function expects the data to be returned, so it currently says "Something went wrong" but it actually works.

**Comment by DmitryIsakbayev** [comment]
Will do in the next release - 8.9.20

**Comment by JimDalton** [comment]
When Diversion Account is deleted, the the Diversion Device should be deleted.  This is a general issues, a dependent value should be deleted when the value it depends on is deleted or changed.

**Comment by fenichelar** [comment]
Resolved, please test after next build.

**Comment by JimDalton** [comment]
Alec,
I did an pull and update on .93 using the links you provided:
http://172.16.4.93:9080/api/git/pull?username=ossadmin&password=ossadmin
http://172.16.4.93:9080/api/git/update?username=ossadmin&password=ossadmin

When I test, I see that the dependent device remains after the Diversion account has been deleted.  For example in the following screenshot, the Diversion Account has been deleted, by the device remains.  If I click on Submit the Diversion Account is not removed.
![image](https://cloud.githubusercontent.com/assets/18315382/16597339/556c8b76-42c6-11e6-9967-c6af2e004f6d.png)

**Comment by fenichelar** [comment]
@JimDalton The change will require a complete rebuild. The urls provided are only capable of updating the JSON files based on config file changes. You should see the changes tomorrow.

**Comment by JimDalton** [comment]
Deleting a Diversion Device did not work as expected.
![image](https://cloud.githubusercontent.com/assets/18315382/16663682/07779b78-444b-11e6-89ce-98a81d41f652.png)

**Comment by fenichelar** [comment]
Please test again.

**Comment by JimDalton** [comment]
Works as expected.
