### ISSUE TITLE
 unable to assign a dial-plan

### ISSUE THREAD

**Issue by txnx-will** [TransNexus/NexOSS#85]
#### Description of issue
I was expecting to see a drop-down for the “Customer Account” field.

![image](https://cloud.githubusercontent.com/assets/14878395/16346253/4d502570-3a14-11e6-874a-2b7cac661c9f.png)

**Comment by DmitryIsakbayev** [comment]
API Column "Customer Account" should have
type="dropdown"
dropdownUrl="/cgi-bin/data/grpdata2.exe?type=customer&customerType=.*Orig.*"

**Comment by fenichelar** [comment]
Please test.

**Comment by JimDalton** [comment]
Works as expected
