### ISSUE TITLE
Add authentication GUI

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#88]
- [x] Setup Sails API
- [x] Setup Ember interface
- [x] Fix build script

**Comment by fenichelar** [comment]
Please test.

**Comment by JimDalton** [comment]
I logged in as a view only user for number translation.  I went to number translation.  The Add and Update buttons were not available as expected, but the Upload button was available and gave me access to upload a new Number Translation configuration file.  The upload button should be disabled for read only users.

**Comment by JimDalton** [comment]
Read Only users should not see the following buttons:
paths.upload
paths.add
paths.update
paths.delete
paths.deleteFile
paths.sendMessage
paths.replicate	
paths.rateSkippedCDRs

**Comment by fenichelar** [comment]
delete file.paths.add;
delete file.paths.update;
delete file.paths.delete;
delete file.paths.upload;
delete file.paths.deleteFile;
delete file.paths.replicate;
delete file.paths.exportRatePlan;
delete file.paths.rateSkippedCDRs;
delete file.paths.sendMessage;

Resolved as above. Please test.

**Comment by fenichelar** [comment]
@JimDalton What needs to be done?
