### ISSUE TITLE
Dashboard links

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#89]

**Comment by fenichelar** [comment]
@DmitryIsakbayev Can you please create another reverse proxy that goes from `hostname:9080/java/**` to `hostname:7080/**`. I need this to change the links on the iframe dynamically.

**Comment by DmitryIsakbayev** [comment]
Please test.

**Comment by DmitryIsakbayev** [comment]
Good catch.  It was redirecting to :1337/java instead of :7080/.
Please test again.  There is a test NexOSS running on .93.

**Comment by fenichelar** [comment]
It seems to be doing a redirect instead of a reverse proxy. When I go to `http://172.16.4.93:9080/java` it redirects the browser to `http://localhost:7080/index.htm`.

**Comment by DmitryIsakbayev** [comment]
Maybe it is because the (NexOSS) web-server redirects you to the default page.

If you ask for a specific page it seems to work as expected -

$ wget --user=xxxxxxx --password=xxxxxx http://172.16.4.32:9080/java/index.htm
--2016-06-28 15:24:16--  http://172.16.4.32:9080/java/index.htm
Connecting to 172.16.4.32:9080... connected.
HTTP request sent, awaiting response... 401 Unauthorized
Connecting to 172.16.4.32:9080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: “index.htm”

    [ <=>                                                                                                                                                                                                                                                                               ] 152         --.-K/s   in 0s      

2016-06-28 15:24:17 (16.2 MB/s) - “index.htm” saved [152]

**Comment by fenichelar** [comment]
@DmitryIsakbayev Can you please enable rewriting: http://j2ep.sourceforge.net/docs/rewrite.html. We will also need absolute link rewriting. `data.xml (config file)` says how to enable absolute link rewriting.

**Comment by DmitryIsakbayev** [comment]
Not working yet.  I have tried to follow the documentation - 
using the web_rewriting.xml instead of the default web.xml
added isRewriting="true" property to the server element of the config/data.xml file.

**Comment by DmitryIsakbayev** [comment]
In order to turn on URL rewriting for the :9080/java <-> :7080/, redeployed the proxy @ /java in the ROOT context.
The ROOT context now combines the proxy filter for /java and push-state filter for /index.html

Please test.

**Comment by fenichelar** [comment]
`http://172.16.4.32:9080/java/logs/oss_dashboard_init.htm`
Does not work as expected. Interesting errors.

**Comment by DmitryIsakbayev** [comment]
[diff.txt](https://github.com/TransNexus/NexOSS/files/381817/diff.txt)

Alec, the attached file compares files directly pulled from NexOSS and via the proxy.
The htm files look ok to me.
I think the change in nexoss-8.9.20-nexoss.js can be ignored because it is in a function that is not used in this page.
What do you think about other changes?

**Comment by fenichelar** [comment]
Unfortunately, the error breaks the entire page for me. I understand what is going on though so I might be able to change the file so that the rewrite engine understands what to do and it is backwards compatible. Where should I make/test the changes to `nexoss-8.9.20-nexoss.js`?

**Comment by DmitryIsakbayev** [comment]
You can use .32 (the version in the file name will be different)

**Comment by fenichelar** [comment]
@DmitryIsakbayev I changed the following files:

- `oss_dashboard.js`
- `nexoss-8.9.27-nexoss.js`
- `bootstrap-3.1.1.js`

The changes do not break nexoss.

**Comment by DmitryIsakbayev** [comment]
Will include the updated files in the next release - 8.9.28

**Comment by fenichelar** [comment]
Thanks.

**Comment by fenichelar** [comment]
Needs testing. Build on .93 needs to be moved to .32 for testing. Will not work on .93.

**Comment by JimDalton** [comment]
Dashboard links give 404
![image](https://cloud.githubusercontent.com/assets/18315382/17335614/8d12a11c-58a8-11e6-8ae9-086b95653c50.png)

**Comment by fenichelar** [comment]
@txnx-will Debug code added. Please update .32 after tomorrow's build for testing.

**Comment by fenichelar** [comment]
Fix implemented (hopefully). Newest build needs to be tested on .32.

**Comment by fenichelar** [comment]
Fix unsuccessful. Investigating.

**Comment by JimDalton** [comment]
The more important goal is to eliminate the iframe and have a better dashboard.  It is OK with me to implement a manual work around to get past this problem.

**Comment by fenichelar** [comment]
@DmitryIsakbayev I am giving up on this approach as the dashboard will be replaced in the near future. I will duplicate `/logs/oss_dashboard_init.htm` and make `/logs/oss_dashboard_ui2.htm` with the changes for the links. I will make the changes on .32 and let you know when they are complete.

@JimDalton please change the `path` for dashboard from `/logs/oss_dashboard_init.htm` to `/logs/oss_dashboard_ui2.htm`.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Done. The following files were created, no other files were edited:

- `/home/ossadmin/OSS/nexoss/WebServer/webapps/ROOT/scripts/oss_dashboard_ui2.js`
- `/home/ossadmin/OSS/nexoss/WebServer/webapps/logs/oss_dashboard_init.htm`

**Comment by JimDalton** [comment]
Changed the path for dashboard from /logs/oss_dashboard_init.htm to /logs/oss_dashboard_ui2.htm in config file.

**Comment by DmitryIsakbayev** [comment]
@fenichelar do you mean oss_dashboard_ui2.htm?

**Comment by fenichelar** [comment]
@DmitryIsakbayev Yes.

**Comment by DmitryIsakbayev** [comment]
Included in version 8.9.30

**Comment by fenichelar** [comment]
Completed. Ready for testing.

**Comment by JimDalton** [comment]
Tested version 8.9.30 on .32.  Dashboard links did not work.
![image](https://cloud.githubusercontent.com/assets/18315382/17634180/520d3fec-609f-11e6-8c25-ba041ae17a79.png)
