### ISSUE TITLE
Dashboard / Monitors / Resource Monitor 

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#90]
#### Page Title
Dashboard / Monitors / Resource Monitor 

#### URL
Old URL: /logs/oss_resource_monitor.htm

#### Description of issue
New API in NexOSS 8.9.19
      o View URL: `/analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=ResourceUtilizationSummary.stat`
      o Column API:
        o group
        o statusColor
        o utilization
        o thresholdWarning
        o thresholdError
        o name
        o description
        o linkToDetailsPage

**Comment by JimDalton** [comment]
Entered into config file. Need to test

**Comment by JimDalton** [comment]
Works as expected
