### ISSUE TITLE
Charting disk TPS 

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#91]
#### Description of issue
viewUrl: `/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=NexOSS-Nex-Stat.res&searchKey=.*HOST_TOTAL_IOSTAT_TPS.*`

Column API:
dateTimeStamp
order =-1
order =-1
order =-1
tps

**Comment by JimDalton** [comment]
Added to the config file.  Need to test.

Should there also be a paths.list?  In the old UI, the user can look a history of .res files.

**Comment by DmitryIsakbayev** [comment]
Here is the paths.list -
paths.list = `/logs/cgi-bin/data/listLogFiles.exe?dir=../../../LOG&fileMask=NexOSS-Nex-Stat.res.*`

The path.view should be updated to use the PATHMASK placeholder instead of the actual file name
path.view - `/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*HOST_TOTAL_IOSTAT_TPS.*`

**Comment by JimDalton** [comment]
Works as expected.
