### ISSUE TITLE
Add Support for IP Range Calculation

### ISSUE THREAD

**Issue by fenichelar** [TransNexus/NexOSS#92]

**Comment by fenichelar** [comment]
Please test.

**Comment by fenichelar** [comment]
@JimDalton The following changes need to be made in the config:

- Change type of `Subnet IP Address` column to `columns.x.type = subnetIPaddress`
- Add `columns.x.dependency = IP Bit Mask` to `Subnet IP Address` column
- Add `columns.x.disallowClear = true` to `IP Bit Mask` column
- Swap `columns.x.order` of `IP Bit Mask` and `Subnet IP Address` columns

**Comment by JimDalton** [comment]
Config changes have been made.
Need to test

**Comment by JimDalton** [comment]
Alec, I made the changes, but the subnet table does not load on .32.

![image](https://cloud.githubusercontent.com/assets/18315382/17380088/43d4f1ee-5993-11e6-8eeb-6473dcbc6571.png)

**Comment by fenichelar** [comment]
@JimDalton, resolved. Latest build on .93 works as expected.

**Comment by JimDalton** [comment]
This feature works as expected.  
As a future enhancement, we may add the Subnet IP range to the table view.  This would be consistent with the legacy UI and more useful for users.
