### ISSUE TITLE
NexOSS Database Data File page

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#93]
#### URL
Old interface: /logs/oss_resources_nexoss_db_status.htm

#### Description of issue
Low Priority because iframe page works well. 
May need new component for this page or make two new pages: one showing that data file size and a second page with database tables information.
![image](https://cloud.githubusercontent.com/assets/18315382/16496982/b815f54e-3ec2-11e6-95ec-8da8385237db.png)

**Comment by fenichelar** [comment]
@DmitryIsakbayev Could you make the API work similar to the rest of the pages when you get a chance?

**Comment by JimDalton** [comment]
Dmitry,

Please review the requirements below and let me know if you can create paths.view uris that make the requested information available.  We should discuss with Alec before we implement.

I think we need to split Resources / Database Space page into two pages.  The first page would be a table of just Data File space.  I think we just need seven columns for the data file page:
1) Date-Time Stamp
2) Total Gigabytes of free space in the data file
3) Total Gigabytes of space filled with data in the data file.
4) Total size of the data file in gigabytes
5) Percent of the total data file that is free (free space /(free space + used space))
6) Percent of the total data file that is filled with data (used space /(free space + used space))
7) 100 Percent.  This value is constant and adds no value for the table, but is useful if the data is charted.
Is an API for this data possible?

For the Table data page, We need a table with the following columns:
1) Table type (Rate, CDR, Credit Control, Other)
2) Table Name (e.g. REACDR)
3) Number of Rows (The current count of the number of rows in the table)
4) History (Link to another page that is a table view the historical row count of the selected table)
         Columns for the linked History page:
         1) Date-Time Stamp when row count was made
         2) Number of rows

**Comment by DmitryIsakbayev** [comment]
The NEXOSS_STATUS_TB table stores stats about datafiles and rowcounts.
The OSS_Updated column stores the time-stamp when the data was gathered.
There are columns for each table that we track rowcounts - ACDR, REACDR, RATEDCDR, etc
We don't have "Table Type" information.
 

`CREATE TABLE NEXOSS_STATUS_TB (
    OSS_Updated                     TIMESTAMP,
    OSS_DbTotal                     VARCHAR(16),
    OSS_DbUsed                      VARCHAR(16),
    OSS_DbFree                      VARCHAR(16),
    OSS_DbPartitionTotal            VARCHAR(16),
    OSS_DbPartitionFree             VARCHAR(16),
    ACCOUNTINVOICE                  VARCHAR(16),
    ACDR                            VARCHAR(16),
    ACDR_EXT_RULES                  VARCHAR(16),
    ARCHIVEDRATEDCDR                VARCHAR(16),
    ARCHIVEDREPORTABLECDR           VARCHAR(16),
    ARCHIVED_RATED_CDR_RULES        VARCHAR(16),
    ARCHIVED_REPORTABLE_CDR_RULES   VARCHAR(16),
    BILLING_SUSPEND_FILTER          VARCHAR(16),
    CDR_FILE_AUDIT                  VARCHAR(16),
    CONFIGUPDATEQUEUE               VARCHAR(16),
    CREDITSTATUS                    VARCHAR(16),
    CURRENCY                        VARCHAR(16),
    DESTINATION                     VARCHAR(16),
    EACDR_FILTER_RULES              VARCHAR(16),
    EXCHANGERATE                    VARCHAR(16),
    EXCHANGERATEDATA                VARCHAR(16),
    EXECUTEREPORTQUEUE              VARCHAR(16),
    EXECUTESQLQUEUE                 VARCHAR(16),
    EXPORTRATEPLANQUEUE             VARCHAR(16),
    EXTRA_SUSPEND_FILTER            VARCHAR(16),
    ICDR                            VARCHAR(16),
    RATEDCDR                        VARCHAR(16),
    RATEPLAN                        VARCHAR(16),
    RATEPLANDATA                    VARCHAR(16),
    REACDR                          VARCHAR(16),
    REACDR_TO_VENDOR_RULES          VARCHAR(16),
    REINVOICEQUEUE                  VARCHAR(16),
    REPORTABLECDR                   VARCHAR(16),
    REPORTQUEUE                     VARCHAR(16),
    RERATEQUEUE                     VARCHAR(16),
    SEACDR                          VARCHAR(16),
    STATUS_TB                       VARCHAR(16),
    TIER                            VARCHAR(16)
);`

**Comment by JimDalton** [comment]
Hello Dmitry,

 

I think the requirement for the Data file space page can be partly fulfilled with a paths.view url that returns the following six columns of data.

OSS_Updated TIMESTAMP,
OSS_DbTotal VARCHAR(16),
OSS_DbUsed VARCHAR(16),
OSS_DbFree VARCHAR(16),
OSS_DbPartitionTotal VARCHAR(16),
OSS_DbPartitionFree VARCHAR(16),



However, I am assuming that the values returned are gigabytes.  For users, it is easier to think, and set alarms for, values in percent utilization.  Is it possible to return % database file utilization  and % Partition utilization?

**Comment by DmitryIsakbayev** [comment]
The SQL statement for Data File space would be -

`select
OSS_Updated,
OSS_DbFree,
OSS_DbUsed,
OSS_DbTotal,
OSS_DbFree / (OSS_DbFree + OSS_DbUsed),
OSS_DbUsed / (OSS_DbFree + OSS_DbUsed),
100
from NEXOSS_STATUS_TB`

viewUri: `/analyzer/cgi-bin/data/downloadTable.exe?sql=select OSS_Updated,OSS_DbFree,OSS_DbUsed,OSS_DbTotal,OSS_DbFree/(OSS_DbFree+OSS_DbUsed),OSS_DbUsed/(OSS_DbFree+OSS_DbUsed),100 from NEXOSS_STATUS_TB order by OSS_Updated DESC order by OSS_Updated DESC`

**Comment by DmitryIsakbayev** [comment]
For the Table data page, we can get summary for each table using a query like.  For the REACDR table the summary sql is

`select
'REACDR',
REACDR,
'LinkToDetailsForREACDR'
from NEXOSS_STATUS_TB
where OSS_Updated = (select max(OSS_Updated) from NEXOSS_STATUS_TB)`


and historical sql is 

`select
OSS_Updated,
REACDR
from NEXOSS_STATUS_TB
order by OSS_Updated DESC'

I am not sure how to generate a data-set that would include summary for all tables.

**Comment by JimDalton** [comment]
This issue has been closed an re-opened as two different issues for simpler tracking
