### ISSUE TITLE
Chart for Disk Space Usage - Time Stamp column in table does not sort as expected.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#94]
#### Page Title
Disk Space Utilization Log

#### URL
Old UI:/logs/oss_resources_disk_space.htm
New UI: /Dashboard_Resources_Host-Server_Disk-Space_Table

#### Description of issue
Please see the chart below.  You will notice that it is perfectly symmetric.  If you look at the time stamps you will notice that the time stamps start at 2016-06-28 and then increase as you move from right along the X-axis until the time stamps become 2016-06-30 13:10:00 in the middle of the chart.  From there, the time stamps decrease and the data at the far right of the chart is 2016-06-28.

You see the same when you look at the table data.  This table has been sorted by time stamp so the problem appears to the table sorting, not the charting function.  Any ideas about what is happening?  
![image](https://cloud.githubusercontent.com/assets/18315382/16497352/6d014a34-3ec4-11e6-9111-cca48db4c8b3.png)

**Comment by fenichelar** [comment]
Resolved.
