### ISSUE TITLE
Fraud Analytics / SIP / Basic / Blacklisted User Agents / Custom List

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#95]
#### Description of issue
New API:
viewUrl: `/analyzer/cgi-bin/data/viewCodes.exe?setKey=CustomBlacklistedUserAgents`
addUrl: `/analyzer/cgi-bin/action/addCode.exe?setKey=CustomBlacklistedUserAgents`
updateUrl: `/analyzer/cgi-bin/action/updateCode.exe?setKey=CustomBlacklistedUserAgents`
deleteUrl: `/analyzer/cgi-bin/action/deleteCode.exe?setKey=CustomBlacklistedUserAgents`
uploadUrl: `/analyzer/cgi-bin/action/updateCodes.exe?setKey=CustomBlacklistedUserAgents`

Columns 0:
 title: User Agent
 api: code

Columns 1:
 title: Check = Blacklist No Check = Whitelist
 api: label
 type: boolean

Columns 2:
 title: Comment
 api: comment

**Comment by JimDalton** [comment]
Add page for Blacklisted User Agent Custom List.   Need to test.
Remove all paths to add, change or delete the existing blacklisted user agent list.  This page will become a static list that is provided by TransNexus.

**Comment by fenichelar** [comment]
Please change column 1 title to `Blacklist User Agent`

**Comment by JimDalton** [comment]
Works as expected
