### ISSUE TITLE
Resources / Host Server / utilization pages

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#96]
#### Description of issue
Dmitry,

I need help with the following pages that are presented in the old UI as charts only, with no tables.

I think I need the paths.view and paths.list urls and all the columns data.

Chart-Total CPU				/logs/oss_stats_chart_cpu_utilization.htm
Chart CPU used by Applications		/logs/oss_stats_chart_cpu_alarm.htm
Chart-Total Memory			/logs/oss_stats_chart_mem_utilization.htm
Chart-Memory used by Applications	/logs/oss_stats_chart_mem_alarm.htm
Swap Space				/logs/oss_stats_chart_mem_swap.htm
NexOSS Webserver CPU		/logs/oss_stats_chart_nexoss_cpu.htm
NexOSS Webserver Memory		/logs/oss_stats_chart_nexoss_mem.htm

**Comment by DmitryIsakbayev** [comment]
It is similar to "Charting disk TPS".  The data is in the same file, only the searchKey value is specific to each chart.

The paths.list is the same for all pages.
paths.list = `/logs/cgi-bin/data/listLogFiles.exe?dir=../../../LOG&fileMask=NexOSS-Nex-Stat.res.*`

NexOSS Webserver CPU
path.view - `/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*NexOSS_Webserver_CPU.*`

NexOSS Webserver Memory
path.view - `/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*NexOSS_Webserver_Memory.*`

Swap Space
path.view - `/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*NexOSS_Swap.*`

Chart-Total CPU
path.view - `/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*NexOSS_CPU_Alarm.*`

Chart-Total Memory
path.view - `/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*NexOSS_Memory_Alarm.*`

Chart CPU used by Applications
path.view - `/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*NexOSS_CPU.*`

Chart-Memory used by Applications
path.view - `/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*NexOSS_Memory.*`

**Comment by JimDalton** [comment]
The following two paths provide the same data.

Chart-Total CPU
path.view - /logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*NexOSS_CPU_Alarm.*

Chart CPU used by Applications
path.view - /logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*NexOSS_CPU.*

The NexOSS_CPU_Alarm data looks correct.  
The NexOSS_CPU data should show CPU by user, system, wait and steal. It does not

**Comment by JimDalton** [comment]
There are many issues related to these pages.  This issues is being closed and opened as multiple new issues focused on specific pages.
