### ISSUE TITLE
Export Rate Plans

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#98]
#### Page Title
Export Rate Plans

#### URL
Old UI: /billing/oss_billing_rate_plan.htm

#### Description of issue
data-viewer Page that lists all Account and Product Rate Plans

On the page provides the view, Alec will create new button to Export Selected Rate Plan

![image](https://cloud.githubusercontent.com/assets/18315382/16533324/e4901a62-3fa5-11e6-9be3-a496bc8f1a53.png)

**Comment by DmitryIsakbayev** [comment]
viewUri: `/analyzer/cgi-bin/data/viewTable.exe?sql=select CustomerName,Type,Name,EffectiveDate,ProvisionedOn,ID from RATEPLAN order by lower(CustomerName) asc,lower(Type) asc,EffectiveDate desc`

Column API are just like they appear in the SQL statement:
CustomerName
Type
Name
EffectiveDate
ProvisionedOn
ID

The current uri for generating a request to export a rate plan is also a SQL statement and I don't think it will work with this UI.  Here is a sample one -
`/analyzer/cgi-bin/action/insertTable.exe?sql=insert into EXPORTRATEPLANQUEUE (CustomerName,Type,Name,EffectiveDate,ProvisionedOn,RatePlanId,Inserted,Updated) 
values ('Ameritech','Term','Ameritech_Inter-State','2016-02-04 00:00:00','2016-02-12 11:11:42.531','26',NOW(),NOW())`

I think I will need to turn it into something like -
`/analyzer/cgi-bin/action/insertTable.exe?sqlTableName=EXPORTRATEPLANQUEUE&sqlColumnNames=CustomerName,Type,Name,EffectiveDate,ProvisionedOn,RatePlanId,Inserted,Updated&Inserted=NOW()&Updated=NOW()`

**Comment by JimDalton** [comment]
Updated config file.
Need to add paths.exportRatePlan column to config file.
Button label should be: Export Rate Plan

View never loads.  The page shows 57 rows loaded, but the rows never become visible.
![image](https://cloud.githubusercontent.com/assets/18315382/16634728/011dabae-439d-11e6-93c8-70ee25c294b6.png)

**Comment by fenichelar** [comment]
Resolved. Please test.

**Comment by JimDalton** [comment]
Work as expected - rates can be viewed.
Still need to add Export Rate Button.  May I add paths.exportRatePlan to config file?

**Comment by fenichelar** [comment]
@JimDalton Yes.

I will need to implement the button action however.

**Comment by DmitryIsakbayev** [comment]
Updated the paths.view to url encode spaces (as %20) and exclude column count and column headers.
`/analyzer/cgi-bin/data/viewTable.exe?showColumnCount=false&showColumnHeaders=false&sql=select%20CustomerName,Type,Name,EffectiveDate,ProvisionedOn,ID%20from%20RATEPLAN%20order%20by%20lower(CustomerName)%20asc,lower(Type)%20asc,EffectiveDate%20desc`

**Comment by fenichelar** [comment]
@JimDalton please use the following url for exporting rate plans:

`/analyzer/cgi-bin/action/insertTable.exe?sql=insert%20into%20EXPORTRATEPLANQUEUE%20(CustomerName,Type,Name,EffectiveDate,ProvisionedOn,RatePlanId,Inserted,Updated)%20values%20('CUSTOMMASKSTARTCustomerNameCUSTOMMASKEND','CUSTOMMASKSTARTTypeCUSTOMMASKEND','CUSTOMMASKSTARTNameCUSTOMMASKEND','CUSTOMMASKSTARTEffectiveDateCUSTOMMASKEND','CUSTOMMASKSTARTProvisionedOnCUSTOMMASKEND','CUSTOMMASKSTARTIDCUSTOMMASKEND',NOW(),NOW())`

**Comment by fenichelar** [comment]
@JimDalton Please change paths.view and paths.exportRatePlan to above values and test.

**Comment by JimDalton** [comment]
Updated paths.view and paths.exportRatePlan in config file.
Need to test.

**Comment by JimDalton** [comment]
Cannot export rate plan.
![image](https://cloud.githubusercontent.com/assets/18315382/17335716/f1d9ae9c-58a8-11e6-9a05-e5691f4963f3.png)

**Comment by DmitryIsakbayev** [comment]
Alec, why did you change the uri for requesting to export the selected rate plan from

`/analyzer/cgi-bin/action/insertTable.exe?sqlTableName=EXPORTRATEPLANQUEUE&sqlColumnNames=CustomerName,Type,Name,EffectiveDate,ProvisionedOn,RatePlanId,Inserted,Updated&Inserted=NOW()&Inserted.quote=false&Updated=NOW()&Updated.quote=false`

to

`/analyzer/cgi-bin/action/insertTable.exe?sql=insert%20into%20EXPORTRATEPLANQUEUE%20(CustomerName,Type,Name,EffectiveDate,ProvisionedOn,RatePlanId,Inserted,Updated)%20values%20('CUSTOMMASKSTARTCustomerNameCUSTOMMASKEND','CUSTOMMASKSTARTTypeCUSTOMMASKEND','CUSTOMMASKSTARTNameCUSTOMMASKEND','CUSTOMMASKSTARTEffectiveDateCUSTOMMASKEND','CUSTOMMASKSTARTProvisionedOnCUSTOMMASKEND','CUSTOMMASKSTARTIDCUSTOMMASKEND',NOW(),NOW())`

**Comment by fenichelar** [comment]
`'CUSTOMMASKSTARTCustomerNameCUSTOMMASKEND','CUSTOMMASKSTARTTypeCUSTOMMASKEND','CUSTOMMASKSTARTNameCUSTOMMASKEND','CUSTOMMASKSTARTEffectiveDateCUSTOMMASKEND','CUSTOMMASKSTARTProvisionedOnCUSTOMMASKEND','CUSTOMMASKSTARTIDCUSTOMMASKEND',NOW(),NOW()` is replaced with the data from the selected row.

**Comment by DmitryIsakbayev** [comment]
Is there a problem using the original URI?
If you want to use the updated version, I think you will need to url encode single quotes.

**Comment by fenichelar** [comment]
Where does the data go on the original URI?

**Comment by fenichelar** [comment]
@DmitryIsakbayev It doesn't matter to me what URI we use, I just need the following strings in the URI and I will replace the string with the data:
- `CUSTOMMASKSTARTCustomerNameCUSTOMMASKEND`
- `CUSTOMMASKSTARTTypeCUSTOMMASKEND`
- `CUSTOMMASKSTARTNameCUSTOMMASKEND`
- `CUSTOMMASKSTARTEffectiveDateCUSTOMMASKEND`
- `CUSTOMMASKSTARTProvisionedOnCUSTOMMASKEND`
- `CUSTOMMASKSTARTIDCUSTOMMASKEND'`

**Comment by DmitryIsakbayev** [comment]
>Where does the data go on the original URI?
Just like it does for update or delete uri.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Call me when you are available.

**Comment by fenichelar** [comment]
Will rewrite to use better API.

**Comment by fenichelar** [comment]
@JimDalton 

Jim please change the API from `ID` to `RatePlanId` for column titled `Rate Plan ID`.

Also please use the following URL: `/analyzer/cgi-bin/action/insertTable.exe?sqlTableName=EXPORTRATEPLANQUEUE&sqlColumnNames=CustomerName,Type,Name,EffectiveDate,ProvisionedOn,RatePlanId,Inserted,Updated&Inserted=NOW()&Inserted.quote=false&Updated=NOW()&Updated.quote=false`

**Comment by fenichelar** [comment]
@DmitryIsakbayev Done. I have tested and it appears to work (I get a 200 status code).

**Comment by JimDalton** [comment]
Updated config file.  Need to test.

**Comment by JimDalton** [comment]
Works as expected.
