### ISSUE TITLE
Pending Rate Plan Export Request

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#99]
#### URL
Old UI:  /billing/oss_billing_pending_rate_export_q.htm

#### Description of issue
View pending rate plans that are being prepared for Export
data-viewer

**Comment by DmitryIsakbayev** [comment]
viewUri `/analyzer/cgi-bin/data/viewTable.exe?sql=select CustomerName,Type,Name,EffectiveDate,ProvisionedOn,RatePlanId,Inserted from EXPORTRATEPLANQUEUE where Updatable='Y' order by Inserted ASC`

**Comment by JimDalton** [comment]
View of rate plans does not load.
![image](https://cloud.githubusercontent.com/assets/18315382/16663780/6c8b2c28-444b-11e6-9308-ee551644b779.png)

**Comment by fenichelar** [comment]
The type of this page should be `data-viewer`.

**Comment by JimDalton** [comment]
Page type has been changed to data-viewer.  Pending rate plans still cannot be viewed.  "No matching records found" is displayed on the new UI.

Configured paths.view url is:/analyzer/cgi-bin/data/viewTable.exe?sql=select CustomerName,Type,Name,EffectiveDate,ProvisionedOn,RatePlanId,Inserted from EXPORTRATEPLANQUEUE where Updatable='Y' order by Inserted ASC

For Information: url from Java console is: /analyzer/cgi-bin/data/viewTable.exe?sql=select+CustomerName%2CType%2CName%2CEffectiveDate%2CProvisionedOn%2CRatePlanId%2CInserted%2C%27FakeGroupByValue%27+as+%22FakeGroupByColumn%22+from+EXPORTRATEPLANQUEUE+where+Updatable%3D%27Y%27+order+by+Inserted+ASC

**Comment by DmitryIsakbayev** [comment]
Looks like the tsv2json.awk script is removing single quotes.   Let's url encode the single quotes as %27
view url: `/analyzer/cgi-bin/data/viewTable.exe?sql=select CustomerName,Type,Name,EffectiveDate,ProvisionedOn,RatePlanId,Inserted from EXPORTRATEPLANQUEUE where Updatable=%27Y%27 order by Inserted ASC`

**Comment by JimDalton** [comment]
Updated paths.view to be: /analyzer/cgi-bin/data/viewTable.exe?sql=select CustomerName,Type,Name,EffectiveDate,ProvisionedOn,RatePlanId,Inserted from EXPORTRATEPLANQUEUE where Updatable=%27Y%27 order by Inserted ASC

Need to test

**Comment by JimDalton** [comment]
View of pending rate plans includes Column Count and Titles.
![image](https://cloud.githubusercontent.com/assets/18315382/16884889/e33f3356-4a99-11e6-8c63-c4eb2abb3556.png)

**Comment by DmitryIsakbayev** [comment]
Updated the paths.view to url encode spaces (as %20) and exclude column count and column headers
`/analyzer/cgi-bin/data/viewTable.exe?showColumnCount=false&showColumnHeaders=false&sql=select%20CustomerName,Type,Name,EffectiveDate,ProvisionedOn,RatePlanId,Inserted%20from%20EXPORTRATEPLANQUEUE%20where%20Updatable=%27Y%27%20order%20by%20Inserted%20ASC`

**Comment by JimDalton** [comment]
Updated paths.view.
Need to test

**Comment by JimDalton** [comment]
Works as expected
